/*
Copyright (c) 2023-2026 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cmd/genmock. DO NOT EDIT.

// Code generated by cmd/genservice. DO NOT EDIT.

package yellowpages

import (
	"context"
	"net/http"
	"testing"
	"time"

	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/examples/yellowpages/yellowpagesapi"
	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/testarossa"
)

func TestYellowpages_Mock(t *testing.T) {
	t.Parallel()
	ctx := t.Context()

	mock := NewMock()
	mock.SetDeployment(connector.TESTING)

	t.Run("on_startup", func(t *testing.T) {
		assert := testarossa.For(t)
		err := mock.OnStartup(ctx)
		assert.NoError(err)
	})

	t.Run("on_shutdown", func(t *testing.T) {
		assert := testarossa.For(t)
		err := mock.OnShutdown(ctx)
		assert.NoError(err)
	})

	t.Run("create", func(t *testing.T) { // MARKER: Create
		assert := testarossa.For(t)

		mock.MockCreate(func(ctx context.Context, obj *yellowpagesapi.Person) (objKey yellowpagesapi.PersonKey, err error) {
			return
		})
		var obj *yellowpagesapi.Person
		_, err := mock.Create(ctx, obj)
		assert.NoError(err)
	})

	t.Run("store", func(t *testing.T) { // MARKER: Store
		assert := testarossa.For(t)

		mock.MockStore(func(ctx context.Context, obj *yellowpagesapi.Person) (stored bool, err error) {
			return
		})
		var obj *yellowpagesapi.Person
		_, err := mock.Store(ctx, obj)
		assert.NoError(err)
	})

	t.Run("must_store", func(t *testing.T) { // MARKER: MustStore
		assert := testarossa.For(t)

		mock.MockMustStore(func(ctx context.Context, obj *yellowpagesapi.Person) (err error) {
			return
		})
		var obj *yellowpagesapi.Person
		err := mock.MustStore(ctx, obj)
		assert.NoError(err)
	})

	t.Run("revise", func(t *testing.T) { // MARKER: Revise
		assert := testarossa.For(t)

		mock.MockRevise(func(ctx context.Context, obj *yellowpagesapi.Person) (revised bool, err error) {
			return
		})
		var obj *yellowpagesapi.Person
		_, err := mock.Revise(ctx, obj)
		assert.NoError(err)
	})

	t.Run("must_revise", func(t *testing.T) { // MARKER: MustRevise
		assert := testarossa.For(t)

		mock.MockMustRevise(func(ctx context.Context, obj *yellowpagesapi.Person) (err error) {
			return
		})
		var obj *yellowpagesapi.Person
		err := mock.MustRevise(ctx, obj)
		assert.NoError(err)
	})

	t.Run("delete", func(t *testing.T) { // MARKER: Delete
		assert := testarossa.For(t)

		mock.MockDelete(func(ctx context.Context, objKey yellowpagesapi.PersonKey) (deleted bool, err error) {
			return
		})
		var objKey yellowpagesapi.PersonKey
		_, err := mock.Delete(ctx, objKey)
		assert.NoError(err)
	})

	t.Run("must_delete", func(t *testing.T) { // MARKER: MustDelete
		assert := testarossa.For(t)

		mock.MockMustDelete(func(ctx context.Context, objKey yellowpagesapi.PersonKey) (err error) {
			return
		})
		var objKey yellowpagesapi.PersonKey
		err := mock.MustDelete(ctx, objKey)
		assert.NoError(err)
	})

	t.Run("list", func(t *testing.T) { // MARKER: List
		assert := testarossa.For(t)

		mock.MockList(func(ctx context.Context, query yellowpagesapi.Query) (objs []*yellowpagesapi.Person, totalCount int, err error) {
			return
		})
		var query yellowpagesapi.Query
		_, _, err := mock.List(ctx, query)
		assert.NoError(err)
	})

	t.Run("lookup", func(t *testing.T) { // MARKER: Lookup
		assert := testarossa.For(t)

		mock.MockLookup(func(ctx context.Context, query yellowpagesapi.Query) (obj *yellowpagesapi.Person, found bool, err error) {
			return
		})
		var query yellowpagesapi.Query
		_, _, err := mock.Lookup(ctx, query)
		assert.NoError(err)
	})

	t.Run("must_lookup", func(t *testing.T) { // MARKER: MustLookup
		assert := testarossa.For(t)

		mock.MockMustLookup(func(ctx context.Context, query yellowpagesapi.Query) (obj *yellowpagesapi.Person, err error) {
			return
		})
		var query yellowpagesapi.Query
		_, err := mock.MustLookup(ctx, query)
		assert.NoError(err)
	})

	t.Run("load", func(t *testing.T) { // MARKER: Load
		assert := testarossa.For(t)

		mock.MockLoad(func(ctx context.Context, objKey yellowpagesapi.PersonKey) (obj *yellowpagesapi.Person, found bool, err error) {
			return
		})
		var objKey yellowpagesapi.PersonKey
		_, _, err := mock.Load(ctx, objKey)
		assert.NoError(err)
	})

	t.Run("must_load", func(t *testing.T) { // MARKER: MustLoad
		assert := testarossa.For(t)

		mock.MockMustLoad(func(ctx context.Context, objKey yellowpagesapi.PersonKey) (obj *yellowpagesapi.Person, err error) {
			return
		})
		var objKey yellowpagesapi.PersonKey
		_, err := mock.MustLoad(ctx, objKey)
		assert.NoError(err)
	})

	t.Run("bulk_load", func(t *testing.T) { // MARKER: BulkLoad
		assert := testarossa.For(t)

		mock.MockBulkLoad(func(ctx context.Context, objKeys []yellowpagesapi.PersonKey) (objs []*yellowpagesapi.Person, err error) {
			return
		})
		var objKeys []yellowpagesapi.PersonKey
		_, err := mock.BulkLoad(ctx, objKeys)
		assert.NoError(err)
	})

	t.Run("bulk_delete", func(t *testing.T) { // MARKER: BulkDelete
		assert := testarossa.For(t)

		mock.MockBulkDelete(func(ctx context.Context, objKeys []yellowpagesapi.PersonKey) (deletedKeys []yellowpagesapi.PersonKey, err error) {
			return
		})
		var objKeys []yellowpagesapi.PersonKey
		_, err := mock.BulkDelete(ctx, objKeys)
		assert.NoError(err)
	})

	t.Run("bulk_create", func(t *testing.T) { // MARKER: BulkCreate
		assert := testarossa.For(t)

		mock.MockBulkCreate(func(ctx context.Context, objs []*yellowpagesapi.Person) (objKeys []yellowpagesapi.PersonKey, err error) {
			return
		})
		var objs []*yellowpagesapi.Person
		_, err := mock.BulkCreate(ctx, objs)
		assert.NoError(err)
	})

	t.Run("bulk_store", func(t *testing.T) { // MARKER: BulkStore
		assert := testarossa.For(t)

		mock.MockBulkStore(func(ctx context.Context, objs []*yellowpagesapi.Person) (storedKeys []yellowpagesapi.PersonKey, err error) {
			return
		})
		var objs []*yellowpagesapi.Person
		_, err := mock.BulkStore(ctx, objs)
		assert.NoError(err)
	})

	t.Run("bulk_revise", func(t *testing.T) { // MARKER: BulkRevise
		assert := testarossa.For(t)

		mock.MockBulkRevise(func(ctx context.Context, objs []*yellowpagesapi.Person) (revisedKeys []yellowpagesapi.PersonKey, err error) {
			return
		})
		var objs []*yellowpagesapi.Person
		_, err := mock.BulkRevise(ctx, objs)
		assert.NoError(err)
	})

	t.Run("purge", func(t *testing.T) { // MARKER: Purge
		assert := testarossa.For(t)

		mock.MockPurge(func(ctx context.Context, query yellowpagesapi.Query) (deletedKeys []yellowpagesapi.PersonKey, err error) {
			return
		})
		var query yellowpagesapi.Query
		_, err := mock.Purge(ctx, query)
		assert.NoError(err)
	})

	t.Run("count", func(t *testing.T) { // MARKER: Count
		assert := testarossa.For(t)

		mock.MockCount(func(ctx context.Context, query yellowpagesapi.Query) (count int, err error) {
			return
		})
		var query yellowpagesapi.Query
		_, err := mock.Count(ctx, query)
		assert.NoError(err)
	})

	t.Run("create_r_e_s_t", func(t *testing.T) { // MARKER: CreateREST
		assert := testarossa.For(t)

		mock.MockCreateREST(func(ctx context.Context, httpRequestBody *yellowpagesapi.Person) (objKey yellowpagesapi.PersonKey, httpStatusCode int, err error) {
			return
		})
		var httpRequestBody *yellowpagesapi.Person
		_, _, err := mock.CreateREST(ctx, httpRequestBody)
		assert.NoError(err)
	})

	t.Run("store_r_e_s_t", func(t *testing.T) { // MARKER: StoreREST
		assert := testarossa.For(t)

		mock.MockStoreREST(func(ctx context.Context, key yellowpagesapi.PersonKey, httpRequestBody *yellowpagesapi.Person) (httpStatusCode int, err error) {
			return
		})
		var key yellowpagesapi.PersonKey
		var httpRequestBody *yellowpagesapi.Person
		_, err := mock.StoreREST(ctx, key, httpRequestBody)
		assert.NoError(err)
	})

	t.Run("delete_r_e_s_t", func(t *testing.T) { // MARKER: DeleteREST
		assert := testarossa.For(t)

		mock.MockDeleteREST(func(ctx context.Context, key yellowpagesapi.PersonKey) (httpStatusCode int, err error) {
			return
		})
		var key yellowpagesapi.PersonKey
		_, err := mock.DeleteREST(ctx, key)
		assert.NoError(err)
	})

	t.Run("load_r_e_s_t", func(t *testing.T) { // MARKER: LoadREST
		assert := testarossa.For(t)

		mock.MockLoadREST(func(ctx context.Context, key yellowpagesapi.PersonKey) (httpResponseBody *yellowpagesapi.Person, httpStatusCode int, err error) {
			return
		})
		var key yellowpagesapi.PersonKey
		_, _, err := mock.LoadREST(ctx, key)
		assert.NoError(err)
	})

	t.Run("list_r_e_s_t", func(t *testing.T) { // MARKER: ListREST
		assert := testarossa.For(t)

		mock.MockListREST(func(ctx context.Context, q yellowpagesapi.Query) (httpResponseBody []*yellowpagesapi.Person, httpStatusCode int, err error) {
			return
		})
		var q yellowpagesapi.Query
		_, _, err := mock.ListREST(ctx, q)
		assert.NoError(err)
	})

	t.Run("try_reserve", func(t *testing.T) { // MARKER: TryReserve
		assert := testarossa.For(t)

		mock.MockTryReserve(func(ctx context.Context, objKey yellowpagesapi.PersonKey, dur time.Duration) (reserved bool, err error) {
			return
		})
		var objKey yellowpagesapi.PersonKey
		var dur time.Duration
		_, err := mock.TryReserve(ctx, objKey, dur)
		assert.NoError(err)
	})

	t.Run("try_bulk_reserve", func(t *testing.T) { // MARKER: TryBulkReserve
		assert := testarossa.For(t)

		mock.MockTryBulkReserve(func(ctx context.Context, objKeys []yellowpagesapi.PersonKey, dur time.Duration) (reservedKeys []yellowpagesapi.PersonKey, err error) {
			return
		})
		var objKeys []yellowpagesapi.PersonKey
		var dur time.Duration
		_, err := mock.TryBulkReserve(ctx, objKeys, dur)
		assert.NoError(err)
	})

	t.Run("reserve", func(t *testing.T) { // MARKER: Reserve
		assert := testarossa.For(t)

		mock.MockReserve(func(ctx context.Context, objKey yellowpagesapi.PersonKey, dur time.Duration) (reserved bool, err error) {
			return
		})
		var objKey yellowpagesapi.PersonKey
		var dur time.Duration
		_, err := mock.Reserve(ctx, objKey, dur)
		assert.NoError(err)
	})

	t.Run("bulk_reserve", func(t *testing.T) { // MARKER: BulkReserve
		assert := testarossa.For(t)

		mock.MockBulkReserve(func(ctx context.Context, objKeys []yellowpagesapi.PersonKey, dur time.Duration) (reservedKeys []yellowpagesapi.PersonKey, err error) {
			return
		})
		var objKeys []yellowpagesapi.PersonKey
		var dur time.Duration
		_, err := mock.BulkReserve(ctx, objKeys, dur)
		assert.NoError(err)
	})

	t.Run("demo", func(t *testing.T) { // MARKER: Demo
		assert := testarossa.For(t)

		mock.MockDemo(func(w http.ResponseWriter, r *http.Request) (err error) {
			return nil
		})
		w := httpx.NewResponseRecorder()
		r := httpx.MustNewRequest("GET", "/", nil)
		err := mock.Demo(w, r)
		assert.NoError(err)
	})

}
