graph LR
    classDef task fill:#32a7c1,color:#f4f2ef,stroke:#32a7c1
    classDef term fill:#e5f4f3,color:#434343,stroke:#32a7c1
    classDef note fill:none,stroke:none,color:#32a7c1,font-size:0.8em
    linkStyle default stroke:#32a7c1

    _title{{"alias"}}:::term -.-> _start
    t0["s"]:::task
    t1["a"]:::task
    t2["b"]:::task
    t3["c"]:::task
    t4["bPrime"]:::task
    t5["d"]:::task
    t0 --> t1
    t0 -->|"goto"| t4
    t1 --> t2
    t2 --> t3
    t4 --> t5
    _start(( )):::term --> t0
    t3 --> _end(( )):::term
    t5 --> _end(( )):::term
