/*
Copyright (c) 2023-2026 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cmd/genmock. DO NOT EDIT.

package aliasflow

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/fabric/sub"
	"github.com/microbus-io/fabric/utils"
	"github.com/microbus-io/fabric/workflow"

	"github.com/microbus-io/fabric/verify/aliasflow/aliasflowapi"
)

// Mock is a mockable version of the microservice, allowing functions, event sinks and web handlers to be mocked.
type Mock struct {
	*Intermediate
	mockTaskS      func(ctx context.Context, flow *workflow.Flow, branch string) (branchOut string, err error) // MARKER: TaskS
	mockTaskA      func(ctx context.Context, flow *workflow.Flow, path string) (pathOut string, err error)     // MARKER: TaskA
	mockTaskB      func(ctx context.Context, flow *workflow.Flow, path string) (pathOut string, err error)     // MARKER: TaskB
	mockTaskC      func(ctx context.Context, flow *workflow.Flow, path string) (pathOut string, err error)     // MARKER: TaskC
	mockTaskD      func(ctx context.Context, flow *workflow.Flow, path string) (pathOut string, err error)     // MARKER: TaskD
	mockAliasGraph func(ctx context.Context) (graph *workflow.Graph, err error)                                // MARKER: Alias
	unsubMockAlias func() error                                                                                // MARKER: Alias
}

// NewMock creates a new mockable version of the microservice.
func NewMock() *Mock {
	svc := &Mock{}
	svc.Intermediate = NewIntermediate(svc)
	svc.SetVersion(7357) // Stands for TEST
	return svc
}

// OnStartup is called when the microservice is started up.
func (svc *Mock) OnStartup(ctx context.Context) (err error) {
	if svc.Deployment() != connector.LOCAL && svc.Deployment() != connector.TESTING {
		return errors.New("mocking disallowed in %s deployment", svc.Deployment())
	}
	return nil
}

// OnShutdown is called when the microservice is shut down.
func (svc *Mock) OnShutdown(ctx context.Context) (err error) {
	return nil
}

// MockTaskS sets up a mock handler for TaskS.
func (svc *Mock) MockTaskS(handler func(ctx context.Context, flow *workflow.Flow, branch string) (branchOut string, err error)) *Mock { // MARKER: TaskS
	svc.mockTaskS = handler
	return svc
}

// TaskS executes the mock handler.
func (svc *Mock) TaskS(ctx context.Context, flow *workflow.Flow, branch string) (branchOut string, err error) { // MARKER: TaskS
	if svc.mockTaskS != nil {
		branchOut, err = svc.mockTaskS(ctx, flow, branch)
	}
	return branchOut, errors.Trace(err)
}

// MockTaskA sets up a mock handler for TaskA.
func (svc *Mock) MockTaskA(handler func(ctx context.Context, flow *workflow.Flow, path string) (pathOut string, err error)) *Mock { // MARKER: TaskA
	svc.mockTaskA = handler
	return svc
}

// TaskA executes the mock handler.
func (svc *Mock) TaskA(ctx context.Context, flow *workflow.Flow, path string) (pathOut string, err error) { // MARKER: TaskA
	if svc.mockTaskA != nil {
		pathOut, err = svc.mockTaskA(ctx, flow, path)
	}
	return pathOut, errors.Trace(err)
}

// MockTaskB sets up a mock handler for TaskB.
func (svc *Mock) MockTaskB(handler func(ctx context.Context, flow *workflow.Flow, path string) (pathOut string, err error)) *Mock { // MARKER: TaskB
	svc.mockTaskB = handler
	return svc
}

// TaskB executes the mock handler.
func (svc *Mock) TaskB(ctx context.Context, flow *workflow.Flow, path string) (pathOut string, err error) { // MARKER: TaskB
	if svc.mockTaskB != nil {
		pathOut, err = svc.mockTaskB(ctx, flow, path)
	}
	return pathOut, errors.Trace(err)
}

// MockTaskC sets up a mock handler for TaskC.
func (svc *Mock) MockTaskC(handler func(ctx context.Context, flow *workflow.Flow, path string) (pathOut string, err error)) *Mock { // MARKER: TaskC
	svc.mockTaskC = handler
	return svc
}

// TaskC executes the mock handler.
func (svc *Mock) TaskC(ctx context.Context, flow *workflow.Flow, path string) (pathOut string, err error) { // MARKER: TaskC
	if svc.mockTaskC != nil {
		pathOut, err = svc.mockTaskC(ctx, flow, path)
	}
	return pathOut, errors.Trace(err)
}

// MockTaskD sets up a mock handler for TaskD.
func (svc *Mock) MockTaskD(handler func(ctx context.Context, flow *workflow.Flow, path string) (pathOut string, err error)) *Mock { // MARKER: TaskD
	svc.mockTaskD = handler
	return svc
}

// TaskD executes the mock handler.
func (svc *Mock) TaskD(ctx context.Context, flow *workflow.Flow, path string) (pathOut string, err error) { // MARKER: TaskD
	if svc.mockTaskD != nil {
		pathOut, err = svc.mockTaskD(ctx, flow, path)
	}
	return pathOut, errors.Trace(err)
}

// MockAlias sets up a mock handler for the Alias workflow.
// The handler receives typed inputs from the workflow's state and returns typed outputs.
// A nil handler clears the mock.
func (svc *Mock) MockAlias(handler func(ctx context.Context, flow *workflow.Flow, branch string) (path string, err error)) *Mock { // MARKER: Alias
	if svc.unsubMockAlias != nil {
		svc.unsubMockAlias()
		svc.unsubMockAlias = nil
	}
	if handler == nil {
		svc.mockAliasGraph = nil
		return svc
	}
	mockName := "MockAlias" + utils.RandomIdentifier(8)
	mockRoute := ":428/mock-alias-" + utils.RandomIdentifier(8)
	mockTaskURL := httpx.JoinHostAndPath(svc.Hostname(), mockRoute)
	svc.mockAliasGraph = func(ctx context.Context) (graph *workflow.Graph, err error) {
		g := workflow.NewGraph(aliasflowapi.Alias.URL())
		g.AddTransition(mockTaskURL, workflow.END)
		return g, nil
	}
	err := svc.Subscribe(mockName, func(w http.ResponseWriter, r *http.Request) error {
		var f workflow.Flow
		if err := json.NewDecoder(r.Body).Decode(&f); err != nil {
			return errors.Trace(err)
		}
		snap := f.Snapshot()
		var in aliasflowapi.AliasIn
		f.ParseState(&in)
		path, err := handler(r.Context(), &f, in.Branch)
		if err != nil {
			return err // No trace
		}
		out := aliasflowapi.AliasOut{Path: path}
		f.SetChanges(out, snap)
		w.Header().Set("Content-Type", "application/json")
		return json.NewEncoder(w).Encode(&f)
	},
		sub.At("POST", mockRoute),
		sub.Task(aliasflowapi.AliasIn{}, aliasflowapi.AliasOut{}),
	)
	if err == nil {
		svc.unsubMockAlias = func() error { return svc.Unsubscribe(mockName) }
	}
	return svc
}

// Alias returns the workflow graph, or a mocked graph if MockAlias was called.
func (svc *Mock) Alias(ctx context.Context) (graph *workflow.Graph, err error) { // MARKER: Alias
	if svc.mockAliasGraph != nil {
		graph, err = svc.mockAliasGraph(ctx)
	}
	return graph, errors.Trace(err)
}
