// Code generated by cmd/genservice. DO NOT EDIT.

package weirdapi

import (
	"context"
	"iter"
	"net/http"
	"reflect"

	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/fabric/pub"
	"github.com/microbus-io/fabric/service"
	"github.com/microbus-io/fabric/sub"
)

// multicastResponse packs the response of a functional multicast.
type multicastResponse struct {
	data         any
	HTTPResponse *http.Response
	err          error
}

// Client is a lightweight proxy for making unicast calls to the microservice.
type Client struct {
	svc  service.Publisher
	host string
	opts []pub.Option
}

// NewClient creates a new unicast client proxy to the microservice.
func NewClient(caller service.Publisher) Client {
	return Client{svc: caller, host: Hostname}
}

// ForHost returns a copy of the client with a different hostname to be applied to requests.
func (_c Client) ForHost(host string) Client {
	return Client{svc: _c.svc, host: host, opts: _c.opts}
}

// WithOptions returns a copy of the client with options to be applied to requests.
func (_c Client) WithOptions(opts ...pub.Option) Client {
	return Client{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...)}
}

// MulticastClient is a lightweight proxy for making multicast calls to the microservice.
type MulticastClient struct {
	svc  service.Publisher
	host string
	opts []pub.Option
}

// NewMulticastClient creates a new multicast client proxy to the microservice.
func NewMulticastClient(caller service.Publisher) MulticastClient {
	return MulticastClient{svc: caller, host: Hostname}
}

// ForHost returns a copy of the client with a different hostname to be applied to requests.
func (_c MulticastClient) ForHost(host string) MulticastClient {
	return MulticastClient{svc: _c.svc, host: host, opts: _c.opts}
}

// WithOptions returns a copy of the client with options to be applied to requests.
func (_c MulticastClient) WithOptions(opts ...pub.Option) MulticastClient {
	return MulticastClient{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...)}
}

// MulticastTrigger is a lightweight proxy for triggering the events of the microservice.
type MulticastTrigger struct {
	svc  service.Publisher
	host string
	opts []pub.Option
}

// NewMulticastTrigger creates a new multicast trigger of events of the microservice.
func NewMulticastTrigger(caller service.Publisher) MulticastTrigger {
	return MulticastTrigger{svc: caller, host: Hostname}
}

// ForHost returns a copy of the trigger with a different hostname to be applied to requests.
func (_c MulticastTrigger) ForHost(host string) MulticastTrigger {
	return MulticastTrigger{svc: _c.svc, host: host, opts: _c.opts}
}

// WithOptions returns a copy of the trigger with options to be applied to requests.
func (_c MulticastTrigger) WithOptions(opts ...pub.Option) MulticastTrigger {
	return MulticastTrigger{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...)}
}

// Hook assists in the subscription to the events of the microservice.
type Hook struct {
	svc  service.Subscriber
	host string
	opts []sub.Option
}

// NewHook creates a new hook to the events of the microservice.
func NewHook(listener service.Subscriber) Hook {
	return Hook{svc: listener, host: Hostname}
}

// ForHost returns a copy of the hook with a different hostname to be applied to the subscription.
func (c Hook) ForHost(host string) Hook {
	return Hook{svc: c.svc, host: host, opts: c.opts}
}

// WithOptions returns a copy of the hook with options to be applied to subscriptions.
func (c Hook) WithOptions(opts ...sub.Option) Hook {
	return Hook{svc: c.svc, host: c.host, opts: append(c.opts, opts...)}
}

// marshalRequest supports functional endpoints.
func marshalRequest(ctx context.Context, svc service.Publisher, opts []pub.Option, host string, method string, route string, in any, out any) (err error) {
	if method == "ANY" {
		method = "POST"
	}
	u := httpx.JoinHostAndPath(host, route)
	query, body, err := httpx.WriteInputPayload(method, in)
	if err != nil {
		return err // No trace
	}
	httpRes, err := svc.Request(
		ctx,
		pub.Method(method),
		pub.URL(u),
		pub.Query(query),
		pub.Body(body),
		pub.Options(opts...),
	)
	if err != nil {
		return err // No trace
	}
	err = httpx.ReadOutputPayload(httpRes, out)
	return errors.Trace(err)
}

// marshalPublish supports multicast functional endpoints.
func marshalPublish(ctx context.Context, svc service.Publisher, opts []pub.Option, host string, method string, route string, in any, out any) iter.Seq[*multicastResponse] {
	if method == "ANY" {
		method = "POST"
	}
	u := httpx.JoinHostAndPath(host, route)
	query, body, err := httpx.WriteInputPayload(method, in)
	if err != nil {
		return func(yield func(*multicastResponse) bool) {
			yield(&multicastResponse{err: err})
		}
	}
	_queue := svc.Publish(
		ctx,
		pub.Method(method),
		pub.URL(u),
		pub.Query(query),
		pub.Body(body),
		pub.Options(opts...),
	)
	return func(yield func(*multicastResponse) bool) {
		for qi := range _queue {
			httpResp, err := qi.Get()
			if err == nil {
				reflect.ValueOf(out).Elem().SetZero()
				err = httpx.ReadOutputPayload(httpResp, out)
			}
			if err != nil {
				if !yield(&multicastResponse{err: err, HTTPResponse: httpResp}) {
					return
				}
			} else {
				if !yield(&multicastResponse{data: out, HTTPResponse: httpResp}) {
					return
				}
			}
		}
	}
}

// marshalFunction handles marshaling for functional endpoints.
func marshalFunction(w http.ResponseWriter, r *http.Request, route string, in any, out any, execute func(in any, out any) error) error {
	err := httpx.ReadInputPayload(r, route, in)
	if err != nil {
		return errors.Trace(err)
	}
	err = execute(in, out)
	if err != nil {
		return err // No trace
	}
	err = httpx.WriteOutputPayload(w, out)
	if err != nil {
		return errors.Trace(err)
	}
	return nil
}

// Plain is a baseline function on the safe trust segment.
func (_c Client) Plain(ctx context.Context) (result string, err error) { // MARKER: Plain
	_in := PlainIn{}
	_out := PlainOut{}
	err = marshalRequest(ctx, _c.svc, _c.opts, _c.host, Plain.Method, Plain.Route, &_in, &_out)
	return _out.Result, err // No trace
}

// PlainResponse packs the response of Plain.
type PlainResponse multicastResponse // MARKER: Plain

// Get unpacks the return arguments of Plain.
func (_res *PlainResponse) Get() (result string, err error) { // MARKER: Plain
	_d := _res.data.(*PlainOut)
	return _d.Result, _res.err
}

// Plain is a baseline function on the safe trust segment.
func (_c MulticastClient) Plain(ctx context.Context) iter.Seq[*PlainResponse] { // MARKER: Plain
	_in := PlainIn{}
	_out := PlainOut{}
	_queue := marshalPublish(ctx, _c.svc, _c.opts, _c.host, Plain.Method, Plain.Route, &_in, &_out)
	return func(yield func(*PlainResponse) bool) {
		for _r := range _queue {
			_clone := _out
			_r.data = &_clone
			if !yield((*PlainResponse)(_r)) {
				return
			}
		}
	}
}

// PathArg accepts a path argument.
func (_c Client) PathArg(ctx context.Context, id string) (err error) { // MARKER: PathArg
	_in := PathArgIn{ID: id}
	_out := PathArgOut{}
	err = marshalRequest(ctx, _c.svc, _c.opts, _c.host, PathArg.Method, PathArg.Route, &_in, &_out)
	return err // No trace
}

// PathArgResponse packs the response of PathArg.
type PathArgResponse multicastResponse // MARKER: PathArg

// Get unpacks the return arguments of PathArg.
func (_res *PathArgResponse) Get() (err error) { // MARKER: PathArg
	return _res.err
}

// PathArg accepts a path argument.
func (_c MulticastClient) PathArg(ctx context.Context, id string) iter.Seq[*PathArgResponse] { // MARKER: PathArg
	_in := PathArgIn{ID: id}
	_out := PathArgOut{}
	_queue := marshalPublish(ctx, _c.svc, _c.opts, _c.host, PathArg.Method, PathArg.Route, &_in, &_out)
	return func(yield func(*PathArgResponse) bool) {
		for _r := range _queue {
			_clone := _out
			_r.data = &_clone
			if !yield((*PathArgResponse)(_r)) {
				return
			}
		}
	}
}

// GreedyArg accepts a greedy tail path argument.
func (_c Client) GreedyArg(ctx context.Context, tail string) (err error) { // MARKER: GreedyArg
	_in := GreedyArgIn{Tail: tail}
	_out := GreedyArgOut{}
	err = marshalRequest(ctx, _c.svc, _c.opts, _c.host, GreedyArg.Method, GreedyArg.Route, &_in, &_out)
	return err // No trace
}

// GreedyArgResponse packs the response of GreedyArg.
type GreedyArgResponse multicastResponse // MARKER: GreedyArg

// Get unpacks the return arguments of GreedyArg.
func (_res *GreedyArgResponse) Get() (err error) { // MARKER: GreedyArg
	return _res.err
}

// GreedyArg accepts a greedy tail path argument.
func (_c MulticastClient) GreedyArg(ctx context.Context, tail string) iter.Seq[*GreedyArgResponse] { // MARKER: GreedyArg
	_in := GreedyArgIn{Tail: tail}
	_out := GreedyArgOut{}
	_queue := marshalPublish(ctx, _c.svc, _c.opts, _c.host, GreedyArg.Method, GreedyArg.Route, &_in, &_out)
	return func(yield func(*GreedyArgResponse) bool) {
		for _r := range _queue {
			_clone := _out
			_r.data = &_clone
			if !yield((*GreedyArgResponse)(_r)) {
				return
			}
		}
	}
}

// PeriodInPath has a period inside its path segment.
func (_c Client) PeriodInPath(ctx context.Context) (err error) { // MARKER: PeriodInPath
	_in := PeriodInPathIn{}
	_out := PeriodInPathOut{}
	err = marshalRequest(ctx, _c.svc, _c.opts, _c.host, PeriodInPath.Method, PeriodInPath.Route, &_in, &_out)
	return err // No trace
}

// PeriodInPathResponse packs the response of PeriodInPath.
type PeriodInPathResponse multicastResponse // MARKER: PeriodInPath

// Get unpacks the return arguments of PeriodInPath.
func (_res *PeriodInPathResponse) Get() (err error) { // MARKER: PeriodInPath
	return _res.err
}

// PeriodInPath has a period inside its path segment.
func (_c MulticastClient) PeriodInPath(ctx context.Context) iter.Seq[*PeriodInPathResponse] { // MARKER: PeriodInPath
	_in := PeriodInPathIn{}
	_out := PeriodInPathOut{}
	_queue := marshalPublish(ctx, _c.svc, _c.opts, _c.host, PeriodInPath.Method, PeriodInPath.Route, &_in, &_out)
	return func(yield func(*PeriodInPathResponse) bool) {
		for _r := range _queue {
			_clone := _out
			_r.data = &_clone
			if !yield((*PeriodInPathResponse)(_r)) {
				return
			}
		}
	}
}

// AnyMethod accepts any HTTP method.
func (_c Client) AnyMethod(ctx context.Context) (err error) { // MARKER: AnyMethod
	_in := AnyMethodIn{}
	_out := AnyMethodOut{}
	err = marshalRequest(ctx, _c.svc, _c.opts, _c.host, AnyMethod.Method, AnyMethod.Route, &_in, &_out)
	return err // No trace
}

// AnyMethodResponse packs the response of AnyMethod.
type AnyMethodResponse multicastResponse // MARKER: AnyMethod

// Get unpacks the return arguments of AnyMethod.
func (_res *AnyMethodResponse) Get() (err error) { // MARKER: AnyMethod
	return _res.err
}

// AnyMethod accepts any HTTP method.
func (_c MulticastClient) AnyMethod(ctx context.Context) iter.Seq[*AnyMethodResponse] { // MARKER: AnyMethod
	_in := AnyMethodIn{}
	_out := AnyMethodOut{}
	_queue := marshalPublish(ctx, _c.svc, _c.opts, _c.host, AnyMethod.Method, AnyMethod.Route, &_in, &_out)
	return func(yield func(*AnyMethodResponse) bool) {
		for _r := range _queue {
			_clone := _out
			_r.data = &_clone
			if !yield((*AnyMethodResponse)(_r)) {
				return
			}
		}
	}
}

// InternalPort is on the :444 internal port.
func (_c Client) InternalPort(ctx context.Context) (err error) { // MARKER: InternalPort
	_in := InternalPortIn{}
	_out := InternalPortOut{}
	err = marshalRequest(ctx, _c.svc, _c.opts, _c.host, InternalPort.Method, InternalPort.Route, &_in, &_out)
	return err // No trace
}

// InternalPortResponse packs the response of InternalPort.
type InternalPortResponse multicastResponse // MARKER: InternalPort

// Get unpacks the return arguments of InternalPort.
func (_res *InternalPortResponse) Get() (err error) { // MARKER: InternalPort
	return _res.err
}

// InternalPort is on the :444 internal port.
func (_c MulticastClient) InternalPort(ctx context.Context) iter.Seq[*InternalPortResponse] { // MARKER: InternalPort
	_in := InternalPortIn{}
	_out := InternalPortOut{}
	_queue := marshalPublish(ctx, _c.svc, _c.opts, _c.host, InternalPort.Method, InternalPort.Route, &_in, &_out)
	return func(yield func(*InternalPortResponse) bool) {
		for _r := range _queue {
			_clone := _out
			_r.data = &_clone
			if !yield((*InternalPortResponse)(_r)) {
				return
			}
		}
	}
}

// TrustRoot is the trust-root :666 endpoint.
func (_c Client) TrustRoot(ctx context.Context, cmd string) (err error) { // MARKER: TrustRoot
	_in := TrustRootIn{Cmd: cmd}
	_out := TrustRootOut{}
	err = marshalRequest(ctx, _c.svc, _c.opts, _c.host, TrustRoot.Method, TrustRoot.Route, &_in, &_out)
	return err // No trace
}

// TrustRootResponse packs the response of TrustRoot.
type TrustRootResponse multicastResponse // MARKER: TrustRoot

// Get unpacks the return arguments of TrustRoot.
func (_res *TrustRootResponse) Get() (err error) { // MARKER: TrustRoot
	return _res.err
}

// TrustRoot is the trust-root :666 endpoint.
func (_c MulticastClient) TrustRoot(ctx context.Context, cmd string) iter.Seq[*TrustRootResponse] { // MARKER: TrustRoot
	_in := TrustRootIn{Cmd: cmd}
	_out := TrustRootOut{}
	_queue := marshalPublish(ctx, _c.svc, _c.opts, _c.host, TrustRoot.Method, TrustRoot.Route, &_in, &_out)
	return func(yield func(*TrustRootResponse) bool) {
		for _r := range _queue {
			_clone := _out
			_r.data = &_clone
			if !yield((*TrustRootResponse)(_r)) {
				return
			}
		}
	}
}

// SlashHostRoot has route "//root".
func (_c Client) SlashHostRoot(ctx context.Context) (err error) { // MARKER: SlashHostRoot
	_in := SlashHostRootIn{}
	_out := SlashHostRootOut{}
	err = marshalRequest(ctx, _c.svc, _c.opts, _c.host, SlashHostRoot.Method, SlashHostRoot.Route, &_in, &_out)
	return err // No trace
}

// SlashHostRootResponse packs the response of SlashHostRoot.
type SlashHostRootResponse multicastResponse // MARKER: SlashHostRoot

// Get unpacks the return arguments of SlashHostRoot.
func (_res *SlashHostRootResponse) Get() (err error) { // MARKER: SlashHostRoot
	return _res.err
}

// SlashHostRoot has route "//root".
func (_c MulticastClient) SlashHostRoot(ctx context.Context) iter.Seq[*SlashHostRootResponse] { // MARKER: SlashHostRoot
	_in := SlashHostRootIn{}
	_out := SlashHostRootOut{}
	_queue := marshalPublish(ctx, _c.svc, _c.opts, _c.host, SlashHostRoot.Method, SlashHostRoot.Route, &_in, &_out)
	return func(yield func(*SlashHostRootResponse) bool) {
		for _r := range _queue {
			_clone := _out
			_r.data = &_clone
			if !yield((*SlashHostRootResponse)(_r)) {
				return
			}
		}
	}
}

// SlashHostPort has route "//alt.host:0/alt-path".
func (_c Client) SlashHostPort(ctx context.Context) (err error) { // MARKER: SlashHostPort
	_in := SlashHostPortIn{}
	_out := SlashHostPortOut{}
	err = marshalRequest(ctx, _c.svc, _c.opts, _c.host, SlashHostPort.Method, SlashHostPort.Route, &_in, &_out)
	return err // No trace
}

// SlashHostPortResponse packs the response of SlashHostPort.
type SlashHostPortResponse multicastResponse // MARKER: SlashHostPort

// Get unpacks the return arguments of SlashHostPort.
func (_res *SlashHostPortResponse) Get() (err error) { // MARKER: SlashHostPort
	return _res.err
}

// SlashHostPort has route "//alt.host:0/alt-path".
func (_c MulticastClient) SlashHostPort(ctx context.Context) iter.Seq[*SlashHostPortResponse] { // MARKER: SlashHostPort
	_in := SlashHostPortIn{}
	_out := SlashHostPortOut{}
	_queue := marshalPublish(ctx, _c.svc, _c.opts, _c.host, SlashHostPort.Method, SlashHostPort.Route, &_in, &_out)
	return func(yield func(*SlashHostPortResponse) bool) {
		for _r := range _queue {
			_clone := _out
			_r.data = &_clone
			if !yield((*SlashHostPortResponse)(_r)) {
				return
			}
		}
	}
}

// SlashHostPathArg has route "//alt.host/items/{id}".
func (_c Client) SlashHostPathArg(ctx context.Context, id string) (err error) { // MARKER: SlashHostPathArg
	_in := SlashHostPathArgIn{ID: id}
	_out := SlashHostPathArgOut{}
	err = marshalRequest(ctx, _c.svc, _c.opts, _c.host, SlashHostPathArg.Method, SlashHostPathArg.Route, &_in, &_out)
	return err // No trace
}

// SlashHostPathArgResponse packs the response of SlashHostPathArg.
type SlashHostPathArgResponse multicastResponse // MARKER: SlashHostPathArg

// Get unpacks the return arguments of SlashHostPathArg.
func (_res *SlashHostPathArgResponse) Get() (err error) { // MARKER: SlashHostPathArg
	return _res.err
}

// SlashHostPathArg has route "//alt.host/items/{id}".
func (_c MulticastClient) SlashHostPathArg(ctx context.Context, id string) iter.Seq[*SlashHostPathArgResponse] { // MARKER: SlashHostPathArg
	_in := SlashHostPathArgIn{ID: id}
	_out := SlashHostPathArgOut{}
	_queue := marshalPublish(ctx, _c.svc, _c.opts, _c.host, SlashHostPathArg.Method, SlashHostPathArg.Route, &_in, &_out)
	return func(yield func(*SlashHostPathArgResponse) bool) {
		for _r := range _queue {
			_clone := _out
			_r.data = &_clone
			if !yield((*SlashHostPathArgResponse)(_r)) {
				return
			}
		}
	}
}

// SpecialHostRoute has route "//my$.xml/lookup" - URL-special character in the hostname segment.
func (_c Client) SpecialHostRoute(ctx context.Context) (err error) { // MARKER: SpecialHostRoute
	_in := SpecialHostRouteIn{}
	_out := SpecialHostRouteOut{}
	err = marshalRequest(ctx, _c.svc, _c.opts, _c.host, SpecialHostRoute.Method, SpecialHostRoute.Route, &_in, &_out)
	return err // No trace
}

// SpecialHostRouteResponse packs the response of SpecialHostRoute.
type SpecialHostRouteResponse multicastResponse // MARKER: SpecialHostRoute

// Get unpacks the return arguments of SpecialHostRoute.
func (_res *SpecialHostRouteResponse) Get() (err error) { // MARKER: SpecialHostRoute
	return _res.err
}

// SpecialHostRoute has route "//my$.xml/lookup" - URL-special character in the hostname segment.
func (_c MulticastClient) SpecialHostRoute(ctx context.Context) iter.Seq[*SpecialHostRouteResponse] { // MARKER: SpecialHostRoute
	_in := SpecialHostRouteIn{}
	_out := SpecialHostRouteOut{}
	_queue := marshalPublish(ctx, _c.svc, _c.opts, _c.host, SpecialHostRoute.Method, SpecialHostRoute.Route, &_in, &_out)
	return func(yield func(*SpecialHostRouteResponse) bool) {
		for _r := range _queue {
			_clone := _out
			_r.data = &_clone
			if !yield((*SpecialHostRouteResponse)(_r)) {
				return
			}
		}
	}
}

// UpperCasePath has route ":443/UPPERCASE.xml" - uppercase path segment with a period.
func (_c Client) UpperCasePath(ctx context.Context) (err error) { // MARKER: UpperCasePath
	_in := UpperCasePathIn{}
	_out := UpperCasePathOut{}
	err = marshalRequest(ctx, _c.svc, _c.opts, _c.host, UpperCasePath.Method, UpperCasePath.Route, &_in, &_out)
	return err // No trace
}

// UpperCasePathResponse packs the response of UpperCasePath.
type UpperCasePathResponse multicastResponse // MARKER: UpperCasePath

// Get unpacks the return arguments of UpperCasePath.
func (_res *UpperCasePathResponse) Get() (err error) { // MARKER: UpperCasePath
	return _res.err
}

// UpperCasePath has route ":443/UPPERCASE.xml" - uppercase path segment with a period.
func (_c MulticastClient) UpperCasePath(ctx context.Context) iter.Seq[*UpperCasePathResponse] { // MARKER: UpperCasePath
	_in := UpperCasePathIn{}
	_out := UpperCasePathOut{}
	_queue := marshalPublish(ctx, _c.svc, _c.opts, _c.host, UpperCasePath.Method, UpperCasePath.Route, &_in, &_out)
	return func(yield func(*UpperCasePathResponse) bool) {
		for _r := range _queue {
			_clone := _out
			_r.data = &_clone
			if !yield((*UpperCasePathResponse)(_r)) {
				return
			}
		}
	}
}

// OnSomethingResponse packs the response of OnSomething.
type OnSomethingResponse multicastResponse // MARKER: OnSomething

// Get unpacks the return arguments of OnSomething.
func (_res *OnSomethingResponse) Get() (ok bool, err error) { // MARKER: OnSomething
	_d := _res.data.(*OnSomethingOut)
	return _d.OK, _res.err
}

// OnSomething is fired when something happens.
func (_c MulticastTrigger) OnSomething(ctx context.Context, detail string) iter.Seq[*OnSomethingResponse] { // MARKER: OnSomething
	_in := OnSomethingIn{Detail: detail}
	_out := OnSomethingOut{}
	_inner := marshalPublish(ctx, _c.svc, _c.opts, _c.host, OnSomething.Method, OnSomething.Route, &_in, &_out)
	return func(yield func(*OnSomethingResponse) bool) {
		for _r := range _inner {
			_clone := _out
			_r.data = &_clone
			if !yield((*OnSomethingResponse)(_r)) {
				return
			}
		}
	}
}

// OnSomething is fired when something happens.
func (c Hook) OnSomething(handler func(ctx context.Context, detail string) (ok bool, err error)) (unsub func() error, err error) { // MARKER: OnSomething
	doOnSomething := func(w http.ResponseWriter, r *http.Request) error {
		var in OnSomethingIn
		var out OnSomethingOut
		err = marshalFunction(w, r, OnSomething.Route, &in, &out, func(_ any, _ any) error {
			out.OK, err = handler(r.Context(), in.Detail)
			return err
		})
		return err // No trace
	}
	const name = "OnSomething"
	path := httpx.JoinHostAndPath(c.host, OnSomething.Route)
	subOpts := append([]sub.Option{
		sub.At(OnSomething.Method, path),
		sub.InboundEvent(OnSomethingIn{}, OnSomethingOut{}),
	}, c.opts...)
	if err := c.svc.Subscribe(name, doOnSomething, subOpts...); err != nil {
		return nil, errors.Trace(err)
	}
	return func() error { return c.svc.Unsubscribe(name) }, nil
}
