/*
Copyright (c) 2023-2026 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cmd/genmock. DO NOT EDIT.

package subgraphentryflow

import (
	"context"
	"testing"

	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/workflow"
	"github.com/microbus-io/testarossa"
)

func TestSubgraphentryflow_Mock(t *testing.T) {
	t.Parallel()
	ctx := t.Context()

	mock := NewMock()
	mock.SetDeployment(connector.TESTING)

	t.Run("on_startup", func(t *testing.T) {
		assert := testarossa.For(t)
		err := mock.OnStartup(ctx)
		assert.NoError(err)
	})

	t.Run("on_shutdown", func(t *testing.T) {
		assert := testarossa.For(t)
		err := mock.OnShutdown(ctx)
		assert.NoError(err)
	})

	t.Run("task_inner", func(t *testing.T) { // MARKER: TaskInner
		assert := testarossa.For(t)

		mock.MockTaskInner(func(ctx context.Context, flow *workflow.Flow) (innerResult string, err error) {
			return
		})
		_, err := mock.TaskInner(ctx, nil)
		assert.NoError(err)
	})

	t.Run("task_tail", func(t *testing.T) { // MARKER: TaskTail
		assert := testarossa.For(t)

		mock.MockTaskTail(func(ctx context.Context, flow *workflow.Flow, innerResult string) (finalResult string, err error) {
			return
		})
		var innerResult string
		_, err := mock.TaskTail(ctx, nil, innerResult)
		assert.NoError(err)
	})

	t.Run("run_inner", func(t *testing.T) { // MARKER: RunInner
		assert := testarossa.For(t)

		mock.MockRunInner(func(ctx context.Context, flow *workflow.Flow) (innerResult string, err error) {
			return
		})
		_, err := mock.RunInner(ctx, nil)
		assert.NoError(err)
	})

	t.Run("run_tail", func(t *testing.T) { // MARKER: RunTail
		assert := testarossa.For(t)

		mock.MockRunTail(func(ctx context.Context, flow *workflow.Flow, innerResult string) (finalResult string, err error) {
			return
		})
		var innerResult string
		_, err := mock.RunTail(ctx, nil, innerResult)
		assert.NoError(err)
	})

	t.Run("inner", func(t *testing.T) { // MARKER: Inner
		assert := testarossa.For(t)

		mock.MockInner(func(ctx context.Context, flow *workflow.Flow) (innerResult string, err error) {
			return
		})
		graph, err := mock.Inner(ctx)
		if assert.NoError(err) {
			assert.NotNil(graph)
		}
	})

	t.Run("tail", func(t *testing.T) { // MARKER: Tail
		assert := testarossa.For(t)

		mock.MockTail(func(ctx context.Context, flow *workflow.Flow, innerResult string) (finalResult string, err error) {
			return
		})
		graph, err := mock.Tail(ctx)
		if assert.NoError(err) {
			assert.NotNil(graph)
		}
	})

	t.Run("outer", func(t *testing.T) { // MARKER: Outer
		assert := testarossa.For(t)

		mock.MockOuter(func(ctx context.Context, flow *workflow.Flow) (finalResult string, err error) {
			return
		})
		graph, err := mock.Outer(ctx)
		if assert.NoError(err) {
			assert.NotNil(graph)
		}
	})

}
