/*
Copyright (c) 2023-2026 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cmd/genmock. DO NOT EDIT.

package reducerflow

import (
	"context"
	"testing"

	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/workflow"
	"github.com/microbus-io/testarossa"
)

func TestReducerflow_Mock(t *testing.T) {
	t.Parallel()
	ctx := t.Context()

	mock := NewMock()
	mock.SetDeployment(connector.TESTING)

	t.Run("on_startup", func(t *testing.T) {
		assert := testarossa.For(t)
		err := mock.OnStartup(ctx)
		assert.NoError(err)
	})

	t.Run("on_shutdown", func(t *testing.T) {
		assert := testarossa.For(t)
		err := mock.OnShutdown(ctx)
		assert.NoError(err)
	})

	t.Run("task_a", func(t *testing.T) { // MARKER: TaskA
		assert := testarossa.For(t)

		mock.MockTaskA(func(ctx context.Context, flow *workflow.Flow) (started bool, err error) {
			return
		})
		_, err := mock.TaskA(ctx, nil)
		assert.NoError(err)
	})

	t.Run("task_b", func(t *testing.T) { // MARKER: TaskB
		assert := testarossa.For(t)

		mock.MockTaskB(func(ctx context.Context, flow *workflow.Flow) (sumTotalOut int, listTagsOut []string, setSeenOut []string, err error) {
			return
		})
		_, _, _, err := mock.TaskB(ctx, nil)
		assert.NoError(err)
	})

	t.Run("task_c", func(t *testing.T) { // MARKER: TaskC
		assert := testarossa.For(t)

		mock.MockTaskC(func(ctx context.Context, flow *workflow.Flow) (sumTotalOut int, listTagsOut []string, setSeenOut []string, err error) {
			return
		})
		_, _, _, err := mock.TaskC(ctx, nil)
		assert.NoError(err)
	})

	t.Run("task_d", func(t *testing.T) { // MARKER: TaskD
		assert := testarossa.For(t)

		mock.MockTaskD(func(ctx context.Context, flow *workflow.Flow) (sumTotalOut int, listTagsOut []string, setSeenOut []string, err error) {
			return
		})
		_, _, _, err := mock.TaskD(ctx, nil)
		assert.NoError(err)
	})

	t.Run("task_e", func(t *testing.T) { // MARKER: TaskE
		assert := testarossa.For(t)

		mock.MockTaskE(func(ctx context.Context, flow *workflow.Flow, sumTotal int, listTags []string, setSeen []string) (finalSum int, finalList []string, finalSet []string, err error) {
			return
		})
		var sumTotal int
		var listTags []string
		var setSeen []string
		_, _, _, err := mock.TaskE(ctx, nil, sumTotal, listTags, setSeen)
		assert.NoError(err)
	})

	t.Run("reducer", func(t *testing.T) { // MARKER: Reducer
		assert := testarossa.For(t)

		mock.MockReducer(func(ctx context.Context, flow *workflow.Flow) (finalSum int, finalList []string, finalSet []string, err error) {
			return
		})
		graph, err := mock.Reducer(ctx)
		if assert.NoError(err) {
			assert.NotNil(graph)
		}
	})

}
