// Code generated by cmd/genservice. DO NOT EDIT.

package kitchenapi

import (
	"context"
	"iter"
	"net/http"
	"reflect"

	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/fabric/pub"
	"github.com/microbus-io/fabric/service"
	"github.com/microbus-io/fabric/sub"
)

// multicastResponse packs the response of a functional multicast.
type multicastResponse struct {
	data         any
	HTTPResponse *http.Response
	err          error
}

// Client is a lightweight proxy for making unicast calls to the microservice.
type Client struct {
	svc  service.Publisher
	host string
	opts []pub.Option
}

// NewClient creates a new unicast client proxy to the microservice.
func NewClient(caller service.Publisher) Client {
	return Client{svc: caller, host: Hostname}
}

// ForHost returns a copy of the client with a different hostname to be applied to requests.
func (_c Client) ForHost(host string) Client {
	return Client{svc: _c.svc, host: host, opts: _c.opts}
}

// WithOptions returns a copy of the client with options to be applied to requests.
func (_c Client) WithOptions(opts ...pub.Option) Client {
	return Client{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...)}
}

// MulticastClient is a lightweight proxy for making multicast calls to the microservice.
type MulticastClient struct {
	svc  service.Publisher
	host string
	opts []pub.Option
}

// NewMulticastClient creates a new multicast client proxy to the microservice.
func NewMulticastClient(caller service.Publisher) MulticastClient {
	return MulticastClient{svc: caller, host: Hostname}
}

// ForHost returns a copy of the client with a different hostname to be applied to requests.
func (_c MulticastClient) ForHost(host string) MulticastClient {
	return MulticastClient{svc: _c.svc, host: host, opts: _c.opts}
}

// WithOptions returns a copy of the client with options to be applied to requests.
func (_c MulticastClient) WithOptions(opts ...pub.Option) MulticastClient {
	return MulticastClient{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...)}
}

// MulticastTrigger is a lightweight proxy for triggering the events of the microservice.
type MulticastTrigger struct {
	svc  service.Publisher
	host string
	opts []pub.Option
}

// NewMulticastTrigger creates a new multicast trigger of events of the microservice.
func NewMulticastTrigger(caller service.Publisher) MulticastTrigger {
	return MulticastTrigger{svc: caller, host: Hostname}
}

// ForHost returns a copy of the trigger with a different hostname to be applied to requests.
func (_c MulticastTrigger) ForHost(host string) MulticastTrigger {
	return MulticastTrigger{svc: _c.svc, host: host, opts: _c.opts}
}

// WithOptions returns a copy of the trigger with options to be applied to requests.
func (_c MulticastTrigger) WithOptions(opts ...pub.Option) MulticastTrigger {
	return MulticastTrigger{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...)}
}

// Hook assists in the subscription to the events of the microservice.
type Hook struct {
	svc  service.Subscriber
	host string
	opts []sub.Option
}

// NewHook creates a new hook to the events of the microservice.
func NewHook(listener service.Subscriber) Hook {
	return Hook{svc: listener, host: Hostname}
}

// ForHost returns a copy of the hook with a different hostname to be applied to the subscription.
func (c Hook) ForHost(host string) Hook {
	return Hook{svc: c.svc, host: host, opts: c.opts}
}

// WithOptions returns a copy of the hook with options to be applied to subscriptions.
func (c Hook) WithOptions(opts ...sub.Option) Hook {
	return Hook{svc: c.svc, host: c.host, opts: append(c.opts, opts...)}
}

// marshalRequest supports functional endpoints.
func marshalRequest(ctx context.Context, svc service.Publisher, opts []pub.Option, host string, method string, route string, in any, out any) (err error) {
	if method == "ANY" {
		method = "POST"
	}
	u := httpx.JoinHostAndPath(host, route)
	query, body, err := httpx.WriteInputPayload(method, in)
	if err != nil {
		return err // No trace
	}
	httpRes, err := svc.Request(
		ctx,
		pub.Method(method),
		pub.URL(u),
		pub.Query(query),
		pub.Body(body),
		pub.Options(opts...),
	)
	if err != nil {
		return err // No trace
	}
	err = httpx.ReadOutputPayload(httpRes, out)
	return errors.Trace(err)
}

// marshalPublish supports multicast functional endpoints.
func marshalPublish(ctx context.Context, svc service.Publisher, opts []pub.Option, host string, method string, route string, in any, out any) iter.Seq[*multicastResponse] {
	if method == "ANY" {
		method = "POST"
	}
	u := httpx.JoinHostAndPath(host, route)
	query, body, err := httpx.WriteInputPayload(method, in)
	if err != nil {
		return func(yield func(*multicastResponse) bool) {
			yield(&multicastResponse{err: err})
		}
	}
	_queue := svc.Publish(
		ctx,
		pub.Method(method),
		pub.URL(u),
		pub.Query(query),
		pub.Body(body),
		pub.Options(opts...),
	)
	return func(yield func(*multicastResponse) bool) {
		for qi := range _queue {
			httpResp, err := qi.Get()
			if err == nil {
				reflect.ValueOf(out).Elem().SetZero()
				err = httpx.ReadOutputPayload(httpResp, out)
			}
			if err != nil {
				if !yield(&multicastResponse{err: err, HTTPResponse: httpResp}) {
					return
				}
			} else {
				if !yield(&multicastResponse{data: out, HTTPResponse: httpResp}) {
					return
				}
			}
		}
	}
}

// marshalFunction handles marshaling for functional endpoints.
func marshalFunction(w http.ResponseWriter, r *http.Request, route string, in any, out any, execute func(in any, out any) error) error {
	err := httpx.ReadInputPayload(r, route, in)
	if err != nil {
		return errors.Trace(err)
	}
	err = execute(in, out)
	if err != nil {
		return err // No trace
	}
	err = httpx.WriteOutputPayload(w, out)
	if err != nil {
		return errors.Trace(err)
	}
	return nil
}

// MyFunc handles the MyFunc endpoint and exercises every call pattern.
func (_c Client) MyFunc(ctx context.Context, input string) (output string, err error) { // MARKER: MyFunc
	_in := MyFuncIn{Input: input}
	_out := MyFuncOut{}
	err = marshalRequest(ctx, _c.svc, _c.opts, _c.host, MyFunc.Method, MyFunc.Route, &_in, &_out)
	return _out.Output, err // No trace
}

// MyFuncResponse packs the response of MyFunc.
type MyFuncResponse multicastResponse // MARKER: MyFunc

// Get unpacks the return arguments of MyFunc.
func (_res *MyFuncResponse) Get() (output string, err error) { // MARKER: MyFunc
	_d := _res.data.(*MyFuncOut)
	return _d.Output, _res.err
}

// MyFunc handles the MyFunc endpoint and exercises every call pattern.
func (_c MulticastClient) MyFunc(ctx context.Context, input string) iter.Seq[*MyFuncResponse] { // MARKER: MyFunc
	_in := MyFuncIn{Input: input}
	_out := MyFuncOut{}
	_queue := marshalPublish(ctx, _c.svc, _c.opts, _c.host, MyFunc.Method, MyFunc.Route, &_in, &_out)
	return func(yield func(*MyFuncResponse) bool) {
		for _r := range _queue {
			_clone := _out
			_r.data = &_clone
			if !yield((*MyFuncResponse)(_r)) {
				return
			}
		}
	}
}

// SelfPing handles peer-to-peer self-pings.
func (_c Client) SelfPing(ctx context.Context) (err error) { // MARKER: SelfPing
	_in := SelfPingIn{}
	_out := SelfPingOut{}
	err = marshalRequest(ctx, _c.svc, _c.opts, _c.host, SelfPing.Method, SelfPing.Route, &_in, &_out)
	return err // No trace
}

// SelfPingResponse packs the response of SelfPing.
type SelfPingResponse multicastResponse // MARKER: SelfPing

// Get unpacks the return arguments of SelfPing.
func (_res *SelfPingResponse) Get() (err error) { // MARKER: SelfPing
	return _res.err
}

// SelfPing handles peer-to-peer self-pings.
func (_c MulticastClient) SelfPing(ctx context.Context) iter.Seq[*SelfPingResponse] { // MARKER: SelfPing
	_in := SelfPingIn{}
	_out := SelfPingOut{}
	_queue := marshalPublish(ctx, _c.svc, _c.opts, _c.host, SelfPing.Method, SelfPing.Route, &_in, &_out)
	return func(yield func(*SelfPingResponse) bool) {
		for _r := range _queue {
			_clone := _out
			_r.data = &_clone
			if !yield((*SelfPingResponse)(_r)) {
				return
			}
		}
	}
}

// AltHostFn registers on a non-own host via the //host form.
func (_c Client) AltHostFn(ctx context.Context) (err error) { // MARKER: AltHostFn
	_in := AltHostFnIn{}
	_out := AltHostFnOut{}
	err = marshalRequest(ctx, _c.svc, _c.opts, _c.host, AltHostFn.Method, AltHostFn.Route, &_in, &_out)
	return err // No trace
}

// AltHostFnResponse packs the response of AltHostFn.
type AltHostFnResponse multicastResponse // MARKER: AltHostFn

// Get unpacks the return arguments of AltHostFn.
func (_res *AltHostFnResponse) Get() (err error) { // MARKER: AltHostFn
	return _res.err
}

// AltHostFn registers on a non-own host via the //host form.
func (_c MulticastClient) AltHostFn(ctx context.Context) iter.Seq[*AltHostFnResponse] { // MARKER: AltHostFn
	_in := AltHostFnIn{}
	_out := AltHostFnOut{}
	_queue := marshalPublish(ctx, _c.svc, _c.opts, _c.host, AltHostFn.Method, AltHostFn.Route, &_in, &_out)
	return func(yield func(*AltHostFnResponse) bool) {
		for _r := range _queue {
			_clone := _out
			_r.data = &_clone
			if !yield((*AltHostFnResponse)(_r)) {
				return
			}
		}
	}
}

// OnMyEventResponse packs the response of OnMyEvent.
type OnMyEventResponse multicastResponse // MARKER: OnMyEvent

// Get unpacks the return arguments of OnMyEvent.
func (_res *OnMyEventResponse) Get() (ok bool, err error) { // MARKER: OnMyEvent
	_d := _res.data.(*OnMyEventOut)
	return _d.OK, _res.err
}

// OnMyEvent is fired when something happens.
func (_c MulticastTrigger) OnMyEvent(ctx context.Context, note string) iter.Seq[*OnMyEventResponse] { // MARKER: OnMyEvent
	_in := OnMyEventIn{Note: note}
	_out := OnMyEventOut{}
	_inner := marshalPublish(ctx, _c.svc, _c.opts, _c.host, OnMyEvent.Method, OnMyEvent.Route, &_in, &_out)
	return func(yield func(*OnMyEventResponse) bool) {
		for _r := range _inner {
			_clone := _out
			_r.data = &_clone
			if !yield((*OnMyEventResponse)(_r)) {
				return
			}
		}
	}
}

// OnMyEvent is fired when something happens.
func (c Hook) OnMyEvent(handler func(ctx context.Context, note string) (ok bool, err error)) (unsub func() error, err error) { // MARKER: OnMyEvent
	doOnMyEvent := func(w http.ResponseWriter, r *http.Request) error {
		var in OnMyEventIn
		var out OnMyEventOut
		err = marshalFunction(w, r, OnMyEvent.Route, &in, &out, func(_ any, _ any) error {
			out.OK, err = handler(r.Context(), in.Note)
			return err
		})
		return err // No trace
	}
	const name = "OnMyEvent"
	path := httpx.JoinHostAndPath(c.host, OnMyEvent.Route)
	subOpts := append([]sub.Option{
		sub.At(OnMyEvent.Method, path),
		sub.InboundEvent(OnMyEventIn{}, OnMyEventOut{}),
	}, c.opts...)
	if err := c.svc.Subscribe(name, doOnMyEvent, subOpts...); err != nil {
		return nil, errors.Trace(err)
	}
	return func() error { return c.svc.Unsubscribe(name) }, nil
}
