graph LR
    classDef task fill:#32a7c1,color:#f4f2ef,stroke:#32a7c1
    classDef term fill:#e5f4f3,color:#434343,stroke:#32a7c1
    classDef note fill:none,stroke:none,color:#32a7c1,font-size:0.8em
    linkStyle default stroke:#32a7c1

    _title{{"switch"}}:::term -.-> _start
    t0["router"]:::task
    t0_switch{"switch"}:::term
    t1["handleHigh"]:::task
    t2["handleMid"]:::task
    t3["handleLow"]:::task
    t0 --> t0_switch
    t0_switch -->|"amount >= 10000"| t1
    t0_switch -->|"amount >= 1000"| t2
    t0_switch -->|"default"| t3
    _start(( )):::term --> t0
    t1 --> _end(( )):::term
    t2 --> _end(( )):::term
    t3 --> _end(( )):::term
