/*
Copyright (c) 2023-2026 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cmd/genmock. DO NOT EDIT.

package failedfanoutflow

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/fabric/sub"
	"github.com/microbus-io/fabric/utils"
	"github.com/microbus-io/fabric/workflow"

	"github.com/microbus-io/fabric/verify/failedfanoutflow/failedfanoutflowapi"
)

// Mock is a mockable version of the microservice, allowing functions, event sinks and web handlers to be mocked.
type Mock struct {
	*Intermediate
	mockSrc               func(ctx context.Context, flow *workflow.Flow) (started bool, err error)                       // MARKER: Src
	mockA                 func(ctx context.Context, flow *workflow.Flow) (sumExecutedOut int, err error)                 // MARKER: A
	mockB                 func(ctx context.Context, flow *workflow.Flow) (sumExecutedOut int, err error)                 // MARKER: B
	mockC                 func(ctx context.Context, flow *workflow.Flow) (sumExecutedOut int, err error)                 // MARKER: C
	mockJ                 func(ctx context.Context, flow *workflow.Flow, sumExecuted int) (totalExecuted int, err error) // MARKER: J
	mockFailedFanOutGraph func(ctx context.Context) (graph *workflow.Graph, err error)                                   // MARKER: FailedFanOut
	unsubMockFailedFanOut func() error                                                                                   // MARKER: FailedFanOut
}

// NewMock creates a new mockable version of the microservice.
func NewMock() *Mock {
	svc := &Mock{}
	svc.Intermediate = NewIntermediate(svc)
	svc.SetVersion(7357) // Stands for TEST
	return svc
}

// OnStartup is called when the microservice is started up.
func (svc *Mock) OnStartup(ctx context.Context) (err error) {
	if svc.Deployment() != connector.LOCAL && svc.Deployment() != connector.TESTING {
		return errors.New("mocking disallowed in %s deployment", svc.Deployment())
	}
	return nil
}

// OnShutdown is called when the microservice is shut down.
func (svc *Mock) OnShutdown(ctx context.Context) (err error) {
	return nil
}

// MockSrc sets up a mock handler for Src.
func (svc *Mock) MockSrc(handler func(ctx context.Context, flow *workflow.Flow) (started bool, err error)) *Mock { // MARKER: Src
	svc.mockSrc = handler
	return svc
}

// Src executes the mock handler.
func (svc *Mock) Src(ctx context.Context, flow *workflow.Flow) (started bool, err error) { // MARKER: Src
	if svc.mockSrc != nil {
		started, err = svc.mockSrc(ctx, flow)
	}
	return started, errors.Trace(err)
}

// MockA sets up a mock handler for A.
func (svc *Mock) MockA(handler func(ctx context.Context, flow *workflow.Flow) (sumExecutedOut int, err error)) *Mock { // MARKER: A
	svc.mockA = handler
	return svc
}

// A executes the mock handler.
func (svc *Mock) A(ctx context.Context, flow *workflow.Flow) (sumExecutedOut int, err error) { // MARKER: A
	if svc.mockA != nil {
		sumExecutedOut, err = svc.mockA(ctx, flow)
	}
	return sumExecutedOut, errors.Trace(err)
}

// MockB sets up a mock handler for B.
func (svc *Mock) MockB(handler func(ctx context.Context, flow *workflow.Flow) (sumExecutedOut int, err error)) *Mock { // MARKER: B
	svc.mockB = handler
	return svc
}

// B executes the mock handler.
func (svc *Mock) B(ctx context.Context, flow *workflow.Flow) (sumExecutedOut int, err error) { // MARKER: B
	if svc.mockB != nil {
		sumExecutedOut, err = svc.mockB(ctx, flow)
	}
	return sumExecutedOut, errors.Trace(err)
}

// MockC sets up a mock handler for C.
func (svc *Mock) MockC(handler func(ctx context.Context, flow *workflow.Flow) (sumExecutedOut int, err error)) *Mock { // MARKER: C
	svc.mockC = handler
	return svc
}

// C executes the mock handler.
func (svc *Mock) C(ctx context.Context, flow *workflow.Flow) (sumExecutedOut int, err error) { // MARKER: C
	if svc.mockC != nil {
		sumExecutedOut, err = svc.mockC(ctx, flow)
	}
	return sumExecutedOut, errors.Trace(err)
}

// MockJ sets up a mock handler for J.
func (svc *Mock) MockJ(handler func(ctx context.Context, flow *workflow.Flow, sumExecuted int) (totalExecuted int, err error)) *Mock { // MARKER: J
	svc.mockJ = handler
	return svc
}

// J executes the mock handler.
func (svc *Mock) J(ctx context.Context, flow *workflow.Flow, sumExecuted int) (totalExecuted int, err error) { // MARKER: J
	if svc.mockJ != nil {
		totalExecuted, err = svc.mockJ(ctx, flow, sumExecuted)
	}
	return totalExecuted, errors.Trace(err)
}

// MockFailedFanOut sets up a mock handler for the FailedFanOut workflow.
// The handler receives typed inputs from the workflow's state and returns typed outputs.
// A nil handler clears the mock.
func (svc *Mock) MockFailedFanOut(handler func(ctx context.Context, flow *workflow.Flow) (sumExecuted int, totalExecuted int, err error)) *Mock { // MARKER: FailedFanOut
	if svc.unsubMockFailedFanOut != nil {
		svc.unsubMockFailedFanOut()
		svc.unsubMockFailedFanOut = nil
	}
	if handler == nil {
		svc.mockFailedFanOutGraph = nil
		return svc
	}
	mockName := "MockFailedFanOut" + utils.RandomIdentifier(8)
	mockRoute := ":428/mock-failed-fan-out-" + utils.RandomIdentifier(8)
	mockTaskURL := httpx.JoinHostAndPath(svc.Hostname(), mockRoute)
	svc.mockFailedFanOutGraph = func(ctx context.Context) (graph *workflow.Graph, err error) {
		g := workflow.NewGraph(failedfanoutflowapi.FailedFanOut.URL())
		g.AddTransition(mockTaskURL, workflow.END)
		return g, nil
	}
	err := svc.Subscribe(mockName, func(w http.ResponseWriter, r *http.Request) error {
		var f workflow.Flow
		if err := json.NewDecoder(r.Body).Decode(&f); err != nil {
			return errors.Trace(err)
		}
		snap := f.Snapshot()
		var in failedfanoutflowapi.FailedFanOutIn
		f.ParseState(&in)
		sumExecuted, totalExecuted, err := handler(r.Context(), &f)
		if err != nil {
			return err // No trace
		}
		out := failedfanoutflowapi.FailedFanOutOut{SumExecuted: sumExecuted, TotalExecuted: totalExecuted}
		f.SetChanges(out, snap)
		w.Header().Set("Content-Type", "application/json")
		return json.NewEncoder(w).Encode(&f)
	},
		sub.At("POST", mockRoute),
		sub.Task(failedfanoutflowapi.FailedFanOutIn{}, failedfanoutflowapi.FailedFanOutOut{}),
	)
	if err == nil {
		svc.unsubMockFailedFanOut = func() error { return svc.Unsubscribe(mockName) }
	}
	return svc
}

// FailedFanOut returns the workflow graph, or a mocked graph if MockFailedFanOut was called.
func (svc *Mock) FailedFanOut(ctx context.Context) (graph *workflow.Graph, err error) { // MARKER: FailedFanOut
	if svc.mockFailedFanOutGraph != nil {
		graph, err = svc.mockFailedFanOutGraph(ctx)
	}
	return graph, errors.Trace(err)
}
