// Code generated by cmd/genmock. DO NOT EDIT.

package superflow

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/fabric/sub"
	"github.com/microbus-io/fabric/utils"
	"github.com/microbus-io/fabric/workflow"

	"github.com/microbus-io/fabric/verify/superflow/superflowapi"
)

// Mock is a mockable version of the microservice, allowing functions, event sinks and web handlers to be mocked.
type Mock struct {
	*Intermediate
	mockTaskA         func(ctx context.Context, flow *workflow.Flow) (err error)   // MARKER: TaskA
	mockTaskB         func(ctx context.Context, flow *workflow.Flow) (err error)   // MARKER: TaskB
	mockTaskC         func(ctx context.Context, flow *workflow.Flow) (err error)   // MARKER: TaskC
	mockTaskD         func(ctx context.Context, flow *workflow.Flow) (err error)   // MARKER: TaskD
	mockTaskE         func(ctx context.Context, flow *workflow.Flow) (err error)   // MARKER: TaskE
	mockTaskZ         func(ctx context.Context, flow *workflow.Flow) (err error)   // MARKER: TaskZ
	mockErrorHandler  func(ctx context.Context, flow *workflow.Flow) (err error)   // MARKER: ErrorHandler
	mockSubTaskA      func(ctx context.Context, flow *workflow.Flow) (err error)   // MARKER: SubTaskA
	mockSubTaskB      func(ctx context.Context, flow *workflow.Flow) (err error)   // MARKER: SubTaskB
	mockSuperGraph    func(ctx context.Context) (graph *workflow.Graph, err error) // MARKER: Super
	unsubMockSuper    func() error                                                 // MARKER: Super
	mockSuperSubGraph func(ctx context.Context) (graph *workflow.Graph, err error) // MARKER: SuperSub
	unsubMockSuperSub func() error                                                 // MARKER: SuperSub
}

// NewMock creates a new mockable version of the microservice.
func NewMock() *Mock {
	svc := &Mock{}
	svc.Intermediate = NewIntermediate(svc)
	svc.SetVersion(7357) // Stands for TEST
	return svc
}

// OnStartup is called when the microservice is started up.
func (svc *Mock) OnStartup(ctx context.Context) (err error) {
	if svc.Deployment() != connector.LOCAL && svc.Deployment() != connector.TESTING {
		return errors.New("mocking disallowed in %s deployment", svc.Deployment())
	}
	return nil
}

// OnShutdown is called when the microservice is shut down.
func (svc *Mock) OnShutdown(ctx context.Context) (err error) {
	return nil
}

// MockTaskA sets up a mock handler for TaskA.
func (svc *Mock) MockTaskA(handler func(ctx context.Context, flow *workflow.Flow) (err error)) *Mock { // MARKER: TaskA
	svc.mockTaskA = handler
	return svc
}

// TaskA executes the mock handler.
func (svc *Mock) TaskA(ctx context.Context, flow *workflow.Flow) (err error) { // MARKER: TaskA
	if svc.mockTaskA != nil {
		err = svc.mockTaskA(ctx, flow)
	}
	return errors.Trace(err)
}

// MockTaskB sets up a mock handler for TaskB.
func (svc *Mock) MockTaskB(handler func(ctx context.Context, flow *workflow.Flow) (err error)) *Mock { // MARKER: TaskB
	svc.mockTaskB = handler
	return svc
}

// TaskB executes the mock handler.
func (svc *Mock) TaskB(ctx context.Context, flow *workflow.Flow) (err error) { // MARKER: TaskB
	if svc.mockTaskB != nil {
		err = svc.mockTaskB(ctx, flow)
	}
	return errors.Trace(err)
}

// MockTaskC sets up a mock handler for TaskC.
func (svc *Mock) MockTaskC(handler func(ctx context.Context, flow *workflow.Flow) (err error)) *Mock { // MARKER: TaskC
	svc.mockTaskC = handler
	return svc
}

// TaskC executes the mock handler.
func (svc *Mock) TaskC(ctx context.Context, flow *workflow.Flow) (err error) { // MARKER: TaskC
	if svc.mockTaskC != nil {
		err = svc.mockTaskC(ctx, flow)
	}
	return errors.Trace(err)
}

// MockTaskD sets up a mock handler for TaskD.
func (svc *Mock) MockTaskD(handler func(ctx context.Context, flow *workflow.Flow) (err error)) *Mock { // MARKER: TaskD
	svc.mockTaskD = handler
	return svc
}

// TaskD executes the mock handler.
func (svc *Mock) TaskD(ctx context.Context, flow *workflow.Flow) (err error) { // MARKER: TaskD
	if svc.mockTaskD != nil {
		err = svc.mockTaskD(ctx, flow)
	}
	return errors.Trace(err)
}

// MockTaskE sets up a mock handler for TaskE.
func (svc *Mock) MockTaskE(handler func(ctx context.Context, flow *workflow.Flow) (err error)) *Mock { // MARKER: TaskE
	svc.mockTaskE = handler
	return svc
}

// TaskE executes the mock handler.
func (svc *Mock) TaskE(ctx context.Context, flow *workflow.Flow) (err error) { // MARKER: TaskE
	if svc.mockTaskE != nil {
		err = svc.mockTaskE(ctx, flow)
	}
	return errors.Trace(err)
}

// MockTaskZ sets up a mock handler for TaskZ.
func (svc *Mock) MockTaskZ(handler func(ctx context.Context, flow *workflow.Flow) (err error)) *Mock { // MARKER: TaskZ
	svc.mockTaskZ = handler
	return svc
}

// TaskZ executes the mock handler.
func (svc *Mock) TaskZ(ctx context.Context, flow *workflow.Flow) (err error) { // MARKER: TaskZ
	if svc.mockTaskZ != nil {
		err = svc.mockTaskZ(ctx, flow)
	}
	return errors.Trace(err)
}

// MockErrorHandler sets up a mock handler for ErrorHandler.
func (svc *Mock) MockErrorHandler(handler func(ctx context.Context, flow *workflow.Flow) (err error)) *Mock { // MARKER: ErrorHandler
	svc.mockErrorHandler = handler
	return svc
}

// ErrorHandler executes the mock handler.
func (svc *Mock) ErrorHandler(ctx context.Context, flow *workflow.Flow) (err error) { // MARKER: ErrorHandler
	if svc.mockErrorHandler != nil {
		err = svc.mockErrorHandler(ctx, flow)
	}
	return errors.Trace(err)
}

// MockSubTaskA sets up a mock handler for SubTaskA.
func (svc *Mock) MockSubTaskA(handler func(ctx context.Context, flow *workflow.Flow) (err error)) *Mock { // MARKER: SubTaskA
	svc.mockSubTaskA = handler
	return svc
}

// SubTaskA executes the mock handler.
func (svc *Mock) SubTaskA(ctx context.Context, flow *workflow.Flow) (err error) { // MARKER: SubTaskA
	if svc.mockSubTaskA != nil {
		err = svc.mockSubTaskA(ctx, flow)
	}
	return errors.Trace(err)
}

// MockSubTaskB sets up a mock handler for SubTaskB.
func (svc *Mock) MockSubTaskB(handler func(ctx context.Context, flow *workflow.Flow) (err error)) *Mock { // MARKER: SubTaskB
	svc.mockSubTaskB = handler
	return svc
}

// SubTaskB executes the mock handler.
func (svc *Mock) SubTaskB(ctx context.Context, flow *workflow.Flow) (err error) { // MARKER: SubTaskB
	if svc.mockSubTaskB != nil {
		err = svc.mockSubTaskB(ctx, flow)
	}
	return errors.Trace(err)
}

// MockSuper sets up a mock handler for the Super workflow.
// The handler receives typed inputs from the workflow's state and returns typed outputs.
// A nil handler clears the mock.
func (svc *Mock) MockSuper(handler func(ctx context.Context, flow *workflow.Flow, items []string, useSubgraph bool, behaviors map[string]superflowapi.TaskBehavior) (err error)) *Mock { // MARKER: Super
	if svc.unsubMockSuper != nil {
		svc.unsubMockSuper()
		svc.unsubMockSuper = nil
	}
	if handler == nil {
		svc.mockSuperGraph = nil
		return svc
	}
	mockName := "MockSuper" + utils.RandomIdentifier(8)
	mockRoute := ":428/mock-super-" + utils.RandomIdentifier(8)
	mockTaskURL := httpx.JoinHostAndPath(svc.Hostname(), mockRoute)
	svc.mockSuperGraph = func(ctx context.Context) (graph *workflow.Graph, err error) {
		g := workflow.NewGraph(superflowapi.Super.URL())
		g.AddTransition(mockTaskURL, workflow.END)
		g.DeclareInputs("*")
		g.DeclareOutputs("*")
		return g, nil
	}
	err := svc.Subscribe(mockName, func(w http.ResponseWriter, r *http.Request) error {
		var f workflow.Flow
		if err := json.NewDecoder(r.Body).Decode(&f); err != nil {
			return errors.Trace(err)
		}
		snap := f.Snapshot()
		var in superflowapi.SuperIn
		f.ParseState(&in)
		err := handler(r.Context(), &f, in.Items, in.UseSubgraph, in.Behaviors)
		if err != nil {
			return err // No trace
		}
		out := superflowapi.SuperOut{}
		f.SetChanges(out, snap)
		w.Header().Set("Content-Type", "application/json")
		return json.NewEncoder(w).Encode(&f)
	},
		sub.At("POST", mockRoute),
		sub.Task(superflowapi.SuperIn{}, superflowapi.SuperOut{}),
	)
	if err == nil {
		svc.unsubMockSuper = func() error { return svc.Unsubscribe(mockName) }
	}
	return svc
}

// Super returns the workflow graph, or a mocked graph if MockSuper was called.
func (svc *Mock) Super(ctx context.Context) (graph *workflow.Graph, err error) { // MARKER: Super
	if svc.mockSuperGraph != nil {
		graph, err = svc.mockSuperGraph(ctx)
	}
	return graph, errors.Trace(err)
}

// MockSuperSub sets up a mock handler for the SuperSub workflow.
// The handler receives typed inputs from the workflow's state and returns typed outputs.
// A nil handler clears the mock.
func (svc *Mock) MockSuperSub(handler func(ctx context.Context, flow *workflow.Flow, behaviors map[string]superflowapi.TaskBehavior) (err error)) *Mock { // MARKER: SuperSub
	if svc.unsubMockSuperSub != nil {
		svc.unsubMockSuperSub()
		svc.unsubMockSuperSub = nil
	}
	if handler == nil {
		svc.mockSuperSubGraph = nil
		return svc
	}
	mockName := "MockSuperSub" + utils.RandomIdentifier(8)
	mockRoute := ":428/mock-super-sub-" + utils.RandomIdentifier(8)
	mockTaskURL := httpx.JoinHostAndPath(svc.Hostname(), mockRoute)
	svc.mockSuperSubGraph = func(ctx context.Context) (graph *workflow.Graph, err error) {
		g := workflow.NewGraph(superflowapi.SuperSub.URL())
		g.AddTransition(mockTaskURL, workflow.END)
		g.DeclareInputs("*")
		g.DeclareOutputs("*")
		return g, nil
	}
	err := svc.Subscribe(mockName, func(w http.ResponseWriter, r *http.Request) error {
		var f workflow.Flow
		if err := json.NewDecoder(r.Body).Decode(&f); err != nil {
			return errors.Trace(err)
		}
		snap := f.Snapshot()
		var in superflowapi.SuperSubIn
		f.ParseState(&in)
		err := handler(r.Context(), &f, in.Behaviors)
		if err != nil {
			return err // No trace
		}
		out := superflowapi.SuperSubOut{}
		f.SetChanges(out, snap)
		w.Header().Set("Content-Type", "application/json")
		return json.NewEncoder(w).Encode(&f)
	},
		sub.At("POST", mockRoute),
		sub.Task(superflowapi.SuperSubIn{}, superflowapi.SuperSubOut{}),
	)
	if err == nil {
		svc.unsubMockSuperSub = func() error { return svc.Unsubscribe(mockName) }
	}
	return svc
}

// SuperSub returns the workflow graph, or a mocked graph if MockSuperSub was called.
func (svc *Mock) SuperSub(ctx context.Context) (graph *workflow.Graph, err error) { // MARKER: SuperSub
	if svc.mockSuperSubGraph != nil {
		graph, err = svc.mockSuperSubGraph(ctx)
	}
	return graph, errors.Trace(err)
}
