graph TB
    classDef core fill:#ed2e92,color:#f4f2ef,stroke:#434343
    classDef svc fill:#32a7c1,color:#f4f2ef,stroke:#434343
    classDef ext fill:#e5f4f3,color:#434343,stroke:#434343

    configurator.core[Configurator<br>configurator.core]
    access.token.core[AccessToken<br>access.token.core]
    bearer.token.core[BearerToken<br>bearer.token.core]
    http.ingress.core[HTTP Ingress<br>http.ingress.core] ---> metrics.core[Metrics<br>metrics.core]
    http.ingress.core ---> bearer.token.core
    http.ingress.core ---> access.token.core
    openapiportal.core[OpenAPI Portal<br>openapiportal.core]
    foreman.core[Foreman<br>foreman.core] --- foreman.core.db[(SQL)]
    llm.core[LLM<br>llm.core] ---> claude.llm.core[Claude LLM<br>claude.llm.core]
    llm.core ---> openai.llm.core[OpenAI LLM<br>openai.llm.core]
    llm.core ---> gemini.llm.core[Gemini LLM<br>gemini.llm.core]
    claude.llm.core ---> http.egress.core
    openai.llm.core ---> http.egress.core
    gemini.llm.core ---> http.egress.core
    creditflow.example[CreditFlow<br>creditflow.example]
    browser.example[Browser<br>browser.example] ---> http.egress.core[HTTP Egress<br>http.egress.core]
    eventsource.example[EventSource<br>eventsource.example] -..-> eventsink.example[EventSink<br>eventsink.example]
    hello.example[Hello<br>hello.example] ---> calculator.example[Calculator<br>calculator.example]
    helloworld.example[HelloWorld<br>helloworld.example]
    login.example[Login<br>login.example] ---> bearer.token.core
    messaging.example[Messaging<br>messaging.example]
    yellowpages.example[Person<br>yellowpages.example] --- yellowpages.example.db[(SQL)]

    class hello.example,calculator.example,browser.example,login.example,eventsource.example,eventsink.example,yellowpages.example,helloworld.example,messaging.example,creditflow.example svc
    class http.ingress.core,metrics.core,bearer.token.core,access.token.core,http.egress.core,configurator.core,openapiportal.core,foreman.core,llm.core,claude.llm.core,openai.llm.core,gemini.llm.core core
    class yellowpages.example.db,foreman.core.db ext
