graph LR
    classDef task fill:#32a7c1,color:#f4f2ef,stroke:#434343
    classDef sub fill:#ed2e92,color:#f4f2ef,stroke:#434343
    classDef term fill:#e5f4f3,color:#434343,stroke:#434343

    _title{{"retry-fan-out"}}:::term --> _start
    t1@{ shape: st-rect, label: "increment" }
    t2@{ shape: trap-t, label: "join" }
    _start(( )):::term --> t0["enter"]:::task
    t0 -->|"for each in elements"| t1
    t1 -->|"fan-in"| t2
    t2 --> _end(( )):::term
    class t1 task
    class t2 task
