/*
Copyright (c) 2023-2026 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cmd/genservice. DO NOT EDIT.

package messagingapi

import (
	"context"
	"iter"
	"net/http"

	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/fabric/pub"
	"github.com/microbus-io/fabric/service"
)

// Client is a lightweight proxy for making unicast calls to the microservice.
type Client struct {
	svc  service.Publisher
	host string
	opts []pub.Option
}

// NewClient creates a new unicast client proxy to the microservice.
func NewClient(caller service.Publisher) Client {
	return Client{svc: caller, host: Hostname}
}

// ForHost returns a copy of the client with a different hostname to be applied to requests.
func (_c Client) ForHost(host string) Client {
	return Client{svc: _c.svc, host: host, opts: _c.opts}
}

// WithOptions returns a copy of the client with options to be applied to requests.
func (_c Client) WithOptions(opts ...pub.Option) Client {
	return Client{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...)}
}

// MulticastClient is a lightweight proxy for making multicast calls to the microservice.
type MulticastClient struct {
	svc  service.Publisher
	host string
	opts []pub.Option
}

// NewMulticastClient creates a new multicast client proxy to the microservice.
func NewMulticastClient(caller service.Publisher) MulticastClient {
	return MulticastClient{svc: caller, host: Hostname}
}

// ForHost returns a copy of the client with a different hostname to be applied to requests.
func (_c MulticastClient) ForHost(host string) MulticastClient {
	return MulticastClient{svc: _c.svc, host: host, opts: _c.opts}
}

// WithOptions returns a copy of the client with options to be applied to requests.
func (_c MulticastClient) WithOptions(opts ...pub.Option) MulticastClient {
	return MulticastClient{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...)}
}

// Home demonstrates making requests using multicast and unicast request/response patterns.
func (_c Client) Home(ctx context.Context, relativeURL string) (res *http.Response, err error) { // MARKER: Home
	return _c.svc.Request(
		ctx,
		pub.Method(Home.Method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Home.Route)),
		pub.RelativeURL(relativeURL),
		pub.Options(_c.opts...),
	)
}

// Home demonstrates making requests using multicast and unicast request/response patterns.
func (_c MulticastClient) Home(ctx context.Context, relativeURL string) iter.Seq[*pub.Response] { // MARKER: Home
	return _c.svc.Publish(
		ctx,
		pub.Method(Home.Method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Home.Route)),
		pub.RelativeURL(relativeURL),
		pub.Options(_c.opts...),
	)
}

// NoQueue demonstrates how the NoQueue subscription option is used to create
// a multicast request/response communication pattern.
// All instances of this microservice will respond to each request.
func (_c Client) NoQueue(ctx context.Context, relativeURL string) (res *http.Response, err error) { // MARKER: NoQueue
	return _c.svc.Request(
		ctx,
		pub.Method(NoQueue.Method),
		pub.URL(httpx.JoinHostAndPath(_c.host, NoQueue.Route)),
		pub.RelativeURL(relativeURL),
		pub.Options(_c.opts...),
	)
}

// NoQueue demonstrates how the NoQueue subscription option is used to create
// a multicast request/response communication pattern.
// All instances of this microservice will respond to each request.
func (_c MulticastClient) NoQueue(ctx context.Context, relativeURL string) iter.Seq[*pub.Response] { // MARKER: NoQueue
	return _c.svc.Publish(
		ctx,
		pub.Method(NoQueue.Method),
		pub.URL(httpx.JoinHostAndPath(_c.host, NoQueue.Route)),
		pub.RelativeURL(relativeURL),
		pub.Options(_c.opts...),
	)
}

// DefaultQueue demonstrates how the DefaultQueue subscription option is used to create
// a unicast request/response communication pattern.
// Only one of the instances of this microservice will respond to each request.
func (_c Client) DefaultQueue(ctx context.Context, relativeURL string) (res *http.Response, err error) { // MARKER: DefaultQueue
	return _c.svc.Request(
		ctx,
		pub.Method(DefaultQueue.Method),
		pub.URL(httpx.JoinHostAndPath(_c.host, DefaultQueue.Route)),
		pub.RelativeURL(relativeURL),
		pub.Options(_c.opts...),
	)
}

// DefaultQueue demonstrates how the DefaultQueue subscription option is used to create
// a unicast request/response communication pattern.
// Only one of the instances of this microservice will respond to each request.
func (_c MulticastClient) DefaultQueue(ctx context.Context, relativeURL string) iter.Seq[*pub.Response] { // MARKER: DefaultQueue
	return _c.svc.Publish(
		ctx,
		pub.Method(DefaultQueue.Method),
		pub.URL(httpx.JoinHostAndPath(_c.host, DefaultQueue.Route)),
		pub.RelativeURL(relativeURL),
		pub.Options(_c.opts...),
	)
}

// CacheLoad looks up an element in the distributed cache of the microservice.
func (_c Client) CacheLoad(ctx context.Context, relativeURL string) (res *http.Response, err error) { // MARKER: CacheLoad
	return _c.svc.Request(
		ctx,
		pub.Method(CacheLoad.Method),
		pub.URL(httpx.JoinHostAndPath(_c.host, CacheLoad.Route)),
		pub.RelativeURL(relativeURL),
		pub.Options(_c.opts...),
	)
}

// CacheLoad looks up an element in the distributed cache of the microservice.
func (_c MulticastClient) CacheLoad(ctx context.Context, relativeURL string) iter.Seq[*pub.Response] { // MARKER: CacheLoad
	return _c.svc.Publish(
		ctx,
		pub.Method(CacheLoad.Method),
		pub.URL(httpx.JoinHostAndPath(_c.host, CacheLoad.Route)),
		pub.RelativeURL(relativeURL),
		pub.Options(_c.opts...),
	)
}

// CacheStore stores an element in the distributed cache of the microservice.
func (_c Client) CacheStore(ctx context.Context, relativeURL string) (res *http.Response, err error) { // MARKER: CacheStore
	return _c.svc.Request(
		ctx,
		pub.Method(CacheStore.Method),
		pub.URL(httpx.JoinHostAndPath(_c.host, CacheStore.Route)),
		pub.RelativeURL(relativeURL),
		pub.Options(_c.opts...),
	)
}

// CacheStore stores an element in the distributed cache of the microservice.
func (_c MulticastClient) CacheStore(ctx context.Context, relativeURL string) iter.Seq[*pub.Response] { // MARKER: CacheStore
	return _c.svc.Publish(
		ctx,
		pub.Method(CacheStore.Method),
		pub.URL(httpx.JoinHostAndPath(_c.host, CacheStore.Route)),
		pub.RelativeURL(relativeURL),
		pub.Options(_c.opts...),
	)
}
