// Code generated by cmd/genmock. DO NOT EDIT.

package soakflow

import (
	"context"
	"testing"

	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/workflow"
	"github.com/microbus-io/testarossa"
)

func TestSoakflow_Mock(t *testing.T) {
	t.Parallel()
	ctx := t.Context()

	mock := NewMock()
	mock.SetDeployment(connector.TESTING)

	t.Run("on_startup", func(t *testing.T) {
		assert := testarossa.For(t)
		err := mock.OnStartup(ctx)
		assert.NoError(err)
	})

	t.Run("on_shutdown", func(t *testing.T) {
		assert := testarossa.For(t)
		err := mock.OnShutdown(ctx)
		assert.NoError(err)
	})

	t.Run("seed", func(t *testing.T) { // MARKER: Seed
		assert := testarossa.For(t)

		mock.MockSeed(func(ctx context.Context, flow *workflow.Flow) (done bool, err error) {
			return
		})
		_, err := mock.Seed(ctx, nil)
		assert.NoError(err)
	})

	t.Run("fan_a", func(t *testing.T) { // MARKER: FanA
		assert := testarossa.For(t)

		mock.MockFanA(func(ctx context.Context, flow *workflow.Flow) (done bool, err error) {
			return
		})
		_, err := mock.FanA(ctx, nil)
		assert.NoError(err)
	})

	t.Run("work", func(t *testing.T) { // MARKER: Work
		assert := testarossa.For(t)

		mock.MockWork(func(ctx context.Context, flow *workflow.Flow) (done bool, err error) {
			return
		})
		_, err := mock.Work(ctx, nil)
		assert.NoError(err)
	})

	t.Run("collect", func(t *testing.T) { // MARKER: Collect
		assert := testarossa.For(t)

		mock.MockCollect(func(ctx context.Context, flow *workflow.Flow) (done bool, err error) {
			return
		})
		_, err := mock.Collect(ctx, nil)
		assert.NoError(err)
	})

	t.Run("loop", func(t *testing.T) { // MARKER: Loop
		assert := testarossa.For(t)

		mock.MockLoop(func(ctx context.Context, flow *workflow.Flow) (done bool, err error) {
			return
		})
		_, err := mock.Loop(ctx, nil)
		assert.NoError(err)
	})

	t.Run("boom_r", func(t *testing.T) { // MARKER: BoomR
		assert := testarossa.For(t)

		mock.MockBoomR(func(ctx context.Context, flow *workflow.Flow) (done bool, err error) {
			return
		})
		_, err := mock.BoomR(ctx, nil)
		assert.NoError(err)
	})

	t.Run("recover", func(t *testing.T) { // MARKER: Recover
		assert := testarossa.For(t)

		mock.MockRecover(func(ctx context.Context, flow *workflow.Flow) (done bool, err error) {
			return
		})
		_, err := mock.Recover(ctx, nil)
		assert.NoError(err)
	})

	t.Run("boom_f", func(t *testing.T) { // MARKER: BoomF
		assert := testarossa.For(t)

		mock.MockBoomF(func(ctx context.Context, flow *workflow.Flow) (done bool, err error) {
			return
		})
		_, err := mock.BoomF(ctx, nil)
		assert.NoError(err)
	})

	t.Run("join", func(t *testing.T) { // MARKER: Join
		assert := testarossa.For(t)

		mock.MockJoin(func(ctx context.Context, flow *workflow.Flow) (done bool, err error) {
			return
		})
		_, err := mock.Join(ctx, nil)
		assert.NoError(err)
	})

	t.Run("inner_entry", func(t *testing.T) { // MARKER: InnerEntry
		assert := testarossa.For(t)

		mock.MockInnerEntry(func(ctx context.Context, flow *workflow.Flow) (done bool, err error) {
			return
		})
		_, err := mock.InnerEntry(ctx, nil)
		assert.NoError(err)
	})

	t.Run("run_sub", func(t *testing.T) { // MARKER: RunSub
		assert := testarossa.For(t)

		mock.MockRunSub(func(ctx context.Context, flow *workflow.Flow) (done bool, err error) {
			return
		})
		_, err := mock.RunSub(ctx, nil)
		assert.NoError(err)
	})

	t.Run("soak", func(t *testing.T) { // MARKER: Soak
		assert := testarossa.For(t)

		mock.MockSoak(func(ctx context.Context, flow *workflow.Flow) (done bool, err error) {
			return
		})
		graph, err := mock.Soak(ctx)
		if assert.NoError(err) {
			assert.NotNil(graph)
		}
	})

	t.Run("inner", func(t *testing.T) { // MARKER: Inner
		assert := testarossa.For(t)

		mock.MockInner(func(ctx context.Context, flow *workflow.Flow) (done bool, err error) {
			return
		})
		graph, err := mock.Inner(ctx)
		if assert.NoError(err) {
			assert.NotNil(graph)
		}
	})

}
