# Copyright (c) 2023-2024 Microbus LLC and various contributors
# 
# This file and the project encapsulating it are the confidential intellectual property of Microbus LLC.
# Neither may be used, copied or distributed without the express written consent of Microbus LLC.

---
# General
#
# host - The host name of the microservice
# description - A human-friendly description of the microservice
# integrationTests - Whether or not to generate integration tests (defaults to true)
# openApi - Whether or not to generate an OpenAPI document at openapi.json (defaults to true)
general:
  host: hello.example
  description: The Hello microservice demonstrates the various capabilities of a microservice.

# Databases
#
# name - A name for the database
# type - The type of the database, "mariadb" or "mysql"
# runtime - "true" to connect to the database in runtime (defaults to "true")
# integrationTests - "true" to connect to the database in integration tests (defaults to "true")
databases:
  # - name: SQL
  #   type: mariadb

# Config properties
#
# signature - Func() (val Type)
# description - Documentation
# default - A default value (defaults to empty)
# validation - A validation pattern
#   str ^[a-zA-Z0-9]+$
#   bool
#   int [0,60]
#   float [0.0,1.0)
#   dur (0s,24h]
#   set Red|Green|Blue
#   url
#   email
#   json
# callback - "true" to handle the change event (defaults to "false")
# secret - "true" to indicate a secret (defaults to "false")
configs:
  - signature: Greeting() (greeting string)
    description: Greeting to use.
    default: Hello
  - signature: Repeat() (count int)
    description: Repeat indicates how many times to display the greeting.
    default: 1
    validation: int [0,100]

# Functions
#
# signature - Func(name Type, name Type) (name Type, name Type, httpStatusCode int)
# description - Documentation
# path - The subscription path
#   (empty) - The function name in kebab-case
#   /path - Default port :443
#   /directory/ - All paths under the directory
#   /obj/*/path - Wildcard path segment
#   :443/path
#   :443/... - Ellipsis denotes the function name in kebab-case
#   :443 - Root path
#   //example.com:443/path
#   https://example.com:443/path
# queue - The subscription queue
#   default - Load balanced (default)
#   none - Pervasive
# openApi - Whether or not to include this endpoint in OpenAPI document of the microservice (defaults to true)
functions:
  # - signature:
  #   description:

# Event sources
#
# signature - OnFunc(name Type, name Type) (name Type, name Type, httpStatusCode int)
# description - Documentation
# path - The subscription path
#   (empty) - The function name in kebab-case
#   /path - Default port :417
#   /directory/ - All paths under the directory
#   /obj/*/path - Wildcard path segment
#   :417/path
#   :417/... - Ellipsis denotes the function name in kebab-case
#   :417 - Root path
#   //example.com:417/path
#   https://example.com:417/path
events:
  # - signature:
  #   description:

# Event sinks
#
# signature - OnFunc(name Type, name Type) (name Type, name Type, httpStatusCode int)
# description - Documentation
# event - The name of the event at the source (defaults to the function name)
# source - The package path of the microservice that is the source of the event
# forHost - For an event source with an overridden host name
# queue - The subscription queue
#   default - Load balanced (default)
#   none - Pervasive
sinks:
  # - signature:
  #   description:
  #   source: package/path/of/another/microservice

# Web handlers
#
# signature - Func()
# description - Documentation
# path - The subscription path
#   (empty) - The function name in kebab-case
#   /path - Default port :443
#   /directory/ - All paths under the directory
#   /obj/*/path - Wildcard path segment
#   :443/path
#   :443/... - Ellipsis denotes the function name in kebab-case
#   :443 - Root path
#   //example.com:443/path
#   https://example.com:443/path
# queue - The subscription queue
#   default - Load balanced (default)
#   none - Pervasive
# openApi - Whether or not to include this endpoint in OpenAPI document of the microservice (defaults to true)
webs:
  - signature: Hello()
    description: Hello prints a greeting.
  - signature: Echo()
    description: Echo back the incoming request in wire format.
  - signature: Ping()
    description: Ping all microservices and list them.
  - signature: Calculator()
    description: |-
      Calculator renders a UI for a calculator.
      The calculation operation is delegated to another microservice in order to demonstrate
      a call from one microservice to another.
  - signature: BusJPEG()
    path: /bus.jpeg
    description: BusJPEG serves an image from the embedded resources.
  - signature: Localization()
    description: Localization prints hello in the language best matching the request's Accept-Language header.

# Tickers
#
# signature - Func()
# description - Documentation
# interval - Duration between iterations (e.g. 15m)
tickers:
  - signature: TickTock()
    description: TickTock is executed every 10 seconds.
    interval: 10s

# Metrics
#
# signature - Func(measure Type, label Type, label Type)
#   RequestDurationSeconds(dur time.Duration, method string, success bool)
#   MemoryUsageBytes(b int64)
#   DistanceMiles(miles float64, countryCode int)
#   RequestsCount(count int, domain string) - unit-less accumulating count
#   CPUSecondsTotal(dur time.Duration) - accumulating count with unit
#   See https://prometheus.io/docs/practices/naming/ for naming best practices
# description - Documentation
# kind - The kind of the metric, "histogram", "gauge" or "counter" (default)
# buckets - Bucket boundaries for histograms [x,y,z,...]
# alias - The name of the metric in Prometheus (defaults to package+function in snake_case)
metrics:
  # - signature:
  #   description:
  #   kind:
