# Copyright (c) 2023 Microbus LLC and various contributors
# 
# This file and the project encapsulating it are the confidential intellectual property of Microbus LLC.
# Neither may be used, copied or distributed without the express written consent of Microbus LLC.

---
# General
#
# host - The host name of the microservice
# description - A human-friendly description of the microservice
# integrationTests - Whether or not to generate integration tests (defaults to true)
general:
  host: http.ingress.sys
  description: The HTTP Ingress microservice relays incoming HTTP requests to the NATS bus.

# Databases
#
# name - A name for the database
# type - The type of the database, "mariadb" or "mysql"
# runtime - "true" to connect to the database in runtime (defaults to "true")
# integrationTests - "true" to connect to the database in integration tests (defaults to "true")
databases:
  # - name: SQL
  #   type: mariadb

# Config properties
#
# signature - Func() (val Type)
# description - Documentation
# default - A default value (defaults to empty)
# validation - A validation pattern
#   str ^[a-zA-Z0-9]+$
#   bool
#   int [0,60]
#   float [0.0,1.0)
#   dur (0s,24h]
#   set Red|Green|Blue
#   url
#   email
#   json
# callback - "true" to handle the change event (defaults to "false")
# secret - "true" to indicate a secret (defaults to "false")
configs:
  - signature: TimeBudget() (budget time.Duration)
    description: |-
      TimeBudget specifies the timeout for handling a request, after it has been read.
      A value of 0 or less indicates no time budget.
    default: 20s
    validation: dur [0s,]
  - signature: Ports() (port string)
    description: Ports is a comma-separated list of HTTP ports on which to listen for requests.
    default: 8080
    callback: true
  - signature: RequestMemoryLimit() (megaBytes int)
    description: RequestMemoryLimit is the memory capacity used to hold pending requests, in megabytes.
    default: 4096
    validation: int [1,]
  - signature: AllowedOrigins() (origins string)
    description: |-
      AllowedOrigins is a comma-separated list of CORS origins to allow requests from.
      The * origin can be used to allow CORS request from all origins.
    default: "*"
    callback: true
  - signature: PortMappings() (mappings string)
    description: |
      PortMappings is a comma-separated list of mappings in the form x:y->z where x is the inbound
      HTTP port, y is the requested NATS port, and z is the port to serve.
      An HTTP request https://ingresshost:x/servicehost:y/path is mapped to internal NATS
      request https://servicehost:z/path .
      Both x and y can be * to indicate all ports. Setting z to * indicates to serve the requested
      port y without change. Specific rules take precedence over * rules.
      The default mapping grants access to all internal ports via HTTP port 8080 but restricts
      HTTP ports 443 and 80 to only internal port 443.
    default: 8080:*->*, 443:*->443, 80:*->443
    callback: true
  - signature: ReadTimeout() (timeout time.Duration)
    description: ReadTimeout specifies the timeout for fully reading a request.
    default: 5m
    validation: dur [1s,]
    callback: true
  - signature: WriteTimeout() (timeout time.Duration)
    description: WriteTimeout specifies the timeout for fully writing the response to a request.
    default: 5m
    validation: dur [1s,]
    callback: true
  - signature: ReadHeaderTimeout() (timeout time.Duration)
    description: ReadHeaderTimeout specifies the timeout for fully reading the header of a request.
    default: 20s
    validation: dur [1s,]
    callback: true
  - signature: Middleware() (viaURL string)
    description: |-
      Middleware defines a microservice to delegate all requests to.
      The URL of the middleware must be fully qualified, for example,
      "https://middle.ware/serve" or "https://middle.ware:123".
  - signature: BlockedPaths() (blockedPaths string)
    description: |-
      A newline-separated list of paths or extensions to block with a 404.
      Paths should not include any arguments.
      Extensions are specified with "*.ext".
    callback: true
    default: |-
      /geoserver
      /console/
      /.env
      /.amazon_aws
      /solr/admin/info/system
      /remote/login
      /Autodiscover/Autodiscover.xml
      /autodiscover/autodiscover.json
      /api/v2/static/not.found
      /api/sonicos/tfa
      /_ignition/execute-solution
      /admin.html
      /auth.html
      /auth1.html
      /readme.txt
      /__Additional
      /Portal0000.htm
      /docs/cplugError.html/
      /CSS/Miniweb.css
      /scripts/WPnBr.dll
      /.git/config
      /cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh
      /actuator/gateway/routes
      /actuator/health
      /Public/home/js/check.js
      /mifs/.;/services/LogService
      /dns-query
      /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application
      /owa/auth/x.js
      /static/admin/javascript/hetong.js
      /.git/HEAD
      /sslvpnLogin.html
      /vpn/index.html
      /wsman
      /geoserver/web
      /remote/logincheck
      /epa/scripts/win/nsepa_setup.exe
      /.well-known/security.txt
      /cf_scripts/scripts/ajax/ckeditor/ckeditor.js
      /Temporary_Listen_Addresses/
      /manager/html
      /logon/LogonPoint/custom.html
      /logon/LogonPoint/index.html
      /catalog-portal/ui/oauth/verify
      *.cfm
      *.asp
      *.aspx
      *.cgi
      *.jsa
      *.jsp
      *.shtml
      *.php
      *.jhtml
      *.mwsl
      *.dll
      *.esp
      *.exe

# Functions
#
# signature - Func(name Type, name Type) (name Type, name Type, httpStatusCode int)
# description - Documentation
# path - The subscription path
#   (empty) - The function name in kebab-case
#   /path - Default port :443
#   /directory/ - All paths under the directory
#   /obj/*/path - Wildcard path segment
#   :443/path
#   :443/... - Ellipsis denotes the function name in kebab-case
#   :443 - Root path
#   //example.com:443/path
#   https://example.com:443/path
# queue - The subscription queue
#   default - Load balanced (default)
#   none - Pervasive
functions:
  # - signature:
  #   description:

# Event sources
#
# signature - OnFunc(name Type, name Type) (name Type, name Type, httpStatusCode int)
# description - Documentation
# path - The subscription path
#   (empty) - The function name in kebab-case
#   /path - Default port :417
#   /directory/ - All paths under the directory
#   /obj/*/path - Wildcard path segment
#   :417/path
#   :417/... - Ellipsis denotes the function name in kebab-case
#   :417 - Root path
#   //example.com:417/path
#   https://example.com:417/path
events:
  # - signature:
  #   description:

# Event sinks
#
# signature - OnFunc(name Type, name Type) (name Type, name Type, httpStatusCode int)
# description - Documentation
# event - The name of the event at the source (defaults to the function name)
# source - The package path of the microservice that is the source of the event
# forHost - For an event source with an overridden host name
# queue - The subscription queue
#   default - Load balanced (default)
#   none - Pervasive
sinks:
  # - signature:
  #   description:
  #   source: package/path/of/another/microservice

# Web handlers
#
# signature - Func()
# description - Documentation
# path - The subscription path
#   (empty) - The function name in kebab-case
#   /path - Default port :443
#   /directory/ - All paths under the directory
#   /obj/*/path - Wildcard path segment
#   :443/path
#   :443/... - Ellipsis denotes the function name in kebab-case
#   :443 - Root path
#   //example.com:443/path
#   https://example.com:443/path
# queue - The subscription queue
#   default - Load balanced (default)
#   none - Pervasive
webs:
  # - signature:
  #   description:

# Tickers
#
# signature - Func()
# description - Documentation
# interval - Duration between iterations (e.g. 15m)
# timeBudget - Duration to complete an iteration
tickers:
  # - signature:
  #   description:
  #   interval:

# Metrics
#
# signature - Func(measure Type, label Type, label Type)
#   RequestDurationSeconds(dur time.Duration, method string, success bool)
#   MemoryUsageBytes(b int64)
#   DistanceMiles(miles float64, countryCode int)
#   RequestsCount(count int, domain string) - unit-less accumulating count
#   CPUSecondsTotal(dur time.Duration) - accumulating count with unit
#   See https://prometheus.io/docs/practices/naming/ for naming best practices
# description - Documentation
# kind - The kind of the metric, "histogram", "gauge" or "counter" (default)
# buckets - Bucket boundaries for histograms [x,y,z,...]
# alias - The name of the metric in Prometheus (defaults to package+function in snake_case)
metrics:
  # - signature:
  #   description:
  #   kind:
