/*
Copyright (c) 2023-2026 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cmd/genservice. DO NOT EDIT.

package helloapi

import (
	"context"
	"iter"
	"net/http"

	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/fabric/pub"
	"github.com/microbus-io/fabric/service"
)

// Client is a lightweight proxy for making unicast calls to the microservice.
type Client struct {
	svc  service.Publisher
	host string
	opts []pub.Option
}

// NewClient creates a new unicast client proxy to the microservice.
func NewClient(caller service.Publisher) Client {
	return Client{svc: caller, host: Hostname}
}

// ForHost returns a copy of the client with a different hostname to be applied to requests.
func (_c Client) ForHost(host string) Client {
	return Client{svc: _c.svc, host: host, opts: _c.opts}
}

// WithOptions returns a copy of the client with options to be applied to requests.
func (_c Client) WithOptions(opts ...pub.Option) Client {
	return Client{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...)}
}

// MulticastClient is a lightweight proxy for making multicast calls to the microservice.
type MulticastClient struct {
	svc  service.Publisher
	host string
	opts []pub.Option
}

// NewMulticastClient creates a new multicast client proxy to the microservice.
func NewMulticastClient(caller service.Publisher) MulticastClient {
	return MulticastClient{svc: caller, host: Hostname}
}

// ForHost returns a copy of the client with a different hostname to be applied to requests.
func (_c MulticastClient) ForHost(host string) MulticastClient {
	return MulticastClient{svc: _c.svc, host: host, opts: _c.opts}
}

// WithOptions returns a copy of the client with options to be applied to requests.
func (_c MulticastClient) WithOptions(opts ...pub.Option) MulticastClient {
	return MulticastClient{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...)}
}

// Hello prints a greeting.
func (_c Client) Hello(ctx context.Context, method string, relativeURL string, body any) (res *http.Response, err error) { // MARKER: Hello
	if method == "" {
		method = Hello.Method
	}
	if method == "ANY" {
		method = "POST"
	}
	return _c.svc.Request(
		ctx,
		pub.Method(method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Hello.Route)),
		pub.RelativeURL(relativeURL),
		pub.Body(body),
		pub.Options(_c.opts...),
	)
}

// Hello prints a greeting.
func (_c MulticastClient) Hello(ctx context.Context, method string, relativeURL string, body any) iter.Seq[*pub.Response] { // MARKER: Hello
	if method == "" {
		method = Hello.Method
	}
	if method == "ANY" {
		method = "POST"
	}
	return _c.svc.Publish(
		ctx,
		pub.Method(method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Hello.Route)),
		pub.RelativeURL(relativeURL),
		pub.Body(body),
		pub.Options(_c.opts...),
	)
}

// Echo back the incoming request in wire format.
func (_c Client) Echo(ctx context.Context, method string, relativeURL string, body any) (res *http.Response, err error) { // MARKER: Echo
	if method == "" {
		method = Echo.Method
	}
	if method == "ANY" {
		method = "POST"
	}
	return _c.svc.Request(
		ctx,
		pub.Method(method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Echo.Route)),
		pub.RelativeURL(relativeURL),
		pub.Body(body),
		pub.Options(_c.opts...),
	)
}

// Echo back the incoming request in wire format.
func (_c MulticastClient) Echo(ctx context.Context, method string, relativeURL string, body any) iter.Seq[*pub.Response] { // MARKER: Echo
	if method == "" {
		method = Echo.Method
	}
	if method == "ANY" {
		method = "POST"
	}
	return _c.svc.Publish(
		ctx,
		pub.Method(method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Echo.Route)),
		pub.RelativeURL(relativeURL),
		pub.Body(body),
		pub.Options(_c.opts...),
	)
}

// Ping all microservices and list them.
func (_c Client) Ping(ctx context.Context, method string, relativeURL string, body any) (res *http.Response, err error) { // MARKER: Ping
	if method == "" {
		method = Ping.Method
	}
	if method == "ANY" {
		method = "POST"
	}
	return _c.svc.Request(
		ctx,
		pub.Method(method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Ping.Route)),
		pub.RelativeURL(relativeURL),
		pub.Body(body),
		pub.Options(_c.opts...),
	)
}

// Ping all microservices and list them.
func (_c MulticastClient) Ping(ctx context.Context, method string, relativeURL string, body any) iter.Seq[*pub.Response] { // MARKER: Ping
	if method == "" {
		method = Ping.Method
	}
	if method == "ANY" {
		method = "POST"
	}
	return _c.svc.Publish(
		ctx,
		pub.Method(method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Ping.Route)),
		pub.RelativeURL(relativeURL),
		pub.Body(body),
		pub.Options(_c.opts...),
	)
}

// Calculator renders a UI for a calculator. The calculation operation is delegated to another microservice in order to demonstrate a call from one microservice to another.
func (_c Client) Calculator(ctx context.Context, method string, relativeURL string, body any) (res *http.Response, err error) { // MARKER: Calculator
	if method == "" {
		method = Calculator.Method
	}
	if method == "ANY" {
		method = "POST"
	}
	return _c.svc.Request(
		ctx,
		pub.Method(method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Calculator.Route)),
		pub.RelativeURL(relativeURL),
		pub.Body(body),
		pub.Options(_c.opts...),
	)
}

// Calculator renders a UI for a calculator. The calculation operation is delegated to another microservice in order to demonstrate a call from one microservice to another.
func (_c MulticastClient) Calculator(ctx context.Context, method string, relativeURL string, body any) iter.Seq[*pub.Response] { // MARKER: Calculator
	if method == "" {
		method = Calculator.Method
	}
	if method == "ANY" {
		method = "POST"
	}
	return _c.svc.Publish(
		ctx,
		pub.Method(method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Calculator.Route)),
		pub.RelativeURL(relativeURL),
		pub.Body(body),
		pub.Options(_c.opts...),
	)
}

// BusPNG serves an image from the embedded resources.
func (_c Client) BusPNG(ctx context.Context, relativeURL string) (res *http.Response, err error) { // MARKER: BusPNG
	return _c.svc.Request(
		ctx,
		pub.Method(BusPNG.Method),
		pub.URL(httpx.JoinHostAndPath(_c.host, BusPNG.Route)),
		pub.RelativeURL(relativeURL),
		pub.Options(_c.opts...),
	)
}

// BusPNG serves an image from the embedded resources.
func (_c MulticastClient) BusPNG(ctx context.Context, relativeURL string) iter.Seq[*pub.Response] { // MARKER: BusPNG
	return _c.svc.Publish(
		ctx,
		pub.Method(BusPNG.Method),
		pub.URL(httpx.JoinHostAndPath(_c.host, BusPNG.Route)),
		pub.RelativeURL(relativeURL),
		pub.Options(_c.opts...),
	)
}

// Localization prints hello in the language best matching the request's Accept-Language header.
func (_c Client) Localization(ctx context.Context, method string, relativeURL string, body any) (res *http.Response, err error) { // MARKER: Localization
	if method == "" {
		method = Localization.Method
	}
	if method == "ANY" {
		method = "POST"
	}
	return _c.svc.Request(
		ctx,
		pub.Method(method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Localization.Route)),
		pub.RelativeURL(relativeURL),
		pub.Body(body),
		pub.Options(_c.opts...),
	)
}

// Localization prints hello in the language best matching the request's Accept-Language header.
func (_c MulticastClient) Localization(ctx context.Context, method string, relativeURL string, body any) iter.Seq[*pub.Response] { // MARKER: Localization
	if method == "" {
		method = Localization.Method
	}
	if method == "ANY" {
		method = "POST"
	}
	return _c.svc.Publish(
		ctx,
		pub.Method(method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Localization.Route)),
		pub.RelativeURL(relativeURL),
		pub.Body(body),
		pub.Options(_c.opts...),
	)
}

// Root is the top-most root page.
func (_c Client) Root(ctx context.Context, method string, relativeURL string, body any) (res *http.Response, err error) { // MARKER: Root
	if method == "" {
		method = Root.Method
	}
	if method == "ANY" {
		method = "POST"
	}
	return _c.svc.Request(
		ctx,
		pub.Method(method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Root.Route)),
		pub.RelativeURL(relativeURL),
		pub.Body(body),
		pub.Options(_c.opts...),
	)
}

// Root is the top-most root page.
func (_c MulticastClient) Root(ctx context.Context, method string, relativeURL string, body any) iter.Seq[*pub.Response] { // MARKER: Root
	if method == "" {
		method = Root.Method
	}
	if method == "ANY" {
		method = "POST"
	}
	return _c.svc.Publish(
		ctx,
		pub.Method(method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Root.Route)),
		pub.RelativeURL(relativeURL),
		pub.Body(body),
		pub.Options(_c.opts...),
	)
}
