---
title: "CreditApproval"
config:
  themeCSS: ".flowchartTitleText { fill: #32a7c1; }"
---
graph LR
    classDef task fill:#32a7c1,color:#f4f2ef,stroke:#32a7c1
    classDef term fill:#e5f4f3,color:#434343,stroke:#32a7c1
    linkStyle default stroke:#32a7c1

    t0["SubmitCreditApplication"]:::task
    t1["VerifyCredit"]:::task
    t2["VerifyEmployment"]:::task
    t3["IdentityVerification"]:::task
    t4["HandleCreditError"]:::task
    t5["ReviewJoin"]:::task
    t5_reduce(("reduce")):::term
    t5_reduce --> t5
    t6["ReviewCredit"]:::task
    t7["RequestMoreInfo"]:::task
    t8["Decision"]:::task
    t0 --> t1
    t1 -->|"onError"| t4
    t4 --> t5_reduce
    t0 -->|"for each"| t2
    t0 --> t3
    t1 --> t5_reduce
    t2 --> t5_reduce
    t3 --> t5_reduce
    t5 -->|"goto"| t7
    t5 --> t6
    t6 -->|"goto"| t7
    t7 --> t6
    t6 --> t8
    _start(( )):::term --> t0
    t8 --> _end(( )):::term
