---
title: "IdentityVerification"
config:
  themeCSS: ".flowchartTitleText { fill: #32a7c1; }"
---
graph LR
    classDef task fill:#32a7c1,color:#f4f2ef,stroke:#32a7c1
    classDef term fill:#e5f4f3,color:#434343,stroke:#32a7c1
    linkStyle default stroke:#32a7c1

    t0["InitIdentityVerification"]:::task
    t1["VerifySSN"]:::task
    t2["VerifyAddress"]:::task
    t3["VerifyPhoneNumber"]:::task
    t4["IdentityDecision"]:::task
    t4_reduce(("reduce")):::term
    t4_reduce --> t4
    t0 --> t1
    t0 --> t2
    t0 --> t3
    t1 --> t4_reduce
    t2 --> t4_reduce
    t3 --> t4_reduce
    _start(( )):::term --> t0
    t4 --> _end(( )):::term
