// Code generated by cmd/genservice. DO NOT EDIT.

package agentstudio

import (
	"context"
	"net/http"

	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/connector"
)

// Mock is a mockable version of the microservice, allowing functions, event sinks and web handlers to be mocked.
type Mock struct {
	*Intermediate
	mockListFlows      func(w http.ResponseWriter, r *http.Request) (err error) // MARKER: ListFlows
	mockFlowDetail     func(w http.ResponseWriter, r *http.Request) (err error) // MARKER: FlowDetail
	mockStepDetail     func(w http.ResponseWriter, r *http.Request) (err error) // MARKER: StepDetail
	mockListWorkflows  func(w http.ResponseWriter, r *http.Request) (err error) // MARKER: ListWorkflows
	mockWorkflowDetail func(w http.ResponseWriter, r *http.Request) (err error) // MARKER: WorkflowDetail
	mockRunWorkflow    func(w http.ResponseWriter, r *http.Request) (err error) // MARKER: RunWorkflow
	mockContinueFlow   func(w http.ResponseWriter, r *http.Request) (err error) // MARKER: ContinueFlow
	mockResumeFlow     func(w http.ResponseWriter, r *http.Request) (err error) // MARKER: ResumeFlow
	mockForkFromStep   func(w http.ResponseWriter, r *http.Request) (err error) // MARKER: ForkFromStep
	mockPollFlow       func(w http.ResponseWriter, r *http.Request) (err error) // MARKER: PollFlow
	mockTaskDetail     func(w http.ResponseWriter, r *http.Request) (err error) // MARKER: TaskDetail
	mockDashboard      func(w http.ResponseWriter, r *http.Request) (err error) // MARKER: Dashboard
	mockAssets         func(w http.ResponseWriter, r *http.Request) (err error) // MARKER: Assets
}

// NewMock creates a new mockable version of the microservice.
func NewMock() *Mock {
	svc := &Mock{}
	svc.Intermediate = NewIntermediate(svc)
	svc.SetVersion(7357) // Stands for TEST
	return svc
}

// OnStartup is called when the microservice is started up.
func (svc *Mock) OnStartup(ctx context.Context) (err error) {
	if svc.Deployment() != connector.LOCAL && svc.Deployment() != connector.TESTING {
		return errors.New("mocking disallowed in %s deployment", svc.Deployment())
	}
	return nil
}

// OnShutdown is called when the microservice is shut down.
func (svc *Mock) OnShutdown(ctx context.Context) (err error) {
	return nil
}

// MockListFlows sets up a mock handler for ListFlows.
func (svc *Mock) MockListFlows(handler func(w http.ResponseWriter, r *http.Request) (err error)) *Mock { // MARKER: ListFlows
	svc.mockListFlows = handler
	return svc
}

// ListFlows executes the mock handler.
func (svc *Mock) ListFlows(w http.ResponseWriter, r *http.Request) (err error) { // MARKER: ListFlows
	if svc.mockListFlows != nil {
		err = svc.mockListFlows(w, r)
	}
	return errors.Trace(err)
}

// MockFlowDetail sets up a mock handler for FlowDetail.
func (svc *Mock) MockFlowDetail(handler func(w http.ResponseWriter, r *http.Request) (err error)) *Mock { // MARKER: FlowDetail
	svc.mockFlowDetail = handler
	return svc
}

// FlowDetail executes the mock handler.
func (svc *Mock) FlowDetail(w http.ResponseWriter, r *http.Request) (err error) { // MARKER: FlowDetail
	if svc.mockFlowDetail != nil {
		err = svc.mockFlowDetail(w, r)
	}
	return errors.Trace(err)
}

// MockStepDetail sets up a mock handler for StepDetail.
func (svc *Mock) MockStepDetail(handler func(w http.ResponseWriter, r *http.Request) (err error)) *Mock { // MARKER: StepDetail
	svc.mockStepDetail = handler
	return svc
}

// StepDetail executes the mock handler.
func (svc *Mock) StepDetail(w http.ResponseWriter, r *http.Request) (err error) { // MARKER: StepDetail
	if svc.mockStepDetail != nil {
		err = svc.mockStepDetail(w, r)
	}
	return errors.Trace(err)
}

// MockListWorkflows sets up a mock handler for ListWorkflows.
func (svc *Mock) MockListWorkflows(handler func(w http.ResponseWriter, r *http.Request) (err error)) *Mock { // MARKER: ListWorkflows
	svc.mockListWorkflows = handler
	return svc
}

// ListWorkflows executes the mock handler.
func (svc *Mock) ListWorkflows(w http.ResponseWriter, r *http.Request) (err error) { // MARKER: ListWorkflows
	if svc.mockListWorkflows != nil {
		err = svc.mockListWorkflows(w, r)
	}
	return errors.Trace(err)
}

// MockWorkflowDetail sets up a mock handler for WorkflowDetail.
func (svc *Mock) MockWorkflowDetail(handler func(w http.ResponseWriter, r *http.Request) (err error)) *Mock { // MARKER: WorkflowDetail
	svc.mockWorkflowDetail = handler
	return svc
}

// WorkflowDetail executes the mock handler.
func (svc *Mock) WorkflowDetail(w http.ResponseWriter, r *http.Request) (err error) { // MARKER: WorkflowDetail
	if svc.mockWorkflowDetail != nil {
		err = svc.mockWorkflowDetail(w, r)
	}
	return errors.Trace(err)
}

// MockRunWorkflow sets up a mock handler for RunWorkflow.
func (svc *Mock) MockRunWorkflow(handler func(w http.ResponseWriter, r *http.Request) (err error)) *Mock { // MARKER: RunWorkflow
	svc.mockRunWorkflow = handler
	return svc
}

// RunWorkflow executes the mock handler.
func (svc *Mock) RunWorkflow(w http.ResponseWriter, r *http.Request) (err error) { // MARKER: RunWorkflow
	if svc.mockRunWorkflow != nil {
		err = svc.mockRunWorkflow(w, r)
	}
	return errors.Trace(err)
}

// MockContinueFlow sets up a mock handler for ContinueFlow.
func (svc *Mock) MockContinueFlow(handler func(w http.ResponseWriter, r *http.Request) (err error)) *Mock { // MARKER: ContinueFlow
	svc.mockContinueFlow = handler
	return svc
}

// ContinueFlow executes the mock handler.
func (svc *Mock) ContinueFlow(w http.ResponseWriter, r *http.Request) (err error) { // MARKER: ContinueFlow
	if svc.mockContinueFlow != nil {
		err = svc.mockContinueFlow(w, r)
	}
	return errors.Trace(err)
}

// MockResumeFlow sets up a mock handler for ResumeFlow.
func (svc *Mock) MockResumeFlow(handler func(w http.ResponseWriter, r *http.Request) (err error)) *Mock { // MARKER: ResumeFlow
	svc.mockResumeFlow = handler
	return svc
}

// ResumeFlow executes the mock handler.
func (svc *Mock) ResumeFlow(w http.ResponseWriter, r *http.Request) (err error) { // MARKER: ResumeFlow
	if svc.mockResumeFlow != nil {
		err = svc.mockResumeFlow(w, r)
	}
	return errors.Trace(err)
}

// MockForkFromStep sets up a mock handler for ForkFromStep.
func (svc *Mock) MockForkFromStep(handler func(w http.ResponseWriter, r *http.Request) (err error)) *Mock { // MARKER: ForkFromStep
	svc.mockForkFromStep = handler
	return svc
}

// ForkFromStep executes the mock handler.
func (svc *Mock) ForkFromStep(w http.ResponseWriter, r *http.Request) (err error) { // MARKER: ForkFromStep
	if svc.mockForkFromStep != nil {
		err = svc.mockForkFromStep(w, r)
	}
	return errors.Trace(err)
}

// MockPollFlow sets up a mock handler for PollFlow.
func (svc *Mock) MockPollFlow(handler func(w http.ResponseWriter, r *http.Request) (err error)) *Mock { // MARKER: PollFlow
	svc.mockPollFlow = handler
	return svc
}

// PollFlow executes the mock handler.
func (svc *Mock) PollFlow(w http.ResponseWriter, r *http.Request) (err error) { // MARKER: PollFlow
	if svc.mockPollFlow != nil {
		err = svc.mockPollFlow(w, r)
	}
	return errors.Trace(err)
}

// MockTaskDetail sets up a mock handler for TaskDetail.
func (svc *Mock) MockTaskDetail(handler func(w http.ResponseWriter, r *http.Request) (err error)) *Mock { // MARKER: TaskDetail
	svc.mockTaskDetail = handler
	return svc
}

// TaskDetail executes the mock handler.
func (svc *Mock) TaskDetail(w http.ResponseWriter, r *http.Request) (err error) { // MARKER: TaskDetail
	if svc.mockTaskDetail != nil {
		err = svc.mockTaskDetail(w, r)
	}
	return errors.Trace(err)
}

// MockDashboard sets up a mock handler for Dashboard.
func (svc *Mock) MockDashboard(handler func(w http.ResponseWriter, r *http.Request) (err error)) *Mock { // MARKER: Dashboard
	svc.mockDashboard = handler
	return svc
}

// Dashboard executes the mock handler.
func (svc *Mock) Dashboard(w http.ResponseWriter, r *http.Request) (err error) { // MARKER: Dashboard
	if svc.mockDashboard != nil {
		err = svc.mockDashboard(w, r)
	}
	return errors.Trace(err)
}

// MockAssets sets up a mock handler for Assets.
func (svc *Mock) MockAssets(handler func(w http.ResponseWriter, r *http.Request) (err error)) *Mock { // MARKER: Assets
	svc.mockAssets = handler
	return svc
}

// Assets executes the mock handler.
func (svc *Mock) Assets(w http.ResponseWriter, r *http.Request) (err error) { // MARKER: Assets
	if svc.mockAssets != nil {
		err = svc.mockAssets(w, r)
	}
	return errors.Trace(err)
}
