// Code generated by cmd/genmock. DO NOT EDIT.

package agentstudio

import (
	"net/http"
	"testing"

	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/testarossa"
)

func TestAgentstudio_Mock(t *testing.T) {
	t.Parallel()
	ctx := t.Context()

	mock := NewMock()
	mock.SetDeployment(connector.TESTING)

	t.Run("on_startup", func(t *testing.T) {
		assert := testarossa.For(t)
		err := mock.OnStartup(ctx)
		assert.NoError(err)
	})

	t.Run("on_shutdown", func(t *testing.T) {
		assert := testarossa.For(t)
		err := mock.OnShutdown(ctx)
		assert.NoError(err)
	})

	t.Run("list_flows", func(t *testing.T) { // MARKER: ListFlows
		assert := testarossa.For(t)

		mock.MockListFlows(func(w http.ResponseWriter, r *http.Request) (err error) {
			return nil
		})
		w := httpx.NewResponseRecorder()
		r := httpx.MustNewRequest("GET", "/", nil)
		err := mock.ListFlows(w, r)
		assert.NoError(err)
	})

	t.Run("flow_detail", func(t *testing.T) { // MARKER: FlowDetail
		assert := testarossa.For(t)

		mock.MockFlowDetail(func(w http.ResponseWriter, r *http.Request) (err error) {
			return nil
		})
		w := httpx.NewResponseRecorder()
		r := httpx.MustNewRequest("GET", "/", nil)
		err := mock.FlowDetail(w, r)
		assert.NoError(err)
	})

	t.Run("step_detail", func(t *testing.T) { // MARKER: StepDetail
		assert := testarossa.For(t)

		mock.MockStepDetail(func(w http.ResponseWriter, r *http.Request) (err error) {
			return nil
		})
		w := httpx.NewResponseRecorder()
		r := httpx.MustNewRequest("GET", "/", nil)
		err := mock.StepDetail(w, r)
		assert.NoError(err)
	})

	t.Run("list_workflows", func(t *testing.T) { // MARKER: ListWorkflows
		assert := testarossa.For(t)

		mock.MockListWorkflows(func(w http.ResponseWriter, r *http.Request) (err error) {
			return nil
		})
		w := httpx.NewResponseRecorder()
		r := httpx.MustNewRequest("GET", "/", nil)
		err := mock.ListWorkflows(w, r)
		assert.NoError(err)
	})

	t.Run("workflow_detail", func(t *testing.T) { // MARKER: WorkflowDetail
		assert := testarossa.For(t)

		mock.MockWorkflowDetail(func(w http.ResponseWriter, r *http.Request) (err error) {
			return nil
		})
		w := httpx.NewResponseRecorder()
		r := httpx.MustNewRequest("GET", "/", nil)
		err := mock.WorkflowDetail(w, r)
		assert.NoError(err)
	})

	t.Run("run_workflow", func(t *testing.T) { // MARKER: RunWorkflow
		assert := testarossa.For(t)

		mock.MockRunWorkflow(func(w http.ResponseWriter, r *http.Request) (err error) {
			return nil
		})
		w := httpx.NewResponseRecorder()
		r := httpx.MustNewRequest("GET", "/", nil)
		err := mock.RunWorkflow(w, r)
		assert.NoError(err)
	})

	t.Run("continue_flow", func(t *testing.T) { // MARKER: ContinueFlow
		assert := testarossa.For(t)

		mock.MockContinueFlow(func(w http.ResponseWriter, r *http.Request) (err error) {
			return nil
		})
		w := httpx.NewResponseRecorder()
		r := httpx.MustNewRequest("GET", "/", nil)
		err := mock.ContinueFlow(w, r)
		assert.NoError(err)
	})

	t.Run("resume_flow", func(t *testing.T) { // MARKER: ResumeFlow
		assert := testarossa.For(t)

		mock.MockResumeFlow(func(w http.ResponseWriter, r *http.Request) (err error) {
			return nil
		})
		w := httpx.NewResponseRecorder()
		r := httpx.MustNewRequest("GET", "/", nil)
		err := mock.ResumeFlow(w, r)
		assert.NoError(err)
	})

	t.Run("restart_flow", func(t *testing.T) { // MARKER: RestartFlow
		assert := testarossa.For(t)

		mock.MockRestartFlow(func(w http.ResponseWriter, r *http.Request) (err error) {
			return nil
		})
		w := httpx.NewResponseRecorder()
		r := httpx.MustNewRequest("GET", "/", nil)
		err := mock.RestartFlow(w, r)
		assert.NoError(err)
	})

	t.Run("restart_from_step", func(t *testing.T) { // MARKER: RestartFromStep
		assert := testarossa.For(t)

		mock.MockRestartFromStep(func(w http.ResponseWriter, r *http.Request) (err error) {
			return nil
		})
		w := httpx.NewResponseRecorder()
		r := httpx.MustNewRequest("GET", "/", nil)
		err := mock.RestartFromStep(w, r)
		assert.NoError(err)
	})

	t.Run("poll_flow", func(t *testing.T) { // MARKER: PollFlow
		assert := testarossa.For(t)

		mock.MockPollFlow(func(w http.ResponseWriter, r *http.Request) (err error) {
			return nil
		})
		w := httpx.NewResponseRecorder()
		r := httpx.MustNewRequest("GET", "/", nil)
		err := mock.PollFlow(w, r)
		assert.NoError(err)
	})

	t.Run("task_detail", func(t *testing.T) { // MARKER: TaskDetail
		assert := testarossa.For(t)

		mock.MockTaskDetail(func(w http.ResponseWriter, r *http.Request) (err error) {
			return nil
		})
		w := httpx.NewResponseRecorder()
		r := httpx.MustNewRequest("GET", "/", nil)
		err := mock.TaskDetail(w, r)
		assert.NoError(err)
	})

	t.Run("dashboard", func(t *testing.T) { // MARKER: Dashboard
		assert := testarossa.For(t)

		mock.MockDashboard(func(w http.ResponseWriter, r *http.Request) (err error) {
			return nil
		})
		w := httpx.NewResponseRecorder()
		r := httpx.MustNewRequest("GET", "/", nil)
		err := mock.Dashboard(w, r)
		assert.NoError(err)
	})

	t.Run("assets", func(t *testing.T) { // MARKER: Assets
		assert := testarossa.For(t)

		mock.MockAssets(func(w http.ResponseWriter, r *http.Request) (err error) {
			return nil
		})
		w := httpx.NewResponseRecorder()
		r := httpx.MustNewRequest("GET", "/", nil)
		err := mock.Assets(w, r)
		assert.NoError(err)
	})

}
