{
 "title": "System Overview",
 "tags": [ "microbus" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(microbus_uptime_duration_seconds,deployment)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,4m,5m,10m,15m,30m,1h,3h,4h,6h,12h,24h"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "60 * sum(rate(microbus_server_request_duration_seconds_count{deployment=~\"$deployment\", port!=\"888\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration Median",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(microbus_server_request_duration_seconds_bucket{deployment=~\"$deployment\", port!=\"888\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Error Ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(microbus_server_request_duration_seconds_count{deployment=~\"$deployment\", port!=\"888\",error=\"ERROR\",code=~\"^5..$\"}[$__range]))\n/\nsum(rate(microbus_server_request_duration_seconds_count{deployment=~\"$deployment\", port!=\"888\"}[$__range]))",
     "legendFormat": "{{error}} {{code}}"
    }
   ]
  },
  {
   "title": "Server Duration Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "60 * (sum by (le) (rate(microbus_server_request_duration_seconds_bucket{deployment=~\"$deployment\", port!=\"888\"}[$interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(max_over_time(microbus_uptime_duration_seconds{deployment=~\"$deployment\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count_over_time(microbus_uptime_duration_seconds{deployment=~\"$deployment\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "piechart",
   "description": "Status codes returned by the server",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by(error, code) (increase(microbus_server_request_duration_seconds_count{deployment=~\"$deployment\", port!=\"888\", error=\"ERROR\", code=~\"^5..$\"}[$__range])))",
     "legendFormat": "{{error}} {{code}}"
    },
    {
     "expr": "round(sum by(error, code) (increase(microbus_server_request_duration_seconds_count{deployment=~\"$deployment\", port!=\"888\", error!=\"ERROR\", code=~\"^2..$\"}[$__range])))",
     "legendFormat": "{{error}} {{code}}"
    },
    {
     "expr": "round(sum by(error, code) (increase(microbus_server_request_duration_seconds_count{deployment=~\"$deployment\", port!=\"888\", error=\"ERROR\", code!~\"^5..$\"}[$__range])))",
     "legendFormat": "{{error}} {{code}}"
    },
    {
     "expr": "round(sum by(error, code) (increase(microbus_server_request_duration_seconds_count{deployment=~\"$deployment\", port!=\"888\", error!=\"ERROR\", code!~\"^2..$\"}[$__range])))",
     "legendFormat": "{{error}} {{code}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(host, ver, id) (microbus_uptime_duration_seconds{deployment=~\"$deployment\"})",
     "legendFormat": "{{host}} v{{ver}} {{id}}"
    }
   ]
  },
  {
   "title": "Server Duration Histogram (sec)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(sum by (le) (increase(microbus_server_request_duration_seconds_bucket{deployment=~\"$deployment\", port!=\"888\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Server Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "60 * sum by(service) (rate(microbus_server_request_duration_seconds_count{deployment=~\"$deployment\", port!=\"888\"}[$interval]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Server Response 5xx Error Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(service) (rate(microbus_server_request_duration_seconds_count{deployment=~\"$deployment\", port!=\"888\", error=\"ERROR\", code=~\"^5..$\"}[$interval]))\n/\nsum by(service) (rate(microbus_server_request_duration_seconds_count{deployment=~\"$deployment\", port!=\"888\"}[$interval]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Server Duration 95%ile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, service) (rate(microbus_server_request_duration_seconds_bucket{deployment=~\"$deployment\", port!=\"888\"}[$interval])))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Server Response Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "60 * sum by(code, service) (rate(microbus_server_request_duration_seconds_count{deployment=~\"$deployment\", port!=\"888\", error=\"ERROR\"}[$interval])) != 0",
     "legendFormat": "[{{code}}] {{service}}"
    }
   ]
  },
  {
   "title": "Server Response Size 95%ile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, service) (rate(microbus_server_response_body_bytes_bucket{deployment=~\"$deployment\", port!=\"888\"}[$interval])))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Log Message Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "recpm" } },
   "targets": [
    {
     "expr": "60 * sum by(severity, message) (rate(microbus_log_messages_total{deployment=~\"$deployment\", severity=\"ERROR\"}[$interval])) != 0",
     "legendFormat": "{{severity}} {{message}}"
    },
    {
     "expr": "60 * sum by(severity, message) (rate(microbus_log_messages_total{severity=\"WARN\"}[$__rate_interval])) != 0",
     "legendFormat": "{{severity}} {{message}}"
    },
    {
     "expr": "60 * sum by(severity, message) (rate(microbus_log_messages_total{severity=\"INFO\"}[$__rate_interval])) != 0",
     "legendFormat": "{{severity}} {{message}}"
    },
    {
     "expr": "60 * sum by(severity, message) (rate(microbus_log_messages_total{severity=\"DEBUG\"}[$__rate_interval])) != 0",
     "legendFormat": "{{severity}} {{message}}"
    }
   ]
  },
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Slow Traces",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{duration>=1s && resource.deployment.environment=\"$deployment\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "5xx Error Traces",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{status=error && span.http.status_code >= 500 && resource.deployment.environment=\"$deployment\"}",
     "tableType": "traces"
    }
   ]
  },
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Client Roundtrip Latency Median",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, host) (rate(microbus_client_ack_roundtrip_latency_seconds_bucket{deployment=~\"$deployment\", port!=\"888\"}[$interval])))",
     "legendFormat": "{{host}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Client Timeout Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "60 * sum by(code) (rate(microbus_client_timeout_requests_total{deployment=~\"$deployment\", port!=\"888\"}[$interval])) != 0",
     "legendFormat": "{{code}}"
    }
   ]
  },
  { "title": "Callbacks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Lifecycle Duration 95%ile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, service, name) (rate(microbus_callback_duration_seconds_bucket{deployment=~\"$deployment\", type=\"lifecycle\"}[$interval])))",
     "legendFormat": "{{service}} {{name}}"
    }
   ]
  },
  {
   "title": "Lifecycle Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "60 * sum by(service, name) (rate(microbus_callback_duration_seconds_count{deployment=~\"$deployment\", error=\"ERROR\", type=\"lifecycle\"}[$__rate_interval])) != 0",
     "legendFormat": "{{service}} {{name}}"
    }
   ]
  },
  {
   "title": "Ticker Duration 95%ile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, service, name) (rate(microbus_callback_duration_seconds_bucket{deployment=~\"$deployment\", type=\"ticker\"}[$interval])))",
     "legendFormat": "{{service}} {{name}}"
    }
   ]
  },
  {
   "title": "Ticker Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "60 * sum by(service, name) (rate(microbus_callback_duration_seconds_count{deployment=~\"$deployment\", error=\"ERROR\", type=\"ticker\"}[$__rate_interval])) != 0",
     "legendFormat": "{{service}} {{name}}"
    }
   ]
  },
  {
   "title": "Config Changed Duration 95%ile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, service, name) (rate(microbus_callback_duration_seconds_bucket{deployment=~\"$deployment\", type=\"config\"}[$interval])))",
     "legendFormat": "{{service}} {{name}}"
    }
   ]
  },
  {
   "title": "Config Changed Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "60 * sum by(service, name) (rate(microbus_callback_duration_seconds_count{deployment=~\"$deployment\", error=\"ERROR\", type=\"config\"}[$__rate_interval])) != 0",
     "legendFormat": "{{service}} {{name}}"
    }
   ]
  },
  {
   "title": "Observe Metrics Duration 95%ile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, service, name) (rate(microbus_callback_duration_seconds_bucket{deployment=~\"$deployment\", type=\"metric\"}[$interval])))",
     "legendFormat": "{{service}} {{name}}"
    }
   ]
  },
  {
   "title": "Observe Metrics Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "60 * sum by(service, name) (rate(microbus_callback_duration_seconds_count{deployment=~\"$deployment\", error=\"ERROR\", type=\"metric\"}[$__rate_interval])) != 0",
     "legendFormat": "{{service}} {{name}}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(microbus_cache_operations_total{deployment=~\"$deployment\", op=\"load\",hit!=\"miss\"}[$interval])) /\nsum(increase(microbus_cache_operations_total{deployment=~\"$deployment\", op=\"load\"}[$interval]))",
     "legendFormat": "Hit ratio"
    }
   ]
  },
  {
   "title": "Cache Operations Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "60 * (sum by (op) (rate(microbus_cache_operations_total{deployment=~\"$deployment\"}[$interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(service) (microbus_cache_memory_bytes{deployment=~\"$deployment\"}) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Elements",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 82 },
   "targets": [
    {
     "expr": "round(sum by(service) (microbus_cache_elements{deployment=~\"$deployment\"}) != 0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}