/*
Copyright (c) 2023-2026 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cmd/genservice. DO NOT EDIT.

package httpegressapi

import (
	"context"
	"iter"
	"net/http"

	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/fabric/pub"
	"github.com/microbus-io/fabric/service"
)

// Client is a lightweight proxy for making unicast calls to the microservice.
type Client struct {
	svc  service.Publisher
	host string
	opts []pub.Option
}

// NewClient creates a new unicast client proxy to the microservice.
func NewClient(caller service.Publisher) Client {
	return Client{svc: caller, host: Hostname}
}

// ForHost returns a copy of the client with a different hostname to be applied to requests.
func (_c Client) ForHost(host string) Client {
	return Client{svc: _c.svc, host: host, opts: _c.opts}
}

// WithOptions returns a copy of the client with options to be applied to requests.
func (_c Client) WithOptions(opts ...pub.Option) Client {
	return Client{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...)}
}

// MulticastClient is a lightweight proxy for making multicast calls to the microservice.
type MulticastClient struct {
	svc  service.Publisher
	host string
	opts []pub.Option
}

// NewMulticastClient creates a new multicast client proxy to the microservice.
func NewMulticastClient(caller service.Publisher) MulticastClient {
	return MulticastClient{svc: caller, host: Hostname}
}

// ForHost returns a copy of the client with a different hostname to be applied to requests.
func (_c MulticastClient) ForHost(host string) MulticastClient {
	return MulticastClient{svc: _c.svc, host: host, opts: _c.opts}
}

// WithOptions returns a copy of the client with options to be applied to requests.
func (_c MulticastClient) WithOptions(opts ...pub.Option) MulticastClient {
	return MulticastClient{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...)}
}

// MakeRequest proxies a request to a URL and returns the HTTP response, respecting the timeout set in the context.
// The proxied request is expected to be posted in the body of the request in binary form (RFC7231).
func (_c Client) MakeRequest(ctx context.Context, relativeURL string, body any) (res *http.Response, err error) { // MARKER: MakeRequest
	return _c.svc.Request(
		ctx,
		pub.Method(MakeRequest.Method),
		pub.URL(httpx.JoinHostAndPath(_c.host, MakeRequest.Route)),
		pub.RelativeURL(relativeURL),
		pub.Body(body),
		pub.Options(_c.opts...),
	)
}

// MakeRequest proxies a request to a URL and returns the HTTP response, respecting the timeout set in the context.
// The proxied request is expected to be posted in the body of the request in binary form (RFC7231).
func (_c MulticastClient) MakeRequest(ctx context.Context, relativeURL string, body any) iter.Seq[*pub.Response] { // MARKER: MakeRequest
	return _c.svc.Publish(
		ctx,
		pub.Method(MakeRequest.Method),
		pub.URL(httpx.JoinHostAndPath(_c.host, MakeRequest.Route)),
		pub.RelativeURL(relativeURL),
		pub.Body(body),
		pub.Options(_c.opts...),
	)
}
