graph TD
    classDef task fill:#32a7c1,color:#f4f2ef,stroke:#434343
    classDef sub fill:#ed2e92,color:#f4f2ef,stroke:#434343
    classDef term fill:#e5f4f3,color:#434343,stroke:#434343

    _title{{"credit-approval"}}:::term --> _start
    _start(( )):::term --> t0["submit-credit-application"]:::task
    t0 --> t1["verify-credit"]:::task
    t0 -->|"for each in employers"| t2["verify-employment"]:::task
    t0 --> t3["identity-verification"]:::sub
    t1 --> t4["review-credit"]:::task
    t1 -->|"on err"| t5["handle-credit-error"]:::task
    t5 --> t4
    t2 --> t4
    t3 --> t4
    t4 -->|"goto"| t6["request-more-info"]:::task
    t6 --> t4
    t4 --> t7["decision"]:::task
    t7 --> _end(( )):::term
