/*
Copyright (c) 2023-2025 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by Microbus. DO NOT EDIT.

package tester

const Version = 183
const SourceCodeSHA256 = "8eb0862202205c78c36bd3305dd7ca30f3910b01b58355c406585c71b2cdad14"
const Timestamp = "2025-11-02T17:28:50.04161Z"

/* {
	"ver": 183,
	"sha256": "8eb0862202205c78c36bd3305dd7ca30f3910b01b58355c406585c71b2cdad14",
	"ts": "2025-11-02T17:28:50.04161Z"
} */
