# Copyright (c) 2023-2024 Microbus LLC and various contributors
# 
# This file and the project encapsulating it are the confidential intellectual property of Microbus LLC.
# Neither may be used, copied or distributed without the express written consent of Microbus LLC.

apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true
    prometheusType: Prometheus
    prometheusVersion: 2.40.x