graph LR
    classDef task fill:#32a7c1,color:#f4f2ef,stroke:#32a7c1
    classDef term fill:#e5f4f3,color:#434343,stroke:#32a7c1
    classDef note fill:none,stroke:none,color:#32a7c1,font-size:0.8em
    linkStyle default stroke:#32a7c1

    _title{{"cancelled-fan-out"}}:::term -.-> _start
    t0["source"]:::task
    t1["a"]:::task
    t2["b"]:::task
    t3["c"]:::task
    t4["j"]:::task
    t4_reduce(("reduce")):::term
    t4_reduce --> t4
    t0 --> t1
    t0 --> t2
    t0 --> t3
    t1 --> t4_reduce
    t2 --> t4_reduce
    t3 --> t4_reduce
    _start(( )):::term --> t0
    t4 --> _end(( )):::term
