/*
Copyright (c) 2023-2026 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cmd/genmock. DO NOT EDIT.

package subgraphflow

import (
	"context"
	"testing"

	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/workflow"
	"github.com/microbus-io/testarossa"
)

func TestSubgraphflow_Mock(t *testing.T) {
	t.Parallel()
	ctx := t.Context()

	mock := NewMock()
	mock.SetDeployment(connector.TESTING)

	t.Run("on_startup", func(t *testing.T) {
		assert := testarossa.For(t)
		err := mock.OnStartup(ctx)
		assert.NoError(err)
	})

	t.Run("on_shutdown", func(t *testing.T) {
		assert := testarossa.For(t)
		err := mock.OnShutdown(ctx)
		assert.NoError(err)
	})

	t.Run("task_a", func(t *testing.T) { // MARKER: TaskA
		assert := testarossa.For(t)

		mock.MockTaskA(func(ctx context.Context, flow *workflow.Flow, seed string) (seedOut string, err error) {
			return
		})
		var seed string
		_, err := mock.TaskA(ctx, nil, seed)
		assert.NoError(err)
	})

	t.Run("task_x", func(t *testing.T) { // MARKER: TaskX
		assert := testarossa.For(t)

		mock.MockTaskX(func(ctx context.Context, flow *workflow.Flow, seed string) (innerStage string, err error) {
			return
		})
		var seed string
		_, err := mock.TaskX(ctx, nil, seed)
		assert.NoError(err)
	})

	t.Run("task_y", func(t *testing.T) { // MARKER: TaskY
		assert := testarossa.For(t)

		mock.MockTaskY(func(ctx context.Context, flow *workflow.Flow, innerStage string) (innerResult string, err error) {
			return
		})
		var innerStage string
		_, err := mock.TaskY(ctx, nil, innerStage)
		assert.NoError(err)
	})

	t.Run("task_z", func(t *testing.T) { // MARKER: TaskZ
		assert := testarossa.For(t)

		mock.MockTaskZ(func(ctx context.Context, flow *workflow.Flow, innerResult string) (finalResult string, err error) {
			return
		})
		var innerResult string
		_, err := mock.TaskZ(ctx, nil, innerResult)
		assert.NoError(err)
	})

	t.Run("inner", func(t *testing.T) { // MARKER: Inner
		assert := testarossa.For(t)

		mock.MockInner(func(ctx context.Context, flow *workflow.Flow, seed string) (innerResult string, err error) {
			return
		})
		graph, err := mock.Inner(ctx)
		if assert.NoError(err) {
			assert.NotNil(graph)
		}
	})

	t.Run("parent", func(t *testing.T) { // MARKER: Parent
		assert := testarossa.For(t)

		mock.MockParent(func(ctx context.Context, flow *workflow.Flow, seed string) (finalResult string, err error) {
			return
		})
		graph, err := mock.Parent(ctx)
		if assert.NoError(err) {
			assert.NotNil(graph)
		}
	})

}
