/*
Copyright (c) 2023-2026 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cmd/genmock. DO NOT EDIT.

package retryloopflow

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/fabric/sub"
	"github.com/microbus-io/fabric/utils"
	"github.com/microbus-io/fabric/workflow"

	"github.com/microbus-io/fabric/verify/retryloopflow/retryloopflowapi"
)

// Mock is a mockable version of the microservice, allowing functions, event sinks and web handlers to be mocked.
type Mock struct {
	*Intermediate
	mockTaskA          func(ctx context.Context, flow *workflow.Flow, target int) (targetOut int, err error)                                // MARKER: TaskA
	mockTaskB          func(ctx context.Context, flow *workflow.Flow, attempts int, target int) (succeeded bool, err error)                 // MARKER: TaskB
	mockHandler        func(ctx context.Context, flow *workflow.Flow, onErr *errors.TracedError, attempts int) (attemptsOut int, err error) // MARKER: Handler
	mockTaskC          func(ctx context.Context, flow *workflow.Flow, attempts int) (finalAttempts int, err error)                          // MARKER: TaskC
	mockRetryLoopGraph func(ctx context.Context) (graph *workflow.Graph, err error)                                                         // MARKER: RetryLoop
	unsubMockRetryLoop func() error                                                                                                         // MARKER: RetryLoop
}

// NewMock creates a new mockable version of the microservice.
func NewMock() *Mock {
	svc := &Mock{}
	svc.Intermediate = NewIntermediate(svc)
	svc.SetVersion(7357) // Stands for TEST
	return svc
}

// OnStartup is called when the microservice is started up.
func (svc *Mock) OnStartup(ctx context.Context) (err error) {
	if svc.Deployment() != connector.LOCAL && svc.Deployment() != connector.TESTING {
		return errors.New("mocking disallowed in %s deployment", svc.Deployment())
	}
	return nil
}

// OnShutdown is called when the microservice is shut down.
func (svc *Mock) OnShutdown(ctx context.Context) (err error) {
	return nil
}

// MockTaskA sets up a mock handler for TaskA.
func (svc *Mock) MockTaskA(handler func(ctx context.Context, flow *workflow.Flow, target int) (targetOut int, err error)) *Mock { // MARKER: TaskA
	svc.mockTaskA = handler
	return svc
}

// TaskA executes the mock handler.
func (svc *Mock) TaskA(ctx context.Context, flow *workflow.Flow, target int) (targetOut int, err error) { // MARKER: TaskA
	if svc.mockTaskA != nil {
		targetOut, err = svc.mockTaskA(ctx, flow, target)
	}
	return targetOut, errors.Trace(err)
}

// MockTaskB sets up a mock handler for TaskB.
func (svc *Mock) MockTaskB(handler func(ctx context.Context, flow *workflow.Flow, attempts int, target int) (succeeded bool, err error)) *Mock { // MARKER: TaskB
	svc.mockTaskB = handler
	return svc
}

// TaskB executes the mock handler.
func (svc *Mock) TaskB(ctx context.Context, flow *workflow.Flow, attempts int, target int) (succeeded bool, err error) { // MARKER: TaskB
	if svc.mockTaskB != nil {
		succeeded, err = svc.mockTaskB(ctx, flow, attempts, target)
	}
	return succeeded, errors.Trace(err)
}

// MockHandler sets up a mock handler for Handler.
func (svc *Mock) MockHandler(handler func(ctx context.Context, flow *workflow.Flow, onErr *errors.TracedError, attempts int) (attemptsOut int, err error)) *Mock { // MARKER: Handler
	svc.mockHandler = handler
	return svc
}

// Handler executes the mock handler.
func (svc *Mock) Handler(ctx context.Context, flow *workflow.Flow, onErr *errors.TracedError, attempts int) (attemptsOut int, err error) { // MARKER: Handler
	if svc.mockHandler != nil {
		attemptsOut, err = svc.mockHandler(ctx, flow, onErr, attempts)
	}
	return attemptsOut, errors.Trace(err)
}

// MockTaskC sets up a mock handler for TaskC.
func (svc *Mock) MockTaskC(handler func(ctx context.Context, flow *workflow.Flow, attempts int) (finalAttempts int, err error)) *Mock { // MARKER: TaskC
	svc.mockTaskC = handler
	return svc
}

// TaskC executes the mock handler.
func (svc *Mock) TaskC(ctx context.Context, flow *workflow.Flow, attempts int) (finalAttempts int, err error) { // MARKER: TaskC
	if svc.mockTaskC != nil {
		finalAttempts, err = svc.mockTaskC(ctx, flow, attempts)
	}
	return finalAttempts, errors.Trace(err)
}

// MockRetryLoop sets up a mock handler for the RetryLoop workflow.
// The handler receives typed inputs from the workflow's state and returns typed outputs.
// A nil handler clears the mock.
func (svc *Mock) MockRetryLoop(handler func(ctx context.Context, flow *workflow.Flow, target int) (finalAttempts int, err error)) *Mock { // MARKER: RetryLoop
	if svc.unsubMockRetryLoop != nil {
		svc.unsubMockRetryLoop()
		svc.unsubMockRetryLoop = nil
	}
	if handler == nil {
		svc.mockRetryLoopGraph = nil
		return svc
	}
	mockName := "MockRetryLoop" + utils.RandomIdentifier(8)
	mockRoute := ":428/mock-retry-loop-" + utils.RandomIdentifier(8)
	mockTaskURL := httpx.JoinHostAndPath(svc.Hostname(), mockRoute)
	svc.mockRetryLoopGraph = func(ctx context.Context) (graph *workflow.Graph, err error) {
		g := workflow.NewGraph(retryloopflowapi.RetryLoop.URL())
		g.AddTransition(mockTaskURL, workflow.END)
		return g, nil
	}
	err := svc.Subscribe(mockName, func(w http.ResponseWriter, r *http.Request) error {
		var f workflow.Flow
		if err := json.NewDecoder(r.Body).Decode(&f); err != nil {
			return errors.Trace(err)
		}
		snap := f.Snapshot()
		var in retryloopflowapi.RetryLoopIn
		f.ParseState(&in)
		finalAttempts, err := handler(r.Context(), &f, in.Target)
		if err != nil {
			return err // No trace
		}
		out := retryloopflowapi.RetryLoopOut{FinalAttempts: finalAttempts}
		f.SetChanges(out, snap)
		w.Header().Set("Content-Type", "application/json")
		return json.NewEncoder(w).Encode(&f)
	},
		sub.At("POST", mockRoute),
		sub.Task(retryloopflowapi.RetryLoopIn{}, retryloopflowapi.RetryLoopOut{}),
	)
	if err == nil {
		svc.unsubMockRetryLoop = func() error { return svc.Unsubscribe(mockName) }
	}
	return svc
}

// RetryLoop returns the workflow graph, or a mocked graph if MockRetryLoop was called.
func (svc *Mock) RetryLoop(ctx context.Context) (graph *workflow.Graph, err error) { // MARKER: RetryLoop
	if svc.mockRetryLoopGraph != nil {
		graph, err = svc.mockRetryLoopGraph(ctx)
	}
	return graph, errors.Trace(err)
}
