graph LR
    classDef task fill:#32a7c1,color:#f4f2ef,stroke:#434343
    classDef sub fill:#ed2e92,color:#f4f2ef,stroke:#434343
    classDef term fill:#e5f4f3,color:#434343,stroke:#434343

    _title{{"retry-loop"}}:::term --> _start
    _start(( )):::term --> t0["taskA"]:::task
    t0 --> t1["taskB"]:::task
    t1 -->|"onError"| t2["handler"]:::task
    t2 --> t1
    t1 --> t3["taskC"]:::task
    t3 --> _end(( )):::term
