// Code generated by cmd/genmock. DO NOT EDIT.

// Code generated by cmd/genservice. DO NOT EDIT.

package petstore

import (
	"context"
	"net/http"

	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/examples/petstore/petstoreapi"
)

// Mock is a mockable version of the microservice, allowing functions, event sinks and web handlers to be mocked.
type Mock struct {
	*Intermediate
	mockAddPet     func(ctx context.Context, httpRequestBody *petstoreapi.Pet) (httpResponseBody *petstoreapi.Pet, httpStatusCode int, err error) // MARKER: AddPet
	mockGetPetById func(ctx context.Context, petId int64) (httpResponseBody *petstoreapi.Pet, httpStatusCode int, err error)                      // MARKER: GetPetById
	mockUploadFile func(w http.ResponseWriter, r *http.Request) (err error)                                                                       // MARKER: UploadFile
}

// NewMock creates a new mockable version of the microservice.
func NewMock() *Mock {
	svc := &Mock{}
	svc.Intermediate = NewIntermediate(svc)
	svc.SetVersion(7357) // Stands for TEST
	return svc
}

// OnStartup is called when the microservice is started up.
func (svc *Mock) OnStartup(ctx context.Context) (err error) {
	if svc.Deployment() != connector.LOCAL && svc.Deployment() != connector.TESTING {
		return errors.New("mocking disallowed in %s deployment", svc.Deployment())
	}
	return nil
}

// OnShutdown is called when the microservice is shut down.
func (svc *Mock) OnShutdown(ctx context.Context) (err error) {
	return nil
}

// MockAddPet sets up a mock handler for AddPet.
func (svc *Mock) MockAddPet(handler func(ctx context.Context, httpRequestBody *petstoreapi.Pet) (httpResponseBody *petstoreapi.Pet, httpStatusCode int, err error)) *Mock { // MARKER: AddPet
	svc.mockAddPet = handler
	return svc
}

// AddPet executes the mock handler.
func (svc *Mock) AddPet(ctx context.Context, httpRequestBody *petstoreapi.Pet) (httpResponseBody *petstoreapi.Pet, httpStatusCode int, err error) { // MARKER: AddPet
	if svc.mockAddPet != nil {
		httpResponseBody, httpStatusCode, err = svc.mockAddPet(ctx, httpRequestBody)
	}
	return httpResponseBody, httpStatusCode, errors.Trace(err)
}

// MockGetPetById sets up a mock handler for GetPetById.
func (svc *Mock) MockGetPetById(handler func(ctx context.Context, petId int64) (httpResponseBody *petstoreapi.Pet, httpStatusCode int, err error)) *Mock { // MARKER: GetPetById
	svc.mockGetPetById = handler
	return svc
}

// GetPetById executes the mock handler.
func (svc *Mock) GetPetById(ctx context.Context, petId int64) (httpResponseBody *petstoreapi.Pet, httpStatusCode int, err error) { // MARKER: GetPetById
	if svc.mockGetPetById != nil {
		httpResponseBody, httpStatusCode, err = svc.mockGetPetById(ctx, petId)
	}
	return httpResponseBody, httpStatusCode, errors.Trace(err)
}

// MockUploadFile sets up a mock handler for UploadFile.
func (svc *Mock) MockUploadFile(handler func(w http.ResponseWriter, r *http.Request) (err error)) *Mock { // MARKER: UploadFile
	svc.mockUploadFile = handler
	return svc
}

// UploadFile executes the mock handler.
func (svc *Mock) UploadFile(w http.ResponseWriter, r *http.Request) (err error) { // MARKER: UploadFile
	if svc.mockUploadFile != nil {
		err = svc.mockUploadFile(w, r)
	}
	return errors.Trace(err)
}
