// Code generated by cmd/genservice. DO NOT EDIT.

package weird

import (
	"context"

	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/connector"
)

// Mock is a mockable version of the microservice, allowing functions, event sinks and web handlers to be mocked.
type Mock struct {
	*Intermediate
	mockPlain            func(ctx context.Context) (result string, err error) // MARKER: Plain
	mockPathArg          func(ctx context.Context, id string) (err error)     // MARKER: PathArg
	mockGreedyArg        func(ctx context.Context, tail string) (err error)   // MARKER: GreedyArg
	mockPeriodInPath     func(ctx context.Context) (err error)                // MARKER: PeriodInPath
	mockAnyMethod        func(ctx context.Context) (err error)                // MARKER: AnyMethod
	mockInternalPort     func(ctx context.Context) (err error)                // MARKER: InternalPort
	mockTrustRoot        func(ctx context.Context, cmd string) (err error)    // MARKER: TrustRoot
	mockSlashHostRoot    func(ctx context.Context) (err error)                // MARKER: SlashHostRoot
	mockSlashHostPort    func(ctx context.Context) (err error)                // MARKER: SlashHostPort
	mockSlashHostPathArg func(ctx context.Context, id string) (err error)     // MARKER: SlashHostPathArg
	mockSpecialHostRoute func(ctx context.Context) (err error)                // MARKER: SpecialHostRoute
	mockUpperCasePath    func(ctx context.Context) (err error)                // MARKER: UpperCasePath
}

// NewMock creates a new mockable version of the microservice.
func NewMock() *Mock {
	svc := &Mock{}
	svc.Intermediate = NewIntermediate(svc)
	svc.SetVersion(7357) // Stands for TEST
	return svc
}

// OnStartup is called when the microservice is started up.
func (svc *Mock) OnStartup(ctx context.Context) (err error) {
	if svc.Deployment() != connector.LOCAL && svc.Deployment() != connector.TESTING {
		return errors.New("mocking disallowed in %s deployment", svc.Deployment())
	}
	return nil
}

// OnShutdown is called when the microservice is shut down.
func (svc *Mock) OnShutdown(ctx context.Context) (err error) {
	return nil
}

// MockPlain sets up a mock handler for Plain.
func (svc *Mock) MockPlain(handler func(ctx context.Context) (result string, err error)) *Mock { // MARKER: Plain
	svc.mockPlain = handler
	return svc
}

// Plain executes the mock handler.
func (svc *Mock) Plain(ctx context.Context) (result string, err error) { // MARKER: Plain
	if svc.mockPlain != nil {
		result, err = svc.mockPlain(ctx)
	}
	return result, errors.Trace(err)
}

// MockPathArg sets up a mock handler for PathArg.
func (svc *Mock) MockPathArg(handler func(ctx context.Context, id string) (err error)) *Mock { // MARKER: PathArg
	svc.mockPathArg = handler
	return svc
}

// PathArg executes the mock handler.
func (svc *Mock) PathArg(ctx context.Context, id string) (err error) { // MARKER: PathArg
	if svc.mockPathArg != nil {
		err = svc.mockPathArg(ctx, id)
	}
	return errors.Trace(err)
}

// MockGreedyArg sets up a mock handler for GreedyArg.
func (svc *Mock) MockGreedyArg(handler func(ctx context.Context, tail string) (err error)) *Mock { // MARKER: GreedyArg
	svc.mockGreedyArg = handler
	return svc
}

// GreedyArg executes the mock handler.
func (svc *Mock) GreedyArg(ctx context.Context, tail string) (err error) { // MARKER: GreedyArg
	if svc.mockGreedyArg != nil {
		err = svc.mockGreedyArg(ctx, tail)
	}
	return errors.Trace(err)
}

// MockPeriodInPath sets up a mock handler for PeriodInPath.
func (svc *Mock) MockPeriodInPath(handler func(ctx context.Context) (err error)) *Mock { // MARKER: PeriodInPath
	svc.mockPeriodInPath = handler
	return svc
}

// PeriodInPath executes the mock handler.
func (svc *Mock) PeriodInPath(ctx context.Context) (err error) { // MARKER: PeriodInPath
	if svc.mockPeriodInPath != nil {
		err = svc.mockPeriodInPath(ctx)
	}
	return errors.Trace(err)
}

// MockAnyMethod sets up a mock handler for AnyMethod.
func (svc *Mock) MockAnyMethod(handler func(ctx context.Context) (err error)) *Mock { // MARKER: AnyMethod
	svc.mockAnyMethod = handler
	return svc
}

// AnyMethod executes the mock handler.
func (svc *Mock) AnyMethod(ctx context.Context) (err error) { // MARKER: AnyMethod
	if svc.mockAnyMethod != nil {
		err = svc.mockAnyMethod(ctx)
	}
	return errors.Trace(err)
}

// MockInternalPort sets up a mock handler for InternalPort.
func (svc *Mock) MockInternalPort(handler func(ctx context.Context) (err error)) *Mock { // MARKER: InternalPort
	svc.mockInternalPort = handler
	return svc
}

// InternalPort executes the mock handler.
func (svc *Mock) InternalPort(ctx context.Context) (err error) { // MARKER: InternalPort
	if svc.mockInternalPort != nil {
		err = svc.mockInternalPort(ctx)
	}
	return errors.Trace(err)
}

// MockTrustRoot sets up a mock handler for TrustRoot.
func (svc *Mock) MockTrustRoot(handler func(ctx context.Context, cmd string) (err error)) *Mock { // MARKER: TrustRoot
	svc.mockTrustRoot = handler
	return svc
}

// TrustRoot executes the mock handler.
func (svc *Mock) TrustRoot(ctx context.Context, cmd string) (err error) { // MARKER: TrustRoot
	if svc.mockTrustRoot != nil {
		err = svc.mockTrustRoot(ctx, cmd)
	}
	return errors.Trace(err)
}

// MockSlashHostRoot sets up a mock handler for SlashHostRoot.
func (svc *Mock) MockSlashHostRoot(handler func(ctx context.Context) (err error)) *Mock { // MARKER: SlashHostRoot
	svc.mockSlashHostRoot = handler
	return svc
}

// SlashHostRoot executes the mock handler.
func (svc *Mock) SlashHostRoot(ctx context.Context) (err error) { // MARKER: SlashHostRoot
	if svc.mockSlashHostRoot != nil {
		err = svc.mockSlashHostRoot(ctx)
	}
	return errors.Trace(err)
}

// MockSlashHostPort sets up a mock handler for SlashHostPort.
func (svc *Mock) MockSlashHostPort(handler func(ctx context.Context) (err error)) *Mock { // MARKER: SlashHostPort
	svc.mockSlashHostPort = handler
	return svc
}

// SlashHostPort executes the mock handler.
func (svc *Mock) SlashHostPort(ctx context.Context) (err error) { // MARKER: SlashHostPort
	if svc.mockSlashHostPort != nil {
		err = svc.mockSlashHostPort(ctx)
	}
	return errors.Trace(err)
}

// MockSlashHostPathArg sets up a mock handler for SlashHostPathArg.
func (svc *Mock) MockSlashHostPathArg(handler func(ctx context.Context, id string) (err error)) *Mock { // MARKER: SlashHostPathArg
	svc.mockSlashHostPathArg = handler
	return svc
}

// SlashHostPathArg executes the mock handler.
func (svc *Mock) SlashHostPathArg(ctx context.Context, id string) (err error) { // MARKER: SlashHostPathArg
	if svc.mockSlashHostPathArg != nil {
		err = svc.mockSlashHostPathArg(ctx, id)
	}
	return errors.Trace(err)
}

// MockSpecialHostRoute sets up a mock handler for SpecialHostRoute.
func (svc *Mock) MockSpecialHostRoute(handler func(ctx context.Context) (err error)) *Mock { // MARKER: SpecialHostRoute
	svc.mockSpecialHostRoute = handler
	return svc
}

// SpecialHostRoute executes the mock handler.
func (svc *Mock) SpecialHostRoute(ctx context.Context) (err error) { // MARKER: SpecialHostRoute
	if svc.mockSpecialHostRoute != nil {
		err = svc.mockSpecialHostRoute(ctx)
	}
	return errors.Trace(err)
}

// MockUpperCasePath sets up a mock handler for UpperCasePath.
func (svc *Mock) MockUpperCasePath(handler func(ctx context.Context) (err error)) *Mock { // MARKER: UpperCasePath
	svc.mockUpperCasePath = handler
	return svc
}

// UpperCasePath executes the mock handler.
func (svc *Mock) UpperCasePath(ctx context.Context) (err error) { // MARKER: UpperCasePath
	if svc.mockUpperCasePath != nil {
		err = svc.mockUpperCasePath(ctx)
	}
	return errors.Trace(err)
}
