// Code generated by cmd/genservice. DO NOT EDIT.

package weird

import (
	"context"
	"testing"

	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/testarossa"
)

func TestWeird_Mock(t *testing.T) {
	t.Parallel()
	ctx := t.Context()

	mock := NewMock()
	mock.SetDeployment(connector.TESTING)

	t.Run("on_startup", func(t *testing.T) {
		assert := testarossa.For(t)
		err := mock.OnStartup(ctx)
		assert.NoError(err)
	})

	t.Run("on_shutdown", func(t *testing.T) {
		assert := testarossa.For(t)
		err := mock.OnShutdown(ctx)
		assert.NoError(err)
	})

	t.Run("plain", func(t *testing.T) { // MARKER: Plain
		assert := testarossa.For(t)

		mock.MockPlain(func(ctx context.Context) (result string, err error) {
			return
		})
		_, err := mock.Plain(ctx)
		assert.NoError(err)
	})

	t.Run("path_arg", func(t *testing.T) { // MARKER: PathArg
		assert := testarossa.For(t)

		mock.MockPathArg(func(ctx context.Context, id string) (err error) {
			return
		})
		var id string
		err := mock.PathArg(ctx, id)
		assert.NoError(err)
	})

	t.Run("greedy_arg", func(t *testing.T) { // MARKER: GreedyArg
		assert := testarossa.For(t)

		mock.MockGreedyArg(func(ctx context.Context, tail string) (err error) {
			return
		})
		var tail string
		err := mock.GreedyArg(ctx, tail)
		assert.NoError(err)
	})

	t.Run("period_in_path", func(t *testing.T) { // MARKER: PeriodInPath
		assert := testarossa.For(t)

		mock.MockPeriodInPath(func(ctx context.Context) (err error) {
			return
		})
		err := mock.PeriodInPath(ctx)
		assert.NoError(err)
	})

	t.Run("any_method", func(t *testing.T) { // MARKER: AnyMethod
		assert := testarossa.For(t)

		mock.MockAnyMethod(func(ctx context.Context) (err error) {
			return
		})
		err := mock.AnyMethod(ctx)
		assert.NoError(err)
	})

	t.Run("internal_port", func(t *testing.T) { // MARKER: InternalPort
		assert := testarossa.For(t)

		mock.MockInternalPort(func(ctx context.Context) (err error) {
			return
		})
		err := mock.InternalPort(ctx)
		assert.NoError(err)
	})

	t.Run("trust_root", func(t *testing.T) { // MARKER: TrustRoot
		assert := testarossa.For(t)

		mock.MockTrustRoot(func(ctx context.Context, cmd string) (err error) {
			return
		})
		var cmd string
		err := mock.TrustRoot(ctx, cmd)
		assert.NoError(err)
	})

	t.Run("slash_host_root", func(t *testing.T) { // MARKER: SlashHostRoot
		assert := testarossa.For(t)

		mock.MockSlashHostRoot(func(ctx context.Context) (err error) {
			return
		})
		err := mock.SlashHostRoot(ctx)
		assert.NoError(err)
	})

	t.Run("slash_host_port", func(t *testing.T) { // MARKER: SlashHostPort
		assert := testarossa.For(t)

		mock.MockSlashHostPort(func(ctx context.Context) (err error) {
			return
		})
		err := mock.SlashHostPort(ctx)
		assert.NoError(err)
	})

	t.Run("slash_host_path_arg", func(t *testing.T) { // MARKER: SlashHostPathArg
		assert := testarossa.For(t)

		mock.MockSlashHostPathArg(func(ctx context.Context, id string) (err error) {
			return
		})
		var id string
		err := mock.SlashHostPathArg(ctx, id)
		assert.NoError(err)
	})

	t.Run("special_host_route", func(t *testing.T) { // MARKER: SpecialHostRoute
		assert := testarossa.For(t)

		mock.MockSpecialHostRoute(func(ctx context.Context) (err error) {
			return
		})
		err := mock.SpecialHostRoute(ctx)
		assert.NoError(err)
	})

	t.Run("upper_case_path", func(t *testing.T) { // MARKER: UpperCasePath
		assert := testarossa.For(t)

		mock.MockUpperCasePath(func(ctx context.Context) (err error) {
			return
		})
		err := mock.UpperCasePath(ctx)
		assert.NoError(err)
	})

}
