// Code generated by cmd/genmock. DO NOT EDIT.

package distributedbackpressureflow

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/fabric/sub"
	"github.com/microbus-io/fabric/utils"
	"github.com/microbus-io/fabric/workflow"

	"github.com/microbus-io/fabric/verify/distributedbackpressureflow/distributedbackpressureflowapi"
)

// Mock is a mockable version of the microservice, allowing functions, event sinks and web handlers to be mocked.
type Mock struct {
	*Intermediate
	mockBounded                      func(ctx context.Context, flow *workflow.Flow, tag string) (tallied bool, err error) // MARKER: Bounded
	mockDistributedBackpressureGraph func(ctx context.Context) (graph *workflow.Graph, err error)                         // MARKER: DistributedBackpressure
	unsubMockDistributedBackpressure func() error                                                                         // MARKER: DistributedBackpressure
}

// NewMock creates a new mockable version of the microservice.
func NewMock() *Mock {
	svc := &Mock{}
	svc.Intermediate = NewIntermediate(svc)
	svc.SetVersion(7357) // Stands for TEST
	return svc
}

// OnStartup is called when the microservice is started up.
func (svc *Mock) OnStartup(ctx context.Context) (err error) {
	if svc.Deployment() != connector.LOCAL && svc.Deployment() != connector.TESTING {
		return errors.New("mocking disallowed in %s deployment", svc.Deployment())
	}
	return nil
}

// OnShutdown is called when the microservice is shut down.
func (svc *Mock) OnShutdown(ctx context.Context) (err error) {
	return nil
}

// MockBounded sets up a mock handler for Bounded.
func (svc *Mock) MockBounded(handler func(ctx context.Context, flow *workflow.Flow, tag string) (tallied bool, err error)) *Mock { // MARKER: Bounded
	svc.mockBounded = handler
	return svc
}

// Bounded executes the mock handler.
func (svc *Mock) Bounded(ctx context.Context, flow *workflow.Flow, tag string) (tallied bool, err error) { // MARKER: Bounded
	if svc.mockBounded != nil {
		tallied, err = svc.mockBounded(ctx, flow, tag)
	}
	return tallied, errors.Trace(err)
}

// MockDistributedBackpressure sets up a mock handler for the DistributedBackpressure workflow.
// The handler receives typed inputs from the workflow's state and returns typed outputs.
// A nil handler clears the mock.
func (svc *Mock) MockDistributedBackpressure(handler func(ctx context.Context, flow *workflow.Flow, tag string) (tallied bool, err error)) *Mock { // MARKER: DistributedBackpressure
	if svc.unsubMockDistributedBackpressure != nil {
		svc.unsubMockDistributedBackpressure()
		svc.unsubMockDistributedBackpressure = nil
	}
	if handler == nil {
		svc.mockDistributedBackpressureGraph = nil
		return svc
	}
	mockName := "MockDistributedBackpressure" + utils.RandomIdentifier(8)
	mockRoute := ":428/mock-distributed-backpressure-" + utils.RandomIdentifier(8)
	mockTaskURL := httpx.JoinHostAndPath(svc.Hostname(), mockRoute)
	svc.mockDistributedBackpressureGraph = func(ctx context.Context) (graph *workflow.Graph, err error) {
		g := workflow.NewGraph(distributedbackpressureflowapi.DistributedBackpressure.URL())
		g.AddTransition(mockTaskURL, workflow.END)
		g.DeclareInputs("*")
		g.DeclareOutputs("*")
		return g, nil
	}
	err := svc.Subscribe(mockName, func(w http.ResponseWriter, r *http.Request) error {
		var f workflow.Flow
		if err := json.NewDecoder(r.Body).Decode(&f); err != nil {
			return errors.Trace(err)
		}
		snap := f.Snapshot()
		var in distributedbackpressureflowapi.DistributedBackpressureIn
		f.ParseState(&in)
		tallied, err := handler(r.Context(), &f, in.Tag)
		if err != nil {
			return err // No trace
		}
		out := distributedbackpressureflowapi.DistributedBackpressureOut{Tallied: tallied}
		f.SetChanges(out, snap)
		w.Header().Set("Content-Type", "application/json")
		return json.NewEncoder(w).Encode(&f)
	},
		sub.At("POST", mockRoute),
		sub.Task(distributedbackpressureflowapi.DistributedBackpressureIn{}, distributedbackpressureflowapi.DistributedBackpressureOut{}),
	)
	if err == nil {
		svc.unsubMockDistributedBackpressure = func() error { return svc.Unsubscribe(mockName) }
	}
	return svc
}

// DistributedBackpressure returns the workflow graph, or a mocked graph if MockDistributedBackpressure was called.
func (svc *Mock) DistributedBackpressure(ctx context.Context) (graph *workflow.Graph, err error) { // MARKER: DistributedBackpressure
	if svc.mockDistributedBackpressureGraph != nil {
		graph, err = svc.mockDistributedBackpressureGraph(ctx)
	}
	return graph, errors.Trace(err)
}
