/*
Copyright (c) 2023-2026 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cmd/genmock. DO NOT EDIT.

package priorityflow

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/fabric/sub"
	"github.com/microbus-io/fabric/utils"
	"github.com/microbus-io/fabric/workflow"

	"github.com/microbus-io/fabric/verify/priorityflow/priorityflowapi"
)

// Mock is a mockable version of the microservice, allowing functions, event sinks and web handlers to be mocked.
type Mock struct {
	*Intermediate
	mockRecord        func(ctx context.Context, flow *workflow.Flow) (recorded bool, err error) // MARKER: Record
	mockPriorityGraph func(ctx context.Context) (graph *workflow.Graph, err error)              // MARKER: Priority
	unsubMockPriority func() error                                                              // MARKER: Priority
}

// NewMock creates a new mockable version of the microservice.
func NewMock() *Mock {
	svc := &Mock{}
	svc.Intermediate = NewIntermediate(svc)
	svc.SetVersion(7357) // Stands for TEST
	return svc
}

// OnStartup is called when the microservice is started up.
func (svc *Mock) OnStartup(ctx context.Context) (err error) {
	if svc.Deployment() != connector.LOCAL && svc.Deployment() != connector.TESTING {
		return errors.New("mocking disallowed in %s deployment", svc.Deployment())
	}
	return nil
}

// OnShutdown is called when the microservice is shut down.
func (svc *Mock) OnShutdown(ctx context.Context) (err error) {
	return nil
}

// MockRecord sets up a mock handler for Record.
func (svc *Mock) MockRecord(handler func(ctx context.Context, flow *workflow.Flow) (recorded bool, err error)) *Mock { // MARKER: Record
	svc.mockRecord = handler
	return svc
}

// Record executes the mock handler.
func (svc *Mock) Record(ctx context.Context, flow *workflow.Flow) (recorded bool, err error) { // MARKER: Record
	if svc.mockRecord != nil {
		recorded, err = svc.mockRecord(ctx, flow)
	}
	return recorded, errors.Trace(err)
}

// MockPriority sets up a mock handler for the Priority workflow.
// The handler receives typed inputs from the workflow's state and returns typed outputs.
// A nil handler clears the mock.
func (svc *Mock) MockPriority(handler func(ctx context.Context, flow *workflow.Flow, tag string, delayMs int) (recorded bool, err error)) *Mock { // MARKER: Priority
	if svc.unsubMockPriority != nil {
		svc.unsubMockPriority()
		svc.unsubMockPriority = nil
	}
	if handler == nil {
		svc.mockPriorityGraph = nil
		return svc
	}
	mockName := "MockPriority" + utils.RandomIdentifier(8)
	mockRoute := ":428/mock-priority-" + utils.RandomIdentifier(8)
	mockTaskURL := httpx.JoinHostAndPath(svc.Hostname(), mockRoute)
	svc.mockPriorityGraph = func(ctx context.Context) (graph *workflow.Graph, err error) {
		g := workflow.NewGraph(priorityflowapi.Priority.URL())
		g.AddTransition(mockTaskURL, workflow.END)
		g.DeclareInputs("*")
		g.DeclareOutputs("*")
		return g, nil
	}
	err := svc.Subscribe(mockName, func(w http.ResponseWriter, r *http.Request) error {
		var f workflow.Flow
		if err := json.NewDecoder(r.Body).Decode(&f); err != nil {
			return errors.Trace(err)
		}
		snap := f.Snapshot()
		var in priorityflowapi.PriorityIn
		f.ParseState(&in)
		recorded, err := handler(r.Context(), &f, in.Tag, in.DelayMs)
		if err != nil {
			return err // No trace
		}
		out := priorityflowapi.PriorityOut{Recorded: recorded}
		f.SetChanges(out, snap)
		w.Header().Set("Content-Type", "application/json")
		return json.NewEncoder(w).Encode(&f)
	},
		sub.At("POST", mockRoute),
		sub.Task(priorityflowapi.PriorityIn{}, priorityflowapi.PriorityOut{}),
	)
	if err == nil {
		svc.unsubMockPriority = func() error { return svc.Unsubscribe(mockName) }
	}
	return svc
}

// Priority returns the workflow graph, or a mocked graph if MockPriority was called.
func (svc *Mock) Priority(ctx context.Context) (graph *workflow.Graph, err error) { // MARKER: Priority
	if svc.mockPriorityGraph != nil {
		graph, err = svc.mockPriorityGraph(ctx)
	}
	return graph, errors.Trace(err)
}
