// Code generated by cmd/genservice. DO NOT EDIT.

package flightbooking

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/microbus-io/dwarf/workflow"
	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/exampleservices/flightbooking/flightbookingapi"
	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/fabric/sub"
	"github.com/microbus-io/fabric/utils"
)

// Mock is a mockable version of the microservice, allowing functions, event sinks and web handlers to be mocked.
type Mock struct {
	*Intermediate
	mockDemo                 func(w http.ResponseWriter, r *http.Request) (err error)                                                                                                                 // MARKER: Demo
	mockSearchFlights        func(ctx context.Context, flow *workflow.Flow, origin string, destination string) (candidates []flightbookingapi.Flight, flightIndex int, err error)                     // MARKER: SearchFlights
	mockProposeFlight        func(ctx context.Context, flow *workflow.Flow, candidates []flightbookingapi.Flight, flightIndex int) (currentFlight flightbookingapi.Flight, exhausted bool, err error) // MARKER: ProposeFlight
	mockAwaitDecision        func(ctx context.Context, flow *workflow.Flow, currentFlight flightbookingapi.Flight, flightIndex int) (accepted bool, flightIndexOut int, err error)                    // MARKER: AwaitDecision
	mockChooseSeat           func(ctx context.Context, flow *workflow.Flow, seatPreference string, currentFlight flightbookingapi.Flight) (seat string, err error)                                    // MARKER: ChooseSeat
	mockConfirmBooking       func(ctx context.Context, flow *workflow.Flow, currentFlight flightbookingapi.Flight, seat string) (confirmation string, airline string, flightNo string, err error)     // MARKER: ConfirmBooking
	mockNoFlights            func(ctx context.Context, flow *workflow.Flow) (confirmation string, err error)                                                                                          // MARKER: NoFlights
	mockPickSeat             func(ctx context.Context, flow *workflow.Flow, seatPreference string, availableSeats []string) (seat string, err error)                                                  // MARKER: PickSeat
	mockBookFlightGraph      func(ctx context.Context) (graph *workflow.Graph, err error)                                                                                                             // MARKER: BookFlight
	unsubMockBookFlight      func() error                                                                                                                                                             // MARKER: BookFlight
	mockChooseSeatAgentGraph func(ctx context.Context) (graph *workflow.Graph, err error)                                                                                                             // MARKER: ChooseSeatAgent
	unsubMockChooseSeatAgent func() error                                                                                                                                                             // MARKER: ChooseSeatAgent
}

// NewMock creates a new mockable version of the microservice.
func NewMock() *Mock {
	svc := &Mock{}
	svc.Intermediate = NewIntermediate(svc)
	svc.SetVersion(7357) // Stands for TEST
	return svc
}

// OnStartup is called when the microservice is started up.
func (svc *Mock) OnStartup(ctx context.Context) (err error) {
	if svc.Deployment() != connector.LOCAL && svc.Deployment() != connector.TESTING {
		return errors.New("mocking disallowed in %s deployment", svc.Deployment())
	}
	return nil
}

// OnShutdown is called when the microservice is shut down.
func (svc *Mock) OnShutdown(ctx context.Context) (err error) {
	return nil
}

// MockDemo sets up a mock handler for Demo.
func (svc *Mock) MockDemo(handler func(w http.ResponseWriter, r *http.Request) (err error)) *Mock { // MARKER: Demo
	svc.mockDemo = handler
	return svc
}

// Demo executes the mock handler.
func (svc *Mock) Demo(w http.ResponseWriter, r *http.Request) (err error) { // MARKER: Demo
	if svc.mockDemo != nil {
		err = svc.mockDemo(w, r)
	}
	return errors.Trace(err)
}

// MockSearchFlights sets up a mock handler for SearchFlights.
func (svc *Mock) MockSearchFlights(handler func(ctx context.Context, flow *workflow.Flow, origin string, destination string) (candidates []flightbookingapi.Flight, flightIndex int, err error)) *Mock { // MARKER: SearchFlights
	svc.mockSearchFlights = handler
	return svc
}

// SearchFlights executes the mock handler.
func (svc *Mock) SearchFlights(ctx context.Context, flow *workflow.Flow, origin string, destination string) (candidates []flightbookingapi.Flight, flightIndex int, err error) { // MARKER: SearchFlights
	if svc.mockSearchFlights != nil {
		candidates, flightIndex, err = svc.mockSearchFlights(ctx, flow, origin, destination)
	}
	return candidates, flightIndex, errors.Trace(err)
}

// MockProposeFlight sets up a mock handler for ProposeFlight.
func (svc *Mock) MockProposeFlight(handler func(ctx context.Context, flow *workflow.Flow, candidates []flightbookingapi.Flight, flightIndex int) (currentFlight flightbookingapi.Flight, exhausted bool, err error)) *Mock { // MARKER: ProposeFlight
	svc.mockProposeFlight = handler
	return svc
}

// ProposeFlight executes the mock handler.
func (svc *Mock) ProposeFlight(ctx context.Context, flow *workflow.Flow, candidates []flightbookingapi.Flight, flightIndex int) (currentFlight flightbookingapi.Flight, exhausted bool, err error) { // MARKER: ProposeFlight
	if svc.mockProposeFlight != nil {
		currentFlight, exhausted, err = svc.mockProposeFlight(ctx, flow, candidates, flightIndex)
	}
	return currentFlight, exhausted, errors.Trace(err)
}

// MockAwaitDecision sets up a mock handler for AwaitDecision.
func (svc *Mock) MockAwaitDecision(handler func(ctx context.Context, flow *workflow.Flow, currentFlight flightbookingapi.Flight, flightIndex int) (accepted bool, flightIndexOut int, err error)) *Mock { // MARKER: AwaitDecision
	svc.mockAwaitDecision = handler
	return svc
}

// AwaitDecision executes the mock handler.
func (svc *Mock) AwaitDecision(ctx context.Context, flow *workflow.Flow, currentFlight flightbookingapi.Flight, flightIndex int) (accepted bool, flightIndexOut int, err error) { // MARKER: AwaitDecision
	if svc.mockAwaitDecision != nil {
		accepted, flightIndexOut, err = svc.mockAwaitDecision(ctx, flow, currentFlight, flightIndex)
	}
	return accepted, flightIndexOut, errors.Trace(err)
}

// MockChooseSeat sets up a mock handler for ChooseSeat.
func (svc *Mock) MockChooseSeat(handler func(ctx context.Context, flow *workflow.Flow, seatPreference string, currentFlight flightbookingapi.Flight) (seat string, err error)) *Mock { // MARKER: ChooseSeat
	svc.mockChooseSeat = handler
	return svc
}

// ChooseSeat executes the mock handler.
func (svc *Mock) ChooseSeat(ctx context.Context, flow *workflow.Flow, seatPreference string, currentFlight flightbookingapi.Flight) (seat string, err error) { // MARKER: ChooseSeat
	if svc.mockChooseSeat != nil {
		seat, err = svc.mockChooseSeat(ctx, flow, seatPreference, currentFlight)
	}
	return seat, errors.Trace(err)
}

// MockConfirmBooking sets up a mock handler for ConfirmBooking.
func (svc *Mock) MockConfirmBooking(handler func(ctx context.Context, flow *workflow.Flow, currentFlight flightbookingapi.Flight, seat string) (confirmation string, airline string, flightNo string, err error)) *Mock { // MARKER: ConfirmBooking
	svc.mockConfirmBooking = handler
	return svc
}

// ConfirmBooking executes the mock handler.
func (svc *Mock) ConfirmBooking(ctx context.Context, flow *workflow.Flow, currentFlight flightbookingapi.Flight, seat string) (confirmation string, airline string, flightNo string, err error) { // MARKER: ConfirmBooking
	if svc.mockConfirmBooking != nil {
		confirmation, airline, flightNo, err = svc.mockConfirmBooking(ctx, flow, currentFlight, seat)
	}
	return confirmation, airline, flightNo, errors.Trace(err)
}

// MockNoFlights sets up a mock handler for NoFlights.
func (svc *Mock) MockNoFlights(handler func(ctx context.Context, flow *workflow.Flow) (confirmation string, err error)) *Mock { // MARKER: NoFlights
	svc.mockNoFlights = handler
	return svc
}

// NoFlights executes the mock handler.
func (svc *Mock) NoFlights(ctx context.Context, flow *workflow.Flow) (confirmation string, err error) { // MARKER: NoFlights
	if svc.mockNoFlights != nil {
		confirmation, err = svc.mockNoFlights(ctx, flow)
	}
	return confirmation, errors.Trace(err)
}

// MockPickSeat sets up a mock handler for PickSeat.
func (svc *Mock) MockPickSeat(handler func(ctx context.Context, flow *workflow.Flow, seatPreference string, availableSeats []string) (seat string, err error)) *Mock { // MARKER: PickSeat
	svc.mockPickSeat = handler
	return svc
}

// PickSeat executes the mock handler.
func (svc *Mock) PickSeat(ctx context.Context, flow *workflow.Flow, seatPreference string, availableSeats []string) (seat string, err error) { // MARKER: PickSeat
	if svc.mockPickSeat != nil {
		seat, err = svc.mockPickSeat(ctx, flow, seatPreference, availableSeats)
	}
	return seat, errors.Trace(err)
}

// MockBookFlight sets up a mock handler for the BookFlight workflow.
// The handler receives typed inputs from the workflow's state and returns typed outputs.
// A nil handler clears the mock.
func (svc *Mock) MockBookFlight(handler func(ctx context.Context, flow *workflow.Flow, origin string, destination string, seatPreference string) (confirmation string, airline string, flightNo string, seat string, err error)) *Mock { // MARKER: BookFlight
	if svc.unsubMockBookFlight != nil {
		svc.unsubMockBookFlight()
		svc.unsubMockBookFlight = nil
	}
	if handler == nil {
		svc.mockBookFlightGraph = nil
		return svc
	}
	mockName := "MockBookFlight" + utils.RandomIdentifier(8)
	mockRoute := ":428/mock-book-flight-" + utils.RandomIdentifier(8)
	mockTaskURL := httpx.JoinHostAndPath(svc.Hostname(), mockRoute)
	svc.mockBookFlightGraph = func(ctx context.Context) (graph *workflow.Graph, err error) {
		g := workflow.NewGraph("BookFlight")
		g.AddTransition(mockTaskURL, workflow.END)
		return g, nil
	}
	err := svc.Subscribe(mockName, func(w http.ResponseWriter, r *http.Request) error {
		var f workflow.Flow
		if err := json.NewDecoder(r.Body).Decode(&f); err != nil {
			return errors.Trace(err)
		}
		snap := f.Snapshot()
		var in flightbookingapi.BookFlightIn
		f.ParseState(&in)
		confirmation, airline, flightNo, seat, err := handler(r.Context(), &f, in.Origin, in.Destination, in.SeatPreference)
		if err != nil {
			return err // No trace
		}
		out := flightbookingapi.BookFlightOut{Confirmation: confirmation, Airline: airline, FlightNo: flightNo, Seat: seat}
		f.SetChanges(out, snap)
		w.Header().Set("Content-Type", "application/json")
		return json.NewEncoder(w).Encode(&f)
	},
		sub.At("POST", mockRoute),
		sub.Task(flightbookingapi.BookFlightIn{}, flightbookingapi.BookFlightOut{}),
	)
	if err == nil {
		svc.unsubMockBookFlight = func() error { return svc.Unsubscribe(mockName) }
	}
	return svc
}

// BookFlight returns the workflow graph, or a mocked graph if MockBookFlight was called.
func (svc *Mock) BookFlight(ctx context.Context) (graph *workflow.Graph, err error) { // MARKER: BookFlight
	if svc.mockBookFlightGraph != nil {
		graph, err = svc.mockBookFlightGraph(ctx)
	}
	return graph, errors.Trace(err)
}

// MockChooseSeatAgent sets up a mock handler for the ChooseSeatAgent workflow.
// The handler receives typed inputs from the workflow's state and returns typed outputs.
// A nil handler clears the mock.
func (svc *Mock) MockChooseSeatAgent(handler func(ctx context.Context, flow *workflow.Flow, seatPreference string, availableSeats []string) (seat string, err error)) *Mock { // MARKER: ChooseSeatAgent
	if svc.unsubMockChooseSeatAgent != nil {
		svc.unsubMockChooseSeatAgent()
		svc.unsubMockChooseSeatAgent = nil
	}
	if handler == nil {
		svc.mockChooseSeatAgentGraph = nil
		return svc
	}
	mockName := "MockChooseSeatAgent" + utils.RandomIdentifier(8)
	mockRoute := ":428/mock-choose-seat-agent-" + utils.RandomIdentifier(8)
	mockTaskURL := httpx.JoinHostAndPath(svc.Hostname(), mockRoute)
	svc.mockChooseSeatAgentGraph = func(ctx context.Context) (graph *workflow.Graph, err error) {
		g := workflow.NewGraph("ChooseSeatAgent")
		g.AddTransition(mockTaskURL, workflow.END)
		return g, nil
	}
	err := svc.Subscribe(mockName, func(w http.ResponseWriter, r *http.Request) error {
		var f workflow.Flow
		if err := json.NewDecoder(r.Body).Decode(&f); err != nil {
			return errors.Trace(err)
		}
		snap := f.Snapshot()
		var in flightbookingapi.ChooseSeatAgentIn
		f.ParseState(&in)
		seat, err := handler(r.Context(), &f, in.SeatPreference, in.AvailableSeats)
		if err != nil {
			return err // No trace
		}
		out := flightbookingapi.ChooseSeatAgentOut{Seat: seat}
		f.SetChanges(out, snap)
		w.Header().Set("Content-Type", "application/json")
		return json.NewEncoder(w).Encode(&f)
	},
		sub.At("POST", mockRoute),
		sub.Task(flightbookingapi.ChooseSeatAgentIn{}, flightbookingapi.ChooseSeatAgentOut{}),
	)
	if err == nil {
		svc.unsubMockChooseSeatAgent = func() error { return svc.Unsubscribe(mockName) }
	}
	return svc
}

// ChooseSeatAgent returns the workflow graph, or a mocked graph if MockChooseSeatAgent was called.
func (svc *Mock) ChooseSeatAgent(ctx context.Context) (graph *workflow.Graph, err error) { // MARKER: ChooseSeatAgent
	if svc.mockChooseSeatAgentGraph != nil {
		graph, err = svc.mockChooseSeatAgentGraph(ctx)
	}
	return graph, errors.Trace(err)
}
