// Code generated by cmd/genservice. DO NOT EDIT.

package flightbooking

import (
	"context"
	"net/http"
	"testing"

	"github.com/microbus-io/dwarf/workflow"
	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/exampleservices/flightbooking/flightbookingapi"
	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/testarossa"
)

func TestFlightbooking_Mock(t *testing.T) {
	t.Parallel()
	ctx := t.Context()

	mock := NewMock()
	mock.SetDeployment(connector.TESTING)

	t.Run("on_startup", func(t *testing.T) {
		assert := testarossa.For(t)
		err := mock.OnStartup(ctx)
		assert.NoError(err)
	})

	t.Run("on_shutdown", func(t *testing.T) {
		assert := testarossa.For(t)
		err := mock.OnShutdown(ctx)
		assert.NoError(err)
	})

	t.Run("demo", func(t *testing.T) { // MARKER: Demo
		assert := testarossa.For(t)

		mock.MockDemo(func(w http.ResponseWriter, r *http.Request) (err error) {
			return nil
		})
		w := httpx.NewResponseRecorder()
		r := httpx.MustNewRequest("GET", "/", nil)
		err := mock.Demo(w, r)
		assert.NoError(err)
	})

	t.Run("search_flights", func(t *testing.T) { // MARKER: SearchFlights
		assert := testarossa.For(t)

		mock.MockSearchFlights(func(ctx context.Context, flow *workflow.Flow, origin string, destination string) (candidates []flightbookingapi.Flight, flightIndex int, err error) {
			return
		})
		var origin string
		var destination string
		_, _, err := mock.SearchFlights(ctx, nil, origin, destination)
		assert.NoError(err)
	})

	t.Run("propose_flight", func(t *testing.T) { // MARKER: ProposeFlight
		assert := testarossa.For(t)

		mock.MockProposeFlight(func(ctx context.Context, flow *workflow.Flow, candidates []flightbookingapi.Flight, flightIndex int) (currentFlight flightbookingapi.Flight, exhausted bool, err error) {
			return
		})
		var candidates []flightbookingapi.Flight
		var flightIndex int
		_, _, err := mock.ProposeFlight(ctx, nil, candidates, flightIndex)
		assert.NoError(err)
	})

	t.Run("await_decision", func(t *testing.T) { // MARKER: AwaitDecision
		assert := testarossa.For(t)

		mock.MockAwaitDecision(func(ctx context.Context, flow *workflow.Flow, currentFlight flightbookingapi.Flight, flightIndex int) (accepted bool, flightIndexOut int, err error) {
			return
		})
		var currentFlight flightbookingapi.Flight
		var flightIndex int
		_, _, err := mock.AwaitDecision(ctx, nil, currentFlight, flightIndex)
		assert.NoError(err)
	})

	t.Run("choose_seat", func(t *testing.T) { // MARKER: ChooseSeat
		assert := testarossa.For(t)

		mock.MockChooseSeat(func(ctx context.Context, flow *workflow.Flow, seatPreference string, currentFlight flightbookingapi.Flight) (seat string, err error) {
			return
		})
		var seatPreference string
		var currentFlight flightbookingapi.Flight
		_, err := mock.ChooseSeat(ctx, nil, seatPreference, currentFlight)
		assert.NoError(err)
	})

	t.Run("confirm_booking", func(t *testing.T) { // MARKER: ConfirmBooking
		assert := testarossa.For(t)

		mock.MockConfirmBooking(func(ctx context.Context, flow *workflow.Flow, currentFlight flightbookingapi.Flight, seat string) (confirmation string, airline string, flightNo string, err error) {
			return
		})
		var currentFlight flightbookingapi.Flight
		var seat string
		_, _, _, err := mock.ConfirmBooking(ctx, nil, currentFlight, seat)
		assert.NoError(err)
	})

	t.Run("no_flights", func(t *testing.T) { // MARKER: NoFlights
		assert := testarossa.For(t)

		mock.MockNoFlights(func(ctx context.Context, flow *workflow.Flow) (confirmation string, err error) {
			return
		})
		_, err := mock.NoFlights(ctx, nil)
		assert.NoError(err)
	})

	t.Run("pick_seat", func(t *testing.T) { // MARKER: PickSeat
		assert := testarossa.For(t)

		mock.MockPickSeat(func(ctx context.Context, flow *workflow.Flow, seatPreference string, availableSeats []string) (seat string, err error) {
			return
		})
		var seatPreference string
		var availableSeats []string
		_, err := mock.PickSeat(ctx, nil, seatPreference, availableSeats)
		assert.NoError(err)
	})

	t.Run("book_flight", func(t *testing.T) { // MARKER: BookFlight
		assert := testarossa.For(t)

		mock.MockBookFlight(func(ctx context.Context, flow *workflow.Flow, origin string, destination string, seatPreference string) (confirmation string, airline string, flightNo string, seat string, err error) {
			return
		})
		graph, err := mock.BookFlight(ctx)
		if assert.NoError(err) {
			assert.NotNil(graph)
		}
	})

	t.Run("choose_seat_agent", func(t *testing.T) { // MARKER: ChooseSeatAgent
		assert := testarossa.For(t)

		mock.MockChooseSeatAgent(func(ctx context.Context, flow *workflow.Flow, seatPreference string, availableSeats []string) (seat string, err error) {
			return
		})
		graph, err := mock.ChooseSeatAgent(ctx)
		if assert.NoError(err) {
			assert.NotNil(graph)
		}
	})

}
