// Code generated by cmd/genservice. DO NOT EDIT.

package configonly

import (
	"context"

	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/connector"
)

// Mock is a mockable version of the microservice, allowing functions, event sinks and web handlers to be mocked.
type Mock struct {
	*Intermediate
	mockOnChangedDenyList func(ctx context.Context) (err error) // MARKER: DenyList
}

// NewMock creates a new mockable version of the microservice.
func NewMock() *Mock {
	svc := &Mock{}
	svc.Intermediate = NewIntermediate(svc)
	svc.SetVersion(7357) // Stands for TEST
	return svc
}

// OnStartup is called when the microservice is started up.
func (svc *Mock) OnStartup(ctx context.Context) (err error) {
	if svc.Deployment() != connector.LOCAL && svc.Deployment() != connector.TESTING {
		return errors.New("mocking disallowed in %s deployment", svc.Deployment())
	}
	return nil
}

// OnShutdown is called when the microservice is shut down.
func (svc *Mock) OnShutdown(ctx context.Context) (err error) {
	return nil
}

// MockOnChangedDenyList sets up a mock handler for OnChangedDenyList.
func (svc *Mock) MockOnChangedDenyList(handler func(ctx context.Context) (err error)) *Mock { // MARKER: DenyList
	svc.mockOnChangedDenyList = handler
	return svc
}

// OnChangedDenyList executes the mock handler.
func (svc *Mock) OnChangedDenyList(ctx context.Context) (err error) { // MARKER: DenyList
	if svc.mockOnChangedDenyList != nil {
		err = svc.mockOnChangedDenyList(ctx)
	}
	return errors.Trace(err)
}
