// Code generated by cmd/genmock. DO NOT EDIT.

package saturatedbandflow

import (
	"context"
	"testing"

	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/workflow"
	"github.com/microbus-io/testarossa"
)

func TestSaturatedbandflow_Mock(t *testing.T) {
	t.Parallel()
	ctx := t.Context()

	mock := NewMock()
	mock.SetDeployment(connector.TESTING)

	t.Run("on_startup", func(t *testing.T) {
		assert := testarossa.For(t)
		err := mock.OnStartup(ctx)
		assert.NoError(err)
	})

	t.Run("on_shutdown", func(t *testing.T) {
		assert := testarossa.For(t)
		err := mock.OnShutdown(ctx)
		assert.NoError(err)
	})

	t.Run("bounded", func(t *testing.T) { // MARKER: Bounded
		assert := testarossa.For(t)

		mock.MockBounded(func(ctx context.Context, flow *workflow.Flow, tag string) (tallied bool, err error) {
			return
		})
		var tag string
		_, err := mock.Bounded(ctx, nil, tag)
		assert.NoError(err)
	})

	t.Run("open", func(t *testing.T) { // MARKER: Open
		assert := testarossa.For(t)

		mock.MockOpen(func(ctx context.Context, flow *workflow.Flow, tag string) (tallied bool, err error) {
			return
		})
		var tag string
		_, err := mock.Open(ctx, nil, tag)
		assert.NoError(err)
	})

	t.Run("saturated_band", func(t *testing.T) { // MARKER: SaturatedBand
		assert := testarossa.For(t)

		mock.MockSaturatedBand(func(ctx context.Context, flow *workflow.Flow, tag string) (tallied bool, err error) {
			return
		})
		graph, err := mock.SaturatedBand(ctx)
		if assert.NoError(err) {
			assert.NotNil(graph)
		}
	})

	t.Run("open_band", func(t *testing.T) { // MARKER: OpenBand
		assert := testarossa.For(t)

		mock.MockOpenBand(func(ctx context.Context, flow *workflow.Flow, tag string) (tallied bool, err error) {
			return
		})
		graph, err := mock.OpenBand(ctx)
		if assert.NoError(err) {
			assert.NotNil(graph)
		}
	})

}
