---
title: "Support"
config:
  themeCSS: ".flowchartTitleText { fill: #32a7c1; }"
---
graph LR
    classDef task fill:#32a7c1,color:#f4f2ef,stroke:#32a7c1
    classDef term fill:#e5f4f3,color:#434343,stroke:#32a7c1
    linkStyle default stroke:#32a7c1

    t0["RunSupport"]:::task
    _start(( )):::term --> t0
    t0 --> _end(( )):::term
