/*
Copyright (c) 2023-2026 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
	"text/template"
)

// generateMain returns the source of a tmp/main.go that, when `go run`, writes
// one MMD file per workflow into the microservice directory.
func generateMain(importPath, pkgAlias, dir string, workflows []workflowFn) ([]byte, error) {
	data := struct {
		ImportPath string
		PkgAlias   string
		DirLit     string
		Workflows  []workflowFnLit
	}{
		ImportPath: importPath,
		PkgAlias:   pkgAlias,
		DirLit:     strconv.Quote(dir),
		Workflows:  make([]workflowFnLit, len(workflows)),
	}
	for i, w := range workflows {
		data.Workflows[i] = workflowFnLit{
			Method:    w.Method,
			OutputLit: strconv.Quote(w.OutputFile),
		}
	}
	var buf bytes.Buffer
	err := mainTemplate.Execute(&buf, data)
	if err != nil {
		return nil, fmt.Errorf("execute template: %w", err)
	}
	// gofmt for readability if a human ends up reading the temp file (e.g. --keep-tmp).
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Fall back to unformatted source. `go run` will still report the real error
		// from the compiler.
		return buf.Bytes(), nil
	}
	return formatted, nil
}

type workflowFnLit struct {
	Method    string
	OutputLit string // already double-quoted
}

var mainTemplate = template.Must(template.New("main").Parse(`// Code generated by cmd/genworkflowmmd. DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	{{.PkgAlias}} "{{.ImportPath}}"
)

func write(dir, name, mermaid string) {
	path := filepath.Join(dir, name)
	err := os.WriteFile(path, []byte(mermaid), 0o644)
	if err != nil {
		panic(err)
	}
	fmt.Println("wrote", path)
}

func main() {
	dir := {{.DirLit}}
	svc := {{.PkgAlias}}.NewService()
{{range .Workflows}}
	{
		g, err := svc.{{.Method}}(context.Background())
		if err != nil {
			panic(fmt.Errorf("{{.Method}}: %w", err))
		}
		write(dir, {{.OutputLit}}, g.Mermaid())
	}
{{end}}
}
`))
