// Code generated by cmd/genservice. DO NOT EDIT.

package svcapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/http"
	"reflect"
	"time"

	"github.com/microbus-io/dwarf/workflow"
	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/fabric/pub"
	"github.com/microbus-io/fabric/service"
)

// multicastResponse packs the response of a functional multicast.
type multicastResponse struct {
	data         any
	HTTPResponse *http.Response
	err          error
}

// Client is a lightweight proxy for making unicast calls to the microservice.
type Client struct {
	svc  service.Publisher
	host string
	opts []pub.Option
}

// NewClient creates a new unicast client proxy to the microservice.
func NewClient(caller service.Publisher) Client {
	return Client{svc: caller, host: Hostname}
}

// ForHost returns a copy of the client with a different hostname to be applied to requests.
func (_c Client) ForHost(host string) Client {
	return Client{svc: _c.svc, host: host, opts: _c.opts}
}

// WithOptions returns a copy of the client with options to be applied to requests.
func (_c Client) WithOptions(opts ...pub.Option) Client {
	return Client{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...)}
}

// MulticastClient is a lightweight proxy for making multicast calls to the microservice.
type MulticastClient struct {
	svc  service.Publisher
	host string
	opts []pub.Option
}

// NewMulticastClient creates a new multicast client proxy to the microservice.
func NewMulticastClient(caller service.Publisher) MulticastClient {
	return MulticastClient{svc: caller, host: Hostname}
}

// ForHost returns a copy of the client with a different hostname to be applied to requests.
func (_c MulticastClient) ForHost(host string) MulticastClient {
	return MulticastClient{svc: _c.svc, host: host, opts: _c.opts}
}

// WithOptions returns a copy of the client with options to be applied to requests.
func (_c MulticastClient) WithOptions(opts ...pub.Option) MulticastClient {
	return MulticastClient{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...)}
}

// WorkflowRunner executes a workflow by name with initial state, blocking until termination.
// foremanapi.Client satisfies this interface.
type WorkflowRunner interface {
	Run(ctx context.Context, workflowName string, initialState any, opts *workflow.FlowOptions) (outcome *workflow.FlowOutcome, err error)
}

// Executor runs tasks and workflows synchronously, blocking until termination.
// It is primarily intended for integration tests.
type Executor struct {
	svc         service.Publisher
	host        string
	opts        []pub.Option
	inFlow      *workflow.Flow
	outFlow     *workflow.Flow
	runner      WorkflowRunner
	flowOptions *workflow.FlowOptions
}

// NewExecutor creates a new executor proxy to the microservice.
func NewExecutor(caller service.Publisher) Executor {
	return Executor{svc: caller, host: Hostname}
}

// ForHost returns a copy of the executor with a different hostname to be applied to requests.
func (_c Executor) ForHost(host string) Executor {
	return Executor{svc: _c.svc, host: host, opts: _c.opts, inFlow: _c.inFlow, outFlow: _c.outFlow, runner: _c.runner, flowOptions: _c.flowOptions}
}

// WithOptions returns a copy of the executor with options to be applied to requests.
func (_c Executor) WithOptions(opts ...pub.Option) Executor {
	return Executor{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...), inFlow: _c.inFlow, outFlow: _c.outFlow, runner: _c.runner, flowOptions: _c.flowOptions}
}

// WithInputFlow returns a copy of the executor with an input flow to use for task execution.
// The input flow's state is available to the task in addition to the typed input arguments.
func (_c Executor) WithInputFlow(flow *workflow.Flow) Executor {
	return Executor{svc: _c.svc, host: _c.host, opts: _c.opts, inFlow: flow, outFlow: _c.outFlow, runner: _c.runner, flowOptions: _c.flowOptions}
}

// WithOutputFlow returns a copy of the executor with an output flow to populate after task execution.
// The output flow captures the full flow state including control signals (Goto, Retry, Interrupt, Sleep).
func (_c Executor) WithOutputFlow(flow *workflow.Flow) Executor {
	return Executor{svc: _c.svc, host: _c.host, opts: _c.opts, inFlow: _c.inFlow, outFlow: flow, runner: _c.runner, flowOptions: _c.flowOptions}
}

// WithWorkflowRunner returns a copy of the executor with a workflow runner for executing workflows.
// foremanapi.NewClient(svc) satisfies the WorkflowRunner interface.
func (_c Executor) WithWorkflowRunner(runner WorkflowRunner) Executor {
	return Executor{svc: _c.svc, host: _c.host, opts: _c.opts, inFlow: _c.inFlow, outFlow: _c.outFlow, runner: runner, flowOptions: _c.flowOptions}
}

// WithFlowOptions returns a copy of the executor that creates workflows with the given flow options
// (priority, fairness key and weight). It has no effect on task execution.
func (_c Executor) WithFlowOptions(flowOptions *workflow.FlowOptions) Executor {
	return Executor{svc: _c.svc, host: _c.host, opts: _c.opts, inFlow: _c.inFlow, outFlow: _c.outFlow, runner: _c.runner, flowOptions: flowOptions}
}

// Subflow runs this microservice's tasks and workflows as isolated child flows from INSIDE a task body.
// Unlike Executor (which carries a service.Publisher and is for tests), Subflow carries the calling
// task's *workflow.Flow: each method parks the calling step and re-enters it when the child terminates,
// returning (..., yield bool, err error).
type Subflow struct {
	flow *workflow.Flow
}

// NewSubflow creates a subflow client bound to the calling task's flow carrier.
func NewSubflow(flow *workflow.Flow) Subflow {
	return Subflow{flow: flow}
}

// marshalRequest supports functional endpoints.
func marshalRequest(ctx context.Context, svc service.Publisher, opts []pub.Option, host string, method string, route string, in any, out any) (err error) {
	if method == "ANY" {
		method = "POST"
	}
	u := httpx.JoinHostAndPath(host, route)
	query, body, err := httpx.WriteInputPayload(method, in)
	if err != nil {
		return err // No trace
	}
	httpRes, err := svc.Request(
		ctx,
		pub.Method(method),
		pub.URL(u),
		pub.Query(query),
		pub.Body(body),
		pub.Options(opts...),
	)
	if err != nil {
		return err // No trace
	}
	err = httpx.ReadOutputPayload(httpRes, out)
	return errors.Trace(err)
}

// marshalPublish supports multicast functional endpoints.
func marshalPublish(ctx context.Context, svc service.Publisher, opts []pub.Option, host string, method string, route string, in any, out any) iter.Seq[*multicastResponse] {
	if method == "ANY" {
		method = "POST"
	}
	u := httpx.JoinHostAndPath(host, route)
	query, body, err := httpx.WriteInputPayload(method, in)
	if err != nil {
		return func(yield func(*multicastResponse) bool) {
			yield(&multicastResponse{err: err})
		}
	}
	_queue := svc.Publish(
		ctx,
		pub.Method(method),
		pub.URL(u),
		pub.Query(query),
		pub.Body(body),
		pub.Options(opts...),
	)
	return func(yield func(*multicastResponse) bool) {
		for qi := range _queue {
			httpResp, err := qi.Get()
			if err == nil {
				reflect.ValueOf(out).Elem().SetZero()
				err = httpx.ReadOutputPayload(httpResp, out)
			}
			if err != nil {
				if !yield(&multicastResponse{err: err, HTTPResponse: httpResp}) {
					return
				}
			} else {
				if !yield(&multicastResponse{data: out, HTTPResponse: httpResp}) {
					return
				}
			}
		}
	}
}

// marshalTask supports task execution via the Executor.
func marshalTask(ctx context.Context, svc service.Publisher, opts []pub.Option, host string, method string, route string, in any, out any, inFlow *workflow.Flow, outFlow *workflow.Flow) (err error) {
	flow := inFlow
	if flow == nil {
		flow = workflow.NewFlow()
	}
	err = flow.SetState(in)
	if err != nil {
		return errors.Trace(err)
	}
	body, err := json.Marshal(flow)
	if err != nil {
		return errors.Trace(err)
	}
	u := httpx.JoinHostAndPath(host, route)
	httpRes, err := svc.Request(
		ctx,
		pub.Method(method),
		pub.URL(u),
		pub.Body(body),
		pub.ContentType("application/json"),
		pub.Options(opts...),
	)
	if err != nil {
		return err // No trace
	}
	err = json.NewDecoder(httpRes.Body).Decode(flow)
	if err != nil {
		return errors.Trace(err)
	}
	if outFlow != nil {
		*outFlow = *flow
	}
	if out != nil {
		err = flow.ParseState(out)
		return errors.Trace(err)
	}
	return nil
}

// marshalWorkflow supports workflow execution via the Executor.
func marshalWorkflow(ctx context.Context, runner WorkflowRunner, flowOptions *workflow.FlowOptions, workflowURL string, in any, out any) (status string, err error) {
	outcome, err := runner.Run(ctx, workflowURL, in, flowOptions)
	if err != nil {
		if outcome != nil {
			return outcome.Status, err // No trace
		}
		return "", err // No trace
	}
	if outcome == nil {
		return "", nil
	}
	status = outcome.Status
	if out != nil && outcome.State != nil {
		data, err := json.Marshal(outcome.State)
		if err != nil {
			return status, errors.Trace(err)
		}
		err = json.Unmarshal(data, out)
		if err != nil {
			return status, errors.Trace(err)
		}
	}
	return status, nil
}

// marshalSubflow runs a child flow via the flow carrier and returns the parker's yield.
func marshalSubflow(flow *workflow.Flow, taskName, url string, in any, out any) (yield bool, err error) {
	if flow == nil {
		return false, errors.New("Subflow requires a flow carrier (call from a task body)")
	}
	if taskName != "" {
		return flow.Subtask(taskName, url, in, out)
	}
	return flow.Subgraph(url, in, out)
}

// Greet returns a greeting for a name.
func (_c Client) Greet(ctx context.Context, name string) (greeting string, err error) { // MARKER: Greet
	_in := GreetIn{Name: name}
	_out := GreetOut{}
	err = marshalRequest(ctx, _c.svc, _c.opts, _c.host, Greet.Method, Greet.Route, &_in, &_out)
	return _out.Greeting, err // No trace
}

// GreetResponse packs the response of Greet.
type GreetResponse multicastResponse // MARKER: Greet

// Get unpacks the return arguments of Greet.
func (_res *GreetResponse) Get() (greeting string, err error) { // MARKER: Greet
	_d := _res.data.(*GreetOut)
	return _d.Greeting, _res.err
}

// Greet returns a greeting for a name.
func (_c MulticastClient) Greet(ctx context.Context, name string) iter.Seq[*GreetResponse] { // MARKER: Greet
	_in := GreetIn{Name: name}
	_out := GreetOut{}
	_queue := marshalPublish(ctx, _c.svc, _c.opts, _c.host, Greet.Method, Greet.Route, &_in, &_out)
	return func(yield func(*GreetResponse) bool) {
		for _r := range _queue {
			_clone := _out
			_r.data = &_clone
			if !yield((*GreetResponse)(_r)) {
				return
			}
		}
	}
}

// Adopt registers a pet and returns the adoption time. It exercises qualification of a domain type
// (Pet -> svcapi.Pet) and an external type (time.Time) in the generated service-package files.
func (_c Client) Adopt(ctx context.Context, pet Pet) (since time.Time, err error) { // MARKER: Adopt
	_in := AdoptIn{Pet: pet}
	_out := AdoptOut{}
	err = marshalRequest(ctx, _c.svc, _c.opts, _c.host, Adopt.Method, Adopt.Route, &_in, &_out)
	return _out.Since, err // No trace
}

// AdoptResponse packs the response of Adopt.
type AdoptResponse multicastResponse // MARKER: Adopt

// Get unpacks the return arguments of Adopt.
func (_res *AdoptResponse) Get() (since time.Time, err error) { // MARKER: Adopt
	_d := _res.data.(*AdoptOut)
	return _d.Since, _res.err
}

// Adopt registers a pet and returns the adoption time. It exercises qualification of a domain type
// (Pet -> svcapi.Pet) and an external type (time.Time) in the generated service-package files.
func (_c MulticastClient) Adopt(ctx context.Context, pet Pet) iter.Seq[*AdoptResponse] { // MARKER: Adopt
	_in := AdoptIn{Pet: pet}
	_out := AdoptOut{}
	_queue := marshalPublish(ctx, _c.svc, _c.opts, _c.host, Adopt.Method, Adopt.Route, &_in, &_out)
	return func(yield func(*AdoptResponse) bool) {
		for _r := range _queue {
			_clone := _out
			_r.data = &_clone
			if !yield((*AdoptResponse)(_r)) {
				return
			}
		}
	}
}

// Ping checks liveness; it takes and returns nothing.
func (_c Client) Ping(ctx context.Context) (err error) { // MARKER: Ping
	_in := PingIn{}
	_out := PingOut{}
	err = marshalRequest(ctx, _c.svc, _c.opts, _c.host, Ping.Method, Ping.Route, &_in, &_out)
	return err // No trace
}

// PingResponse packs the response of Ping.
type PingResponse multicastResponse // MARKER: Ping

// Get unpacks the return arguments of Ping.
func (_res *PingResponse) Get() (err error) { // MARKER: Ping
	return _res.err
}

// Ping checks liveness; it takes and returns nothing.
func (_c MulticastClient) Ping(ctx context.Context) iter.Seq[*PingResponse] { // MARKER: Ping
	_in := PingIn{}
	_out := PingOut{}
	_queue := marshalPublish(ctx, _c.svc, _c.opts, _c.host, Ping.Method, Ping.Route, &_in, &_out)
	return func(yield func(*PingResponse) bool) {
		for _r := range _queue {
			_clone := _out
			_r.data = &_clone
			if !yield((*PingResponse)(_r)) {
				return
			}
		}
	}
}

// Dashboard serves an HTML dashboard on any method (ANY -> 4-arg web client).
func (_c Client) Dashboard(ctx context.Context, method string, relativeURL string, body any) (res *http.Response, err error) { // MARKER: Dashboard
	if method == "" {
		method = Dashboard.Method
	}
	if method == "ANY" {
		method = "POST"
	}
	return _c.svc.Request(
		ctx,
		pub.Method(method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Dashboard.Route)),
		pub.RelativeURL(relativeURL),
		pub.Body(body),
		pub.Options(_c.opts...),
	)
}

// Dashboard serves an HTML dashboard on any method (ANY -> 4-arg web client).
func (_c MulticastClient) Dashboard(ctx context.Context, method string, relativeURL string, body any) iter.Seq[*pub.Response] { // MARKER: Dashboard
	if method == "" {
		method = Dashboard.Method
	}
	if method == "ANY" {
		method = "POST"
	}
	return _c.svc.Publish(
		ctx,
		pub.Method(method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Dashboard.Route)),
		pub.RelativeURL(relativeURL),
		pub.Body(body),
		pub.Options(_c.opts...),
	)
}

// Status serves a plain status page (GET -> 2-arg web client, no body).
func (_c Client) Status(ctx context.Context, relativeURL string) (res *http.Response, err error) { // MARKER: Status
	return _c.svc.Request(
		ctx,
		pub.Method(Status.Method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Status.Route)),
		pub.RelativeURL(relativeURL),
		pub.Options(_c.opts...),
	)
}

// Status serves a plain status page (GET -> 2-arg web client, no body).
func (_c MulticastClient) Status(ctx context.Context, relativeURL string) iter.Seq[*pub.Response] { // MARKER: Status
	return _c.svc.Publish(
		ctx,
		pub.Method(Status.Method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Status.Route)),
		pub.RelativeURL(relativeURL),
		pub.Options(_c.opts...),
	)
}

// Upload accepts a file upload (POST -> 3-arg web client, with body).
func (_c Client) Upload(ctx context.Context, relativeURL string, body any) (res *http.Response, err error) { // MARKER: Upload
	return _c.svc.Request(
		ctx,
		pub.Method(Upload.Method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Upload.Route)),
		pub.RelativeURL(relativeURL),
		pub.Body(body),
		pub.Options(_c.opts...),
	)
}

// Upload accepts a file upload (POST -> 3-arg web client, with body).
func (_c MulticastClient) Upload(ctx context.Context, relativeURL string, body any) iter.Seq[*pub.Response] { // MARKER: Upload
	return _c.svc.Publish(
		ctx,
		pub.Method(Upload.Method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Upload.Route)),
		pub.RelativeURL(relativeURL),
		pub.Body(body),
		pub.Options(_c.opts...),
	)
}

// ProcessStep is a workflow task that processes an item.
func (_c Executor) ProcessStep(ctx context.Context, item string) (done bool, err error) { // MARKER: ProcessStep
	var out ProcessStepOut
	err = marshalTask(ctx, _c.svc, _c.opts, _c.host, ProcessStep.Method, ProcessStep.Route, ProcessStepIn{Item: item}, &out, _c.inFlow, _c.outFlow)
	return out.Done, err // No trace
}

// ProcessStep is a workflow task that processes an item.
func (_sf Subflow) ProcessStep(ctx context.Context, item string) (done bool, yield bool, err error) { // MARKER: ProcessStep
	var out ProcessStepOut
	yield, err = marshalSubflow(_sf.flow, "ProcessStep", ProcessStep.URL(), ProcessStepIn{Item: item}, &out)
	if yield || err != nil {
		return done, yield, err
	}
	return out.Done, false, nil
}

// ReviewStep is a workflow task whose output read-modify-writes the shared "count" state field.
func (_c Executor) ReviewStep(ctx context.Context, count int) (countOut int, err error) { // MARKER: ReviewStep
	var out ReviewStepOut
	err = marshalTask(ctx, _c.svc, _c.opts, _c.host, ReviewStep.Method, ReviewStep.Route, ReviewStepIn{Count: count}, &out, _c.inFlow, _c.outFlow)
	return out.CountOut, err // No trace
}

// ReviewStep is a workflow task whose output read-modify-writes the shared "count" state field.
func (_sf Subflow) ReviewStep(ctx context.Context, count int) (countOut int, yield bool, err error) { // MARKER: ReviewStep
	var out ReviewStepOut
	yield, err = marshalSubflow(_sf.flow, "ReviewStep", ReviewStep.URL(), ReviewStepIn{Count: count}, &out)
	if yield || err != nil {
		return countOut, yield, err
	}
	return out.CountOut, false, nil
}

// MainFlow is the top-level workflow graph.
func (_c Executor) MainFlow(ctx context.Context, item string, pet Pet) (done bool, since time.Time, status string, err error) { // MARKER: MainFlow
	if _c.runner == nil {
		return done, since, "", errors.New("workflow runner not set, use WithWorkflowRunner")
	}
	var out MainFlowOut
	status, err = marshalWorkflow(ctx, _c.runner, _c.flowOptions, MainFlow.URL(), MainFlowIn{Item: item, Pet: pet}, &out)
	return out.Done, out.Since, status, err
}

// MainFlow is the top-level workflow graph.
func (_sf Subflow) MainFlow(ctx context.Context, item string, pet Pet) (done bool, since time.Time, yield bool, err error) { // MARKER: MainFlow
	var out MainFlowOut
	yield, err = marshalSubflow(_sf.flow, "", MainFlow.URL(), MainFlowIn{Item: item, Pet: pet}, &out)
	if yield || err != nil {
		return done, since, yield, err
	}
	return out.Done, out.Since, false, nil
}
