/*
Copyright (c) 2023-2026 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cmd/genmock. DO NOT EDIT.

package nestedfanoutflow

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/fabric/sub"
	"github.com/microbus-io/fabric/utils"
	"github.com/microbus-io/fabric/workflow"

	"github.com/microbus-io/fabric/verify/nestedfanoutflow/nestedfanoutflowapi"
)

// Mock is a mockable version of the microservice, allowing functions, event sinks and web handlers to be mocked.
type Mock struct {
	*Intermediate
	mockTaskA       func(ctx context.Context, flow *workflow.Flow) (started bool, err error)                                             // MARKER: TaskA
	mockNormalB     func(ctx context.Context, flow *workflow.Flow) (normalResult string, err error)                                      // MARKER: NormalB
	mockTaskX       func(ctx context.Context, flow *workflow.Flow) (innerStarted bool, err error)                                        // MARKER: TaskX
	mockTaskY       func(ctx context.Context, flow *workflow.Flow) (sumInnerOut int, err error)                                          // MARKER: TaskY
	mockTaskZ       func(ctx context.Context, flow *workflow.Flow) (sumInnerOut int, err error)                                          // MARKER: TaskZ
	mockTaskW       func(ctx context.Context, flow *workflow.Flow, sumInner int) (innerResult int, err error)                            // MARKER: TaskW
	mockTaskJ       func(ctx context.Context, flow *workflow.Flow, normalResult string, innerResult int) (finalResult string, err error) // MARKER: TaskJ
	mockInnerGraph  func(ctx context.Context) (graph *workflow.Graph, err error)                                                         // MARKER: Inner
	unsubMockInner  func() error                                                                                                         // MARKER: Inner
	mockNestedGraph func(ctx context.Context) (graph *workflow.Graph, err error)                                                         // MARKER: Nested
	unsubMockNested func() error                                                                                                         // MARKER: Nested
}

// NewMock creates a new mockable version of the microservice.
func NewMock() *Mock {
	svc := &Mock{}
	svc.Intermediate = NewIntermediate(svc)
	svc.SetVersion(7357) // Stands for TEST
	return svc
}

// OnStartup is called when the microservice is started up.
func (svc *Mock) OnStartup(ctx context.Context) (err error) {
	if svc.Deployment() != connector.LOCAL && svc.Deployment() != connector.TESTING {
		return errors.New("mocking disallowed in %s deployment", svc.Deployment())
	}
	return nil
}

// OnShutdown is called when the microservice is shut down.
func (svc *Mock) OnShutdown(ctx context.Context) (err error) {
	return nil
}

// MockTaskA sets up a mock handler for TaskA.
func (svc *Mock) MockTaskA(handler func(ctx context.Context, flow *workflow.Flow) (started bool, err error)) *Mock { // MARKER: TaskA
	svc.mockTaskA = handler
	return svc
}

// TaskA executes the mock handler.
func (svc *Mock) TaskA(ctx context.Context, flow *workflow.Flow) (started bool, err error) { // MARKER: TaskA
	if svc.mockTaskA != nil {
		started, err = svc.mockTaskA(ctx, flow)
	}
	return started, errors.Trace(err)
}

// MockNormalB sets up a mock handler for NormalB.
func (svc *Mock) MockNormalB(handler func(ctx context.Context, flow *workflow.Flow) (normalResult string, err error)) *Mock { // MARKER: NormalB
	svc.mockNormalB = handler
	return svc
}

// NormalB executes the mock handler.
func (svc *Mock) NormalB(ctx context.Context, flow *workflow.Flow) (normalResult string, err error) { // MARKER: NormalB
	if svc.mockNormalB != nil {
		normalResult, err = svc.mockNormalB(ctx, flow)
	}
	return normalResult, errors.Trace(err)
}

// MockTaskX sets up a mock handler for TaskX.
func (svc *Mock) MockTaskX(handler func(ctx context.Context, flow *workflow.Flow) (innerStarted bool, err error)) *Mock { // MARKER: TaskX
	svc.mockTaskX = handler
	return svc
}

// TaskX executes the mock handler.
func (svc *Mock) TaskX(ctx context.Context, flow *workflow.Flow) (innerStarted bool, err error) { // MARKER: TaskX
	if svc.mockTaskX != nil {
		innerStarted, err = svc.mockTaskX(ctx, flow)
	}
	return innerStarted, errors.Trace(err)
}

// MockTaskY sets up a mock handler for TaskY.
func (svc *Mock) MockTaskY(handler func(ctx context.Context, flow *workflow.Flow) (sumInnerOut int, err error)) *Mock { // MARKER: TaskY
	svc.mockTaskY = handler
	return svc
}

// TaskY executes the mock handler.
func (svc *Mock) TaskY(ctx context.Context, flow *workflow.Flow) (sumInnerOut int, err error) { // MARKER: TaskY
	if svc.mockTaskY != nil {
		sumInnerOut, err = svc.mockTaskY(ctx, flow)
	}
	return sumInnerOut, errors.Trace(err)
}

// MockTaskZ sets up a mock handler for TaskZ.
func (svc *Mock) MockTaskZ(handler func(ctx context.Context, flow *workflow.Flow) (sumInnerOut int, err error)) *Mock { // MARKER: TaskZ
	svc.mockTaskZ = handler
	return svc
}

// TaskZ executes the mock handler.
func (svc *Mock) TaskZ(ctx context.Context, flow *workflow.Flow) (sumInnerOut int, err error) { // MARKER: TaskZ
	if svc.mockTaskZ != nil {
		sumInnerOut, err = svc.mockTaskZ(ctx, flow)
	}
	return sumInnerOut, errors.Trace(err)
}

// MockTaskW sets up a mock handler for TaskW.
func (svc *Mock) MockTaskW(handler func(ctx context.Context, flow *workflow.Flow, sumInner int) (innerResult int, err error)) *Mock { // MARKER: TaskW
	svc.mockTaskW = handler
	return svc
}

// TaskW executes the mock handler.
func (svc *Mock) TaskW(ctx context.Context, flow *workflow.Flow, sumInner int) (innerResult int, err error) { // MARKER: TaskW
	if svc.mockTaskW != nil {
		innerResult, err = svc.mockTaskW(ctx, flow, sumInner)
	}
	return innerResult, errors.Trace(err)
}

// MockTaskJ sets up a mock handler for TaskJ.
func (svc *Mock) MockTaskJ(handler func(ctx context.Context, flow *workflow.Flow, normalResult string, innerResult int) (finalResult string, err error)) *Mock { // MARKER: TaskJ
	svc.mockTaskJ = handler
	return svc
}

// TaskJ executes the mock handler.
func (svc *Mock) TaskJ(ctx context.Context, flow *workflow.Flow, normalResult string, innerResult int) (finalResult string, err error) { // MARKER: TaskJ
	if svc.mockTaskJ != nil {
		finalResult, err = svc.mockTaskJ(ctx, flow, normalResult, innerResult)
	}
	return finalResult, errors.Trace(err)
}

// MockInner sets up a mock handler for the Inner workflow.
// The handler receives typed inputs from the workflow's state and returns typed outputs.
// A nil handler clears the mock.
func (svc *Mock) MockInner(handler func(ctx context.Context, flow *workflow.Flow) (innerResult int, err error)) *Mock { // MARKER: Inner
	if svc.unsubMockInner != nil {
		svc.unsubMockInner()
		svc.unsubMockInner = nil
	}
	if handler == nil {
		svc.mockInnerGraph = nil
		return svc
	}
	mockName := "MockInner" + utils.RandomIdentifier(8)
	mockRoute := ":428/mock-inner-" + utils.RandomIdentifier(8)
	mockTaskURL := httpx.JoinHostAndPath(svc.Hostname(), mockRoute)
	svc.mockInnerGraph = func(ctx context.Context) (graph *workflow.Graph, err error) {
		g := workflow.NewGraph(nestedfanoutflowapi.Inner.URL())
		g.AddTransition(mockTaskURL, workflow.END)
		return g, nil
	}
	err := svc.Subscribe(mockName, func(w http.ResponseWriter, r *http.Request) error {
		var f workflow.Flow
		if err := json.NewDecoder(r.Body).Decode(&f); err != nil {
			return errors.Trace(err)
		}
		snap := f.Snapshot()
		var in nestedfanoutflowapi.InnerIn
		f.ParseState(&in)
		innerResult, err := handler(r.Context(), &f)
		if err != nil {
			return err // No trace
		}
		out := nestedfanoutflowapi.InnerOut{InnerResult: innerResult}
		f.SetChanges(out, snap)
		w.Header().Set("Content-Type", "application/json")
		return json.NewEncoder(w).Encode(&f)
	},
		sub.At("POST", mockRoute),
		sub.Task(nestedfanoutflowapi.InnerIn{}, nestedfanoutflowapi.InnerOut{}),
	)
	if err == nil {
		svc.unsubMockInner = func() error { return svc.Unsubscribe(mockName) }
	}
	return svc
}

// Inner returns the workflow graph, or a mocked graph if MockInner was called.
func (svc *Mock) Inner(ctx context.Context) (graph *workflow.Graph, err error) { // MARKER: Inner
	if svc.mockInnerGraph != nil {
		graph, err = svc.mockInnerGraph(ctx)
	}
	return graph, errors.Trace(err)
}

// MockNested sets up a mock handler for the Nested workflow.
// The handler receives typed inputs from the workflow's state and returns typed outputs.
// A nil handler clears the mock.
func (svc *Mock) MockNested(handler func(ctx context.Context, flow *workflow.Flow) (finalResult string, err error)) *Mock { // MARKER: Nested
	if svc.unsubMockNested != nil {
		svc.unsubMockNested()
		svc.unsubMockNested = nil
	}
	if handler == nil {
		svc.mockNestedGraph = nil
		return svc
	}
	mockName := "MockNested" + utils.RandomIdentifier(8)
	mockRoute := ":428/mock-nested-" + utils.RandomIdentifier(8)
	mockTaskURL := httpx.JoinHostAndPath(svc.Hostname(), mockRoute)
	svc.mockNestedGraph = func(ctx context.Context) (graph *workflow.Graph, err error) {
		g := workflow.NewGraph(nestedfanoutflowapi.Nested.URL())
		g.AddTransition(mockTaskURL, workflow.END)
		return g, nil
	}
	err := svc.Subscribe(mockName, func(w http.ResponseWriter, r *http.Request) error {
		var f workflow.Flow
		if err := json.NewDecoder(r.Body).Decode(&f); err != nil {
			return errors.Trace(err)
		}
		snap := f.Snapshot()
		var in nestedfanoutflowapi.NestedIn
		f.ParseState(&in)
		finalResult, err := handler(r.Context(), &f)
		if err != nil {
			return err // No trace
		}
		out := nestedfanoutflowapi.NestedOut{FinalResult: finalResult}
		f.SetChanges(out, snap)
		w.Header().Set("Content-Type", "application/json")
		return json.NewEncoder(w).Encode(&f)
	},
		sub.At("POST", mockRoute),
		sub.Task(nestedfanoutflowapi.NestedIn{}, nestedfanoutflowapi.NestedOut{}),
	)
	if err == nil {
		svc.unsubMockNested = func() error { return svc.Unsubscribe(mockName) }
	}
	return svc
}

// Nested returns the workflow graph, or a mocked graph if MockNested was called.
func (svc *Mock) Nested(ctx context.Context) (graph *workflow.Graph, err error) { // MARKER: Nested
	if svc.mockNestedGraph != nil {
		graph, err = svc.mockNestedGraph(ctx)
	}
	return graph, errors.Trace(err)
}
