graph LR
    classDef task fill:#32a7c1,color:#f4f2ef,stroke:#32a7c1
    classDef term fill:#e5f4f3,color:#434343,stroke:#32a7c1
    classDef note fill:none,stroke:none,color:#32a7c1,font-size:0.8em
    linkStyle default stroke:#32a7c1

    _title{{"nested"}}:::term -.-> _start
    t0["taskA"]:::task
    t1["normalB"]:::task
    t2["runInner"]:::task
    t3["taskJ"]:::task
    t3_reduce(("reduce")):::term
    t3_reduce --> t3
    t0 --> t1
    t0 --> t2
    t1 --> t3_reduce
    t2 --> t3_reduce
    _start(( )):::term --> t0
    t3 --> _end(( )):::term
