/*
Copyright (c) 2023-2026 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cmd/genservice. DO NOT EDIT.

package geminillm

import (
	"context"

	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/coreservices/llm/llmapi"
)

// Mock is a mockable version of the microservice, allowing functions, event sinks and web handlers to be mocked.
type Mock struct {
	*Intermediate
	mockTurn              func(ctx context.Context, model string, items []llmapi.Item, tools []llmapi.Tool, options *llmapi.TurnOptions) (itemsOut []llmapi.Item, stopReason string, usage llmapi.Usage, err error) // MARKER: Turn
	mockOnResolveProvider func(ctx context.Context, model string) (ok bool, err error)                                                                                                                              // MARKER: OnResolveProvider
}

// NewMock creates a new mockable version of the microservice.
func NewMock() *Mock {
	svc := &Mock{}
	svc.Intermediate = NewIntermediate(svc)
	svc.SetVersion(7357) // Stands for TEST
	return svc
}

// OnStartup is called when the microservice is started up.
func (svc *Mock) OnStartup(ctx context.Context) (err error) {
	if svc.Deployment() != connector.LOCAL && svc.Deployment() != connector.TESTING {
		return errors.New("mocking disallowed in %s deployment", svc.Deployment())
	}
	return nil
}

// OnShutdown is called when the microservice is shut down.
func (svc *Mock) OnShutdown(ctx context.Context) (err error) {
	return nil
}

// MockTurn sets up a mock handler for Turn.
func (svc *Mock) MockTurn(handler func(ctx context.Context, model string, items []llmapi.Item, tools []llmapi.Tool, options *llmapi.TurnOptions) (itemsOut []llmapi.Item, stopReason string, usage llmapi.Usage, err error)) *Mock { // MARKER: Turn
	svc.mockTurn = handler
	return svc
}

// Turn executes the mock handler.
func (svc *Mock) Turn(ctx context.Context, model string, items []llmapi.Item, tools []llmapi.Tool, options *llmapi.TurnOptions) (itemsOut []llmapi.Item, stopReason string, usage llmapi.Usage, err error) { // MARKER: Turn
	if svc.mockTurn != nil {
		itemsOut, stopReason, usage, err = svc.mockTurn(ctx, model, items, tools, options)
	}
	return itemsOut, stopReason, usage, errors.Trace(err)
}

// MockOnResolveProvider sets up a mock handler for OnResolveProvider.
func (svc *Mock) MockOnResolveProvider(handler func(ctx context.Context, model string) (ok bool, err error)) *Mock { // MARKER: OnResolveProvider
	svc.mockOnResolveProvider = handler
	return svc
}

// OnResolveProvider executes the mock handler.
func (svc *Mock) OnResolveProvider(ctx context.Context, model string) (ok bool, err error) { // MARKER: OnResolveProvider
	if svc.mockOnResolveProvider != nil {
		ok, err = svc.mockOnResolveProvider(ctx, model)
	}
	return ok, errors.Trace(err)
}
