graph LR
    classDef task fill:#32a7c1,color:#f4f2ef,stroke:#32a7c1
    classDef term fill:#e5f4f3,color:#434343,stroke:#32a7c1
    classDef note fill:none,stroke:none,color:#32a7c1,font-size:0.8em
    linkStyle default stroke:#32a7c1

    _title{{"dynamic-fan-out"}}:::term -.-> _start
    t0["taskA"]:::task
    t1["taskB"]:::task
    t2["taskC"]:::task
    t2_reduce(("reduce")):::term
    t2_reduce --> t2
    t0 -->|"for each"| t1
    t1 --> t2_reduce
    _start(( )):::term --> t0
    t2 --> _end(( )):::term
