graph LR
    classDef task fill:#32a7c1,color:#f4f2ef,stroke:#32a7c1
    classDef term fill:#e5f4f3,color:#434343,stroke:#32a7c1
    classDef note fill:none,stroke:none,color:#32a7c1,font-size:0.8em
    linkStyle default stroke:#32a7c1

    _title{{"fairness"}}:::term -.-> _start
    t0["tally"]:::task
    _start(( )):::term --> t0
    t0 --> _end(( )):::term
