graph LR
    classDef task fill:#32a7c1,color:#f4f2ef,stroke:#32a7c1
    classDef term fill:#e5f4f3,color:#434343,stroke:#32a7c1
    classDef note fill:none,stroke:none,color:#32a7c1,font-size:0.8em
    linkStyle default stroke:#32a7c1

    _title{{"conditional"}}:::term -.-> _start
    t0["taskA"]:::task
    t0_when{"when"}:::term
    t1["taskHigh"]:::task
    t2["taskLow"]:::task
    t3["taskC"]:::task
    t3_reduce(("reduce")):::term
    t3_reduce --> t3
    t1 --> t3_reduce
    t2 --> t3_reduce
    t0 --> t0_when
    t0_when -->|"score >= 50"| t1
    t0_when -->|"score < 50"| t2
    _start(( )):::term --> t0
    t3 --> _end(( )):::term
