graph LR
    classDef task fill:#32a7c1,color:#f4f2ef,stroke:#32a7c1
    classDef term fill:#e5f4f3,color:#434343,stroke:#32a7c1
    classDef note fill:none,stroke:none,color:#32a7c1,font-size:0.8em
    linkStyle default stroke:#32a7c1

    _title{{"fan-out-error"}}:::term -.-> _start
    t0["taskA"]:::task
    t1["taskB"]:::task
    t2["taskC"]:::task
    t3["taskD"]:::task
    t4["handler"]:::task
    t5["taskE"]:::task
    t5_reduce(("reduce")):::term
    t5_reduce --> t5
    t0 --> t1
    t0 --> t2
    t0 --> t3
    t1 -->|"onError"| t4
    t1 --> t5_reduce
    t2 --> t5_reduce
    t3 --> t5_reduce
    t4 --> t5_reduce
    _start(( )):::term --> t0
    t5 --> _end(( )):::term
