// Code generated by cmd/genservice. DO NOT EDIT.

package svc

import (
	"context"
	"encoding/json"
	"net/http"
	"time"

	"github.com/microbus-io/dwarf/workflow"
	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/cmd/genservice/testdata/svc/svcapi"
	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/fabric/sub"
	"github.com/microbus-io/fabric/utils"
)

// Mock is a mockable version of the microservice, allowing functions, event sinks and web handlers to be mocked.
type Mock struct {
	*Intermediate
	mockGreet               func(ctx context.Context, name string) (greeting string, err error)                 // MARKER: Greet
	mockAdopt               func(ctx context.Context, pet svcapi.Pet) (since time.Time, err error)              // MARKER: Adopt
	mockPing                func(ctx context.Context) (err error)                                               // MARKER: Ping
	mockDashboard           func(w http.ResponseWriter, r *http.Request) (err error)                            // MARKER: Dashboard
	mockProcessStep         func(ctx context.Context, flow *workflow.Flow, item string) (done bool, err error)  // MARKER: ProcessStep
	mockReviewStep          func(ctx context.Context, flow *workflow.Flow, count int) (countOut int, err error) // MARKER: ReviewStep
	mockMainFlowGraph       func(ctx context.Context) (graph *workflow.Graph, err error)                        // MARKER: MainFlow
	unsubMockMainFlow       func() error                                                                        // MARKER: MainFlow
	mockOnSrcEvent          func(ctx context.Context, detail string) (ok bool, err error)                       // MARKER: OnSrcEvent
	mockReconcile           func(ctx context.Context) (err error)                                               // MARKER: Reconcile
	mockOnObserveQueueDepth func(ctx context.Context) (err error)                                               // MARKER: QueueDepth
	mockOnChangedMaxItems   func(ctx context.Context) (err error)                                               // MARKER: MaxItems
}

// NewMock creates a new mockable version of the microservice.
func NewMock() *Mock {
	svc := &Mock{}
	svc.Intermediate = NewIntermediate(svc)
	svc.SetVersion(7357) // Stands for TEST
	return svc
}

// OnStartup is called when the microservice is started up.
func (svc *Mock) OnStartup(ctx context.Context) (err error) {
	if svc.Deployment() != connector.LOCAL && svc.Deployment() != connector.TESTING {
		return errors.New("mocking disallowed in %s deployment", svc.Deployment())
	}
	return nil
}

// OnShutdown is called when the microservice is shut down.
func (svc *Mock) OnShutdown(ctx context.Context) (err error) {
	return nil
}

// MockGreet sets up a mock handler for Greet.
func (svc *Mock) MockGreet(handler func(ctx context.Context, name string) (greeting string, err error)) *Mock { // MARKER: Greet
	svc.mockGreet = handler
	return svc
}

// Greet executes the mock handler.
func (svc *Mock) Greet(ctx context.Context, name string) (greeting string, err error) { // MARKER: Greet
	if svc.mockGreet != nil {
		greeting, err = svc.mockGreet(ctx, name)
	}
	return greeting, errors.Trace(err)
}

// MockAdopt sets up a mock handler for Adopt.
func (svc *Mock) MockAdopt(handler func(ctx context.Context, pet svcapi.Pet) (since time.Time, err error)) *Mock { // MARKER: Adopt
	svc.mockAdopt = handler
	return svc
}

// Adopt executes the mock handler.
func (svc *Mock) Adopt(ctx context.Context, pet svcapi.Pet) (since time.Time, err error) { // MARKER: Adopt
	if svc.mockAdopt != nil {
		since, err = svc.mockAdopt(ctx, pet)
	}
	return since, errors.Trace(err)
}

// MockPing sets up a mock handler for Ping.
func (svc *Mock) MockPing(handler func(ctx context.Context) (err error)) *Mock { // MARKER: Ping
	svc.mockPing = handler
	return svc
}

// Ping executes the mock handler.
func (svc *Mock) Ping(ctx context.Context) (err error) { // MARKER: Ping
	if svc.mockPing != nil {
		err = svc.mockPing(ctx)
	}
	return errors.Trace(err)
}

// MockDashboard sets up a mock handler for Dashboard.
func (svc *Mock) MockDashboard(handler func(w http.ResponseWriter, r *http.Request) (err error)) *Mock { // MARKER: Dashboard
	svc.mockDashboard = handler
	return svc
}

// Dashboard executes the mock handler.
func (svc *Mock) Dashboard(w http.ResponseWriter, r *http.Request) (err error) { // MARKER: Dashboard
	if svc.mockDashboard != nil {
		err = svc.mockDashboard(w, r)
	}
	return errors.Trace(err)
}

// MockProcessStep sets up a mock handler for ProcessStep.
func (svc *Mock) MockProcessStep(handler func(ctx context.Context, flow *workflow.Flow, item string) (done bool, err error)) *Mock { // MARKER: ProcessStep
	svc.mockProcessStep = handler
	return svc
}

// ProcessStep executes the mock handler.
func (svc *Mock) ProcessStep(ctx context.Context, flow *workflow.Flow, item string) (done bool, err error) { // MARKER: ProcessStep
	if svc.mockProcessStep != nil {
		done, err = svc.mockProcessStep(ctx, flow, item)
	}
	return done, errors.Trace(err)
}

// MockReviewStep sets up a mock handler for ReviewStep.
func (svc *Mock) MockReviewStep(handler func(ctx context.Context, flow *workflow.Flow, count int) (countOut int, err error)) *Mock { // MARKER: ReviewStep
	svc.mockReviewStep = handler
	return svc
}

// ReviewStep executes the mock handler.
func (svc *Mock) ReviewStep(ctx context.Context, flow *workflow.Flow, count int) (countOut int, err error) { // MARKER: ReviewStep
	if svc.mockReviewStep != nil {
		countOut, err = svc.mockReviewStep(ctx, flow, count)
	}
	return countOut, errors.Trace(err)
}

// MockMainFlow sets up a mock handler for the MainFlow workflow.
// The handler receives typed inputs from the workflow's state and returns typed outputs.
// A nil handler clears the mock.
func (svc *Mock) MockMainFlow(handler func(ctx context.Context, flow *workflow.Flow, item string, pet svcapi.Pet) (done bool, since time.Time, err error)) *Mock { // MARKER: MainFlow
	if svc.unsubMockMainFlow != nil {
		svc.unsubMockMainFlow()
		svc.unsubMockMainFlow = nil
	}
	if handler == nil {
		svc.mockMainFlowGraph = nil
		return svc
	}
	mockName := "MockMainFlow" + utils.RandomIdentifier(8)
	mockRoute := ":428/mock-main-flow-" + utils.RandomIdentifier(8)
	mockTaskURL := httpx.JoinHostAndPath(svc.Hostname(), mockRoute)
	svc.mockMainFlowGraph = func(ctx context.Context) (graph *workflow.Graph, err error) {
		g := workflow.NewGraph("MainFlow")
		g.AddTransition(mockTaskURL, workflow.END)
		return g, nil
	}
	err := svc.Subscribe(mockName, func(w http.ResponseWriter, r *http.Request) error {
		var f workflow.Flow
		if err := json.NewDecoder(r.Body).Decode(&f); err != nil {
			return errors.Trace(err)
		}
		snap := f.Snapshot()
		var in svcapi.MainFlowIn
		f.ParseState(&in)
		done, since, err := handler(r.Context(), &f, in.Item, in.Pet)
		if err != nil {
			return err // No trace
		}
		out := svcapi.MainFlowOut{Done: done, Since: since}
		f.SetChanges(out, snap)
		w.Header().Set("Content-Type", "application/json")
		return json.NewEncoder(w).Encode(&f)
	},
		sub.At("POST", mockRoute),
		sub.Task(svcapi.MainFlowIn{}, svcapi.MainFlowOut{}),
	)
	if err == nil {
		svc.unsubMockMainFlow = func() error { return svc.Unsubscribe(mockName) }
	}
	return svc
}

// MainFlow returns the workflow graph, or a mocked graph if MockMainFlow was called.
func (svc *Mock) MainFlow(ctx context.Context) (graph *workflow.Graph, err error) { // MARKER: MainFlow
	if svc.mockMainFlowGraph != nil {
		graph, err = svc.mockMainFlowGraph(ctx)
	}
	return graph, errors.Trace(err)
}

// MockOnSrcEvent sets up a mock handler for OnSrcEvent.
func (svc *Mock) MockOnSrcEvent(handler func(ctx context.Context, detail string) (ok bool, err error)) *Mock { // MARKER: OnSrcEvent
	svc.mockOnSrcEvent = handler
	return svc
}

// OnSrcEvent executes the mock handler.
func (svc *Mock) OnSrcEvent(ctx context.Context, detail string) (ok bool, err error) { // MARKER: OnSrcEvent
	if svc.mockOnSrcEvent != nil {
		ok, err = svc.mockOnSrcEvent(ctx, detail)
	}
	return ok, errors.Trace(err)
}

// MockReconcile sets up a mock handler for Reconcile.
func (svc *Mock) MockReconcile(handler func(ctx context.Context) (err error)) *Mock { // MARKER: Reconcile
	svc.mockReconcile = handler
	return svc
}

// Reconcile executes the mock handler.
func (svc *Mock) Reconcile(ctx context.Context) (err error) { // MARKER: Reconcile
	if svc.mockReconcile != nil {
		err = svc.mockReconcile(ctx)
	}
	return errors.Trace(err)
}

// MockOnObserveQueueDepth sets up a mock handler for OnObserveQueueDepth.
func (svc *Mock) MockOnObserveQueueDepth(handler func(ctx context.Context) (err error)) *Mock { // MARKER: QueueDepth
	svc.mockOnObserveQueueDepth = handler
	return svc
}

// OnObserveQueueDepth executes the mock handler.
func (svc *Mock) OnObserveQueueDepth(ctx context.Context) (err error) { // MARKER: QueueDepth
	if svc.mockOnObserveQueueDepth != nil {
		err = svc.mockOnObserveQueueDepth(ctx)
	}
	return errors.Trace(err)
}

// MockOnChangedMaxItems sets up a mock handler for OnChangedMaxItems.
func (svc *Mock) MockOnChangedMaxItems(handler func(ctx context.Context) (err error)) *Mock { // MARKER: MaxItems
	svc.mockOnChangedMaxItems = handler
	return svc
}

// OnChangedMaxItems executes the mock handler.
func (svc *Mock) OnChangedMaxItems(ctx context.Context) (err error) { // MARKER: MaxItems
	if svc.mockOnChangedMaxItems != nil {
		err = svc.mockOnChangedMaxItems(ctx)
	}
	return errors.Trace(err)
}
