/*
Copyright (c) 2023-2026 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cmd/genmock. DO NOT EDIT.

package perelementpipelineflow

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/fabric/sub"
	"github.com/microbus-io/fabric/utils"
	"github.com/microbus-io/fabric/workflow"

	"github.com/microbus-io/fabric/verify/perelementpipelineflow/perelementpipelineflowapi"
)

// Mock is a mockable version of the microservice, allowing functions, event sinks and web handlers to be mocked.
type Mock struct {
	*Intermediate
	mockTaskS                   func(ctx context.Context, flow *workflow.Flow, items []string) (itemsOut []string, err error)                        // MARKER: TaskS
	mockTaskH                   func(ctx context.Context, flow *workflow.Flow, item string) (itemUpper string, err error)                            // MARKER: TaskH
	mockTaskA                   func(ctx context.Context, flow *workflow.Flow, itemUpper string) (aProcessed string, err error)                      // MARKER: TaskA
	mockTaskB                   func(ctx context.Context, flow *workflow.Flow, itemUpper string) (bProcessed string, err error)                      // MARKER: TaskB
	mockTaskM                   func(ctx context.Context, flow *workflow.Flow, aProcessed string, bProcessed string) (setMerged []string, err error) // MARKER: TaskM
	mockTaskL                   func(ctx context.Context, flow *workflow.Flow, setMerged []string) (finalCount int, err error)                       // MARKER: TaskL
	mockPerElementPipelineGraph func(ctx context.Context) (graph *workflow.Graph, err error)                                                         // MARKER: PerElementPipeline
	unsubMockPerElementPipeline func() error                                                                                                         // MARKER: PerElementPipeline
}

// NewMock creates a new mockable version of the microservice.
func NewMock() *Mock {
	svc := &Mock{}
	svc.Intermediate = NewIntermediate(svc)
	svc.SetVersion(7357) // Stands for TEST
	return svc
}

// OnStartup is called when the microservice is started up.
func (svc *Mock) OnStartup(ctx context.Context) (err error) {
	if svc.Deployment() != connector.LOCAL && svc.Deployment() != connector.TESTING {
		return errors.New("mocking disallowed in %s deployment", svc.Deployment())
	}
	return nil
}

// OnShutdown is called when the microservice is shut down.
func (svc *Mock) OnShutdown(ctx context.Context) (err error) {
	return nil
}

// MockTaskS sets up a mock handler for TaskS.
func (svc *Mock) MockTaskS(handler func(ctx context.Context, flow *workflow.Flow, items []string) (itemsOut []string, err error)) *Mock { // MARKER: TaskS
	svc.mockTaskS = handler
	return svc
}

// TaskS executes the mock handler.
func (svc *Mock) TaskS(ctx context.Context, flow *workflow.Flow, items []string) (itemsOut []string, err error) { // MARKER: TaskS
	if svc.mockTaskS != nil {
		itemsOut, err = svc.mockTaskS(ctx, flow, items)
	}
	return itemsOut, errors.Trace(err)
}

// MockTaskH sets up a mock handler for TaskH.
func (svc *Mock) MockTaskH(handler func(ctx context.Context, flow *workflow.Flow, item string) (itemUpper string, err error)) *Mock { // MARKER: TaskH
	svc.mockTaskH = handler
	return svc
}

// TaskH executes the mock handler.
func (svc *Mock) TaskH(ctx context.Context, flow *workflow.Flow, item string) (itemUpper string, err error) { // MARKER: TaskH
	if svc.mockTaskH != nil {
		itemUpper, err = svc.mockTaskH(ctx, flow, item)
	}
	return itemUpper, errors.Trace(err)
}

// MockTaskA sets up a mock handler for TaskA.
func (svc *Mock) MockTaskA(handler func(ctx context.Context, flow *workflow.Flow, itemUpper string) (aProcessed string, err error)) *Mock { // MARKER: TaskA
	svc.mockTaskA = handler
	return svc
}

// TaskA executes the mock handler.
func (svc *Mock) TaskA(ctx context.Context, flow *workflow.Flow, itemUpper string) (aProcessed string, err error) { // MARKER: TaskA
	if svc.mockTaskA != nil {
		aProcessed, err = svc.mockTaskA(ctx, flow, itemUpper)
	}
	return aProcessed, errors.Trace(err)
}

// MockTaskB sets up a mock handler for TaskB.
func (svc *Mock) MockTaskB(handler func(ctx context.Context, flow *workflow.Flow, itemUpper string) (bProcessed string, err error)) *Mock { // MARKER: TaskB
	svc.mockTaskB = handler
	return svc
}

// TaskB executes the mock handler.
func (svc *Mock) TaskB(ctx context.Context, flow *workflow.Flow, itemUpper string) (bProcessed string, err error) { // MARKER: TaskB
	if svc.mockTaskB != nil {
		bProcessed, err = svc.mockTaskB(ctx, flow, itemUpper)
	}
	return bProcessed, errors.Trace(err)
}

// MockTaskM sets up a mock handler for TaskM.
func (svc *Mock) MockTaskM(handler func(ctx context.Context, flow *workflow.Flow, aProcessed string, bProcessed string) (setMerged []string, err error)) *Mock { // MARKER: TaskM
	svc.mockTaskM = handler
	return svc
}

// TaskM executes the mock handler.
func (svc *Mock) TaskM(ctx context.Context, flow *workflow.Flow, aProcessed string, bProcessed string) (setMerged []string, err error) { // MARKER: TaskM
	if svc.mockTaskM != nil {
		setMerged, err = svc.mockTaskM(ctx, flow, aProcessed, bProcessed)
	}
	return setMerged, errors.Trace(err)
}

// MockTaskL sets up a mock handler for TaskL.
func (svc *Mock) MockTaskL(handler func(ctx context.Context, flow *workflow.Flow, setMerged []string) (finalCount int, err error)) *Mock { // MARKER: TaskL
	svc.mockTaskL = handler
	return svc
}

// TaskL executes the mock handler.
func (svc *Mock) TaskL(ctx context.Context, flow *workflow.Flow, setMerged []string) (finalCount int, err error) { // MARKER: TaskL
	if svc.mockTaskL != nil {
		finalCount, err = svc.mockTaskL(ctx, flow, setMerged)
	}
	return finalCount, errors.Trace(err)
}

// MockPerElementPipeline sets up a mock handler for the PerElementPipeline workflow.
// The handler receives typed inputs from the workflow's state and returns typed outputs.
// A nil handler clears the mock.
func (svc *Mock) MockPerElementPipeline(handler func(ctx context.Context, flow *workflow.Flow, items []string) (finalCount int, err error)) *Mock { // MARKER: PerElementPipeline
	if svc.unsubMockPerElementPipeline != nil {
		svc.unsubMockPerElementPipeline()
		svc.unsubMockPerElementPipeline = nil
	}
	if handler == nil {
		svc.mockPerElementPipelineGraph = nil
		return svc
	}
	mockName := "MockPerElementPipeline" + utils.RandomIdentifier(8)
	mockRoute := ":428/mock-per-element-pipeline-" + utils.RandomIdentifier(8)
	mockTaskURL := httpx.JoinHostAndPath(svc.Hostname(), mockRoute)
	svc.mockPerElementPipelineGraph = func(ctx context.Context) (graph *workflow.Graph, err error) {
		g := workflow.NewGraph(perelementpipelineflowapi.PerElementPipeline.URL())
		g.AddTransition(mockTaskURL, workflow.END)
		return g, nil
	}
	err := svc.Subscribe(mockName, func(w http.ResponseWriter, r *http.Request) error {
		var f workflow.Flow
		if err := json.NewDecoder(r.Body).Decode(&f); err != nil {
			return errors.Trace(err)
		}
		snap := f.Snapshot()
		var in perelementpipelineflowapi.PerElementPipelineIn
		f.ParseState(&in)
		finalCount, err := handler(r.Context(), &f, in.Items)
		if err != nil {
			return err // No trace
		}
		out := perelementpipelineflowapi.PerElementPipelineOut{FinalCount: finalCount}
		f.SetChanges(out, snap)
		w.Header().Set("Content-Type", "application/json")
		return json.NewEncoder(w).Encode(&f)
	},
		sub.At("POST", mockRoute),
		sub.Task(perelementpipelineflowapi.PerElementPipelineIn{}, perelementpipelineflowapi.PerElementPipelineOut{}),
	)
	if err == nil {
		svc.unsubMockPerElementPipeline = func() error { return svc.Unsubscribe(mockName) }
	}
	return svc
}

// PerElementPipeline returns the workflow graph, or a mocked graph if MockPerElementPipeline was called.
func (svc *Mock) PerElementPipeline(ctx context.Context) (graph *workflow.Graph, err error) { // MARKER: PerElementPipeline
	if svc.mockPerElementPipelineGraph != nil {
		graph, err = svc.mockPerElementPipelineGraph(ctx)
	}
	return graph, errors.Trace(err)
}
