%%{init: {'themeVariables': {'lineColor': '#32a7c1', 'edgeLabelBackground': '#e5f4f3', 'textColor': '#434343', 'titleColor': '#32a7c1', 'clusterTextColor': '#32a7c1'}}}%%
graph LR
    classDef task fill:#32a7c1,color:#f4f2ef,stroke:#32a7c1
    classDef sub fill:#ed2e92,color:#f4f2ef,stroke:#ed2e92
    classDef term fill:#e5f4f3,color:#434343,stroke:#32a7c1

    _title{{"per-element-pipeline"}}:::term --> _start
    _start(( )):::term --> t0
    t0["taskS"]:::task
    t4["taskM"]:::task
    t5["taskL"]:::task
    subgraph fo_t0 ["for each in items"]
        direction LR
        t1["taskH"]:::task
        t2["taskA"]:::task
        t3["taskB"]:::task
    end
    t0 -->|"fan out"| t1
    t1 --> t2
    t1 --> t3
    t2 -->|"fan in"| t4
    t3 -->|"fan in"| t4
    t4 --> t5
    t5 --> _end(( )):::term
    style fo_t0 fill:#32a7c1,fill-opacity:0.15,stroke:#434343,stroke-dasharray:4 2
