# Copyright (c) 2023-2024 Microbus LLC and various contributors
# 
# This file and the project encapsulating it are the confidential intellectual property of Microbus LLC.
# Neither may be used, copied or distributed without the express written consent of Microbus LLC.

services:
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      COLLECTOR_OTLP_ENABLED: 'true'
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    networks:
      - microbus-network
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - microbus-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - microbus-network
    depends_on:
      - prometheus
    volumes:
      - ./grafana:/etc/grafana/provisioning/
  nats:
    image: nats:2-alpine
    ports:
      - "8222:8222"
      - "4222:4222"
    networks:
      - microbus-network
networks:
  microbus-network:
