graph LR
    classDef task fill:#32a7c1,color:#f4f2ef,stroke:#434343
    classDef sub fill:#ed2e92,color:#f4f2ef,stroke:#434343
    classDef term fill:#e5f4f3,color:#434343,stroke:#434343

    _title{{"chat-loop"}}:::term --> _start
    t4@{ shape: st-rect, label: "executeTool" }
    t2@{ shape: trap-t, label: "nextLLM" }
    _start(( )):::term --> t0["initChat"]:::task
    t0 --> t1["firstLLM"]:::task
    t1 --> t3["processResponse"]:::task
    t3 -->|"goto"| _end(( )):::term
    t3 -->|"for each in pendingToolCalls"| t4
    t4 -->|"fan-in"| t2
    t2 --> t3
    class t4 task
    class t2 task
