// Code generated by cmd/genmock. DO NOT EDIT.

package cancelbackpressureflow

import (
	"context"
	"testing"

	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/workflow"
	"github.com/microbus-io/testarossa"
)

func TestCancelbackpressureflow_Mock(t *testing.T) {
	t.Parallel()
	ctx := t.Context()

	mock := NewMock()
	mock.SetDeployment(connector.TESTING)

	t.Run("on_startup", func(t *testing.T) {
		assert := testarossa.For(t)
		err := mock.OnStartup(ctx)
		assert.NoError(err)
	})

	t.Run("on_shutdown", func(t *testing.T) {
		assert := testarossa.For(t)
		err := mock.OnShutdown(ctx)
		assert.NoError(err)
	})

	t.Run("bounce_and_cancel", func(t *testing.T) { // MARKER: BounceAndCancel
		assert := testarossa.For(t)

		mock.MockBounceAndCancel(func(ctx context.Context, flow *workflow.Flow, tag string) (tallied bool, err error) {
			return
		})
		var tag string
		_, err := mock.BounceAndCancel(ctx, nil, tag)
		assert.NoError(err)
	})

	t.Run("cancel_backpressure", func(t *testing.T) { // MARKER: CancelBackpressure
		assert := testarossa.For(t)

		mock.MockCancelBackpressure(func(ctx context.Context, flow *workflow.Flow, tag string) (tallied bool, err error) {
			return
		})
		graph, err := mock.CancelBackpressure(ctx)
		if assert.NoError(err) {
			assert.NotNil(graph)
		}
	})

}
