/*
Copyright (c) 2023-2026 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cmd/genmock. DO NOT EDIT.

package nestedfailfanoutflow

import (
	"context"
	"testing"

	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/workflow"
	"github.com/microbus-io/testarossa"
)

func TestNestedfailfanoutflow_Mock(t *testing.T) {
	t.Parallel()
	ctx := t.Context()

	mock := NewMock()
	mock.SetDeployment(connector.TESTING)

	t.Run("on_startup", func(t *testing.T) {
		assert := testarossa.For(t)
		err := mock.OnStartup(ctx)
		assert.NoError(err)
	})

	t.Run("on_shutdown", func(t *testing.T) {
		assert := testarossa.For(t)
		err := mock.OnShutdown(ctx)
		assert.NoError(err)
	})

	t.Run("task_a", func(t *testing.T) { // MARKER: TaskA
		assert := testarossa.For(t)
		mock.MockTaskA(func(ctx context.Context, flow *workflow.Flow) (outers []int, err error) { return })
		_, err := mock.TaskA(ctx, nil)
		assert.NoError(err)
	})

	t.Run("task_o", func(t *testing.T) { // MARKER: TaskO
		assert := testarossa.For(t)
		mock.MockTaskO(func(ctx context.Context, flow *workflow.Flow, outerItem int) (inners []int, currentOuter int, err error) { return })
		_, _, err := mock.TaskO(ctx, nil, 0)
		assert.NoError(err)
	})

	t.Run("task_i", func(t *testing.T) { // MARKER: TaskI
		assert := testarossa.For(t)
		mock.MockTaskI(func(ctx context.Context, flow *workflow.Flow, currentOuter int, innerItem int) (err error) { return })
		err := mock.TaskI(ctx, nil, 0, 0)
		assert.NoError(err)
	})

	t.Run("join_i", func(t *testing.T) { // MARKER: JoinI
		assert := testarossa.For(t)
		mock.MockJoinI(func(ctx context.Context, flow *workflow.Flow) (err error) { return })
		err := mock.JoinI(ctx, nil)
		assert.NoError(err)
	})

	t.Run("join_o", func(t *testing.T) { // MARKER: JoinO
		assert := testarossa.For(t)
		mock.MockJoinO(func(ctx context.Context, flow *workflow.Flow) (done bool, err error) { return })
		_, err := mock.JoinO(ctx, nil)
		assert.NoError(err)
	})

	t.Run("nested", func(t *testing.T) { // MARKER: Nested
		assert := testarossa.For(t)
		mock.MockNested(func(ctx context.Context, flow *workflow.Flow) (done bool, err error) { return })
		graph, err := mock.Nested(ctx)
		if assert.NoError(err) {
			assert.NotNil(graph)
		}
	})
}
