name: "Test"
on:
  push:
    branches:
      - "*"
      - "*/*"

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Run tests"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - run: go version
