# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-go

name: Test
on:
  pull_request:
    types: [opened, reopened, edited]
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - uses: actions/checkout@v4
      - name: Setup NATS server
        uses: onichandame/nats-action@master
        with:
          port: 4222
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true
          cache-dependency-path: go.sum
      - name: Go version
        run: go version
      - name: Run tests (NATS only)
        run: MICROBUS_SHORT_CIRCUIT=0 go test -count 1 -timeout 30s -cover ./...
      - name: Run tests (short-circuit only)
        run: go test -count 1 -timeout 30s -cover ./...
      - name: Run tests (NATS and short-circuit)
        run: MICROBUS_NATS=nats://127.0.0.1:4222 go test -count 1 -timeout 30s -cover ./...
