/*
Copyright (c) 2023-2026 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cmd/genmock. DO NOT EDIT.

// Code generated by cmd/genservice. DO NOT EDIT.

package accesstoken

import (
	"context"
	"testing"

	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/coreservices/accesstoken/accesstokenapi"
	"github.com/microbus-io/testarossa"
)

func TestAccesstoken_Mock(t *testing.T) {
	t.Parallel()
	ctx := t.Context()

	mock := NewMock()
	mock.SetDeployment(connector.TESTING)

	t.Run("on_startup", func(t *testing.T) {
		assert := testarossa.For(t)
		err := mock.OnStartup(ctx)
		assert.NoError(err)
	})

	t.Run("on_shutdown", func(t *testing.T) {
		assert := testarossa.For(t)
		err := mock.OnShutdown(ctx)
		assert.NoError(err)
	})

	t.Run("mint", func(t *testing.T) { // MARKER: Mint
		assert := testarossa.For(t)

		mock.MockMint(func(ctx context.Context, claims any) (token string, err error) {
			return
		})
		var claims any
		_, err := mock.Mint(ctx, claims)
		assert.NoError(err)
	})

	t.Run("j_w_k_s", func(t *testing.T) { // MARKER: JWKS
		assert := testarossa.For(t)

		mock.MockJWKS(func(ctx context.Context) (keys []accesstokenapi.JWK, err error) {
			return
		})
		_, err := mock.JWKS(ctx)
		assert.NoError(err)
	})

	t.Run("local_keys", func(t *testing.T) { // MARKER: LocalKeys
		assert := testarossa.For(t)

		mock.MockLocalKeys(func(ctx context.Context) (keys []accesstokenapi.JWK, err error) {
			return
		})
		_, err := mock.LocalKeys(ctx)
		assert.NoError(err)
	})

	t.Run("rotate_key", func(t *testing.T) { // MARKER: RotateKey
		assert := testarossa.For(t)

		mock.MockRotateKey(func(ctx context.Context) (err error) {
			return
		})
		err := mock.RotateKey(ctx)
		assert.NoError(err)
	})

}
